### ISSUE TITLE
Google Assistant: Lights working but unknown error

### ISSUE THREAD

**Issue by Freez** [DewGew/Domoticz-Google-Assistant#101]
When I use Google Assistant by giving a voice command it says: Unknown error for kitchen
The lights are working fine, there are no error's in the log.

I can't figure out how to solve this problem. Maybe this issue is linked to #100 but I guess not.

**Comment by K4CZP3R** [comment]
#98

**Comment by DewGew** [comment]
See #100

**Comment by K4CZP3R** [comment]
Syncing works with voice and with button. But when sending data to domoticz it sends some unknown char `¶`

```2020-01-23 20:53:44 - DEBUG - http://192.168.2.9:8080 "GET /json.htm?type=command¶m=switchlight&idx=9&switchcmd=On HTTP/1.1" 200 47```


it should be
```?type=command&param=switchlight``` and not ```?type=command¶m=switchlight```

**Comment by DewGew** [comment]
But does it work anyway?
