### ISSUE TITLE
Can't sync or control Domoticz-Google-Assistant

### ISSUE THREAD

**Issue by NeoRanga** [DewGew/Domoticz-Google-Assistant#102]
When I try to add the device in google home. I can login to Domoticz Google Assistant, and it loads, then I get kicked back to the add device screen. When I try to add the device again, I get a Not Found message. and the adress it tries to open is

`https://**<MY_SITE>**/https%3A%2F%2Foauth-redirect.googleusercontent.com%2Fr%2Fdomoticzassistant-2c9ee?code=.....&state=....

If I open the adress in Firefox and remove MySite and open https://oauth-redirect.googleusercontent.com/r/do... I get a "Logging in" message, but it takes me back to the add device screen and no device is added.

**Comment by NeoRanga** [comment]
Also I cant use the sync button.

Message
from Browser
> Page not found!: 404 Client Error: Not Found for url: https://homegraph.googleapis.com/v1/devices:requestSync

from Log
> 2020-01-22 12:49:51 - DEBUG - Starting new HTTPS connection (1): raw.githubusercontent.com:443
> 2020-01-22 12:49:51 - DEBUG - https://raw.githubusercontent.com:443 "GET /DewGew/Domoticz-Google-Assistant/beta/const.py HTTP/1.1" 200 11253
> 2020-01-22 12:49:58 - DEBUG - Starting new HTTPS connection (1): raw.githubusercontent.com:443
> 2020-01-22 12:50:03 - DEBUG - https://raw.githubusercontent.com:443 "GET /DewGew/Domoticz-Google-Assistant/beta/const.py HTTP/1.1" 200 11253
> 2020-01-22 12:50:03 - DEBUG - Starting new HTTPS connection (1): accounts.google.com:443
> 2020-01-22 12:50:04 - DEBUG - https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None
> 2020-01-22 12:50:04 - DEBUG - Starting new HTTPS connection (1): homegraph.googleapis.com:443
> 2020-01-22 12:50:04 - DEBUG - https://homegraph.googleapis.com:443 "POST /v1/devices:requestSync HTTP/1.1" 404 None


DZGA v1.5.6

**Comment by NeoRanga** [comment]
The first problem was an SSL problem. The letsencrypt cert didnt work on the proxy. With that fixed, I can add the device in Google Home. But all the sensors and lights are offline. And I still cant sync. New error code.

> Page not found!: 403 Client Error: Forbidden for url: https://homegraph.googleapis.com/v1/devices:requestSync

**Comment by DewGew** [comment]
See #97

**Comment by NeoRanga** [comment]
@DewGew I have tried it multiple times, but I cant get it to work. Started from scratch 3 times. I cant get the test version on the site to talk to dzga, how do I sync via voice?

**Comment by DewGew** [comment]
Say ”sync my devices”

**Comment by NeoRanga** [comment]
It didn't work either. I have also tried to insert the key in the config, but it failed also.

**Comment by DewGew** [comment]
try click test button in actions on google

**Comment by NeoRanga** [comment]
Tried the test button. Tried to type "Sync my devices" and it replied "We're sorry, but something went wrong. Please try again.
**** lämnade konversationen"
Updated today and created a new service account key and placed the "smart-home-key.json" in the Domoticz-Google-Assisstant folder, but I still can't sync. Can't control my devices via voice or on test console.
Still the same error message if i press the syncbutton on Domoticz-Google-Assistant page. "Page not found!: 403 Client Error: Forbidden for url: https://homegraph.googleapis.com/v1/devices:requestSync"
And I create my keys on the correct project on Google.

**Comment by DewGew** [comment]
403 usually get If u you set wrong url in actions on google or certificate is not valid. Try with ngrok also to see if you get same error

**Comment by NeoRanga** [comment]
Tried with ngrok, and I did to manage 1 sync in Domoticz-Google-Assistant, but after that it is the same again. Tried to turn the lights on or off in google home, but they are offline. If i open a thermometer it is offline and I don't see the temperature, but if I go into settings on the device and then back out, I can see the temperature. I was like this before I tried ngrok also.
This is what I get in ngrok console when I request a sync,
`POST /settings                 404 Not Found <----Trying to sync
GET  /favicon.ico              404 Not Found
GET  /settings                 200 OK  <---- Open Settings
`

**Comment by NeoRanga** [comment]
Where is token.py? When I try to access it, I get "Page not found".

**Comment by DewGew** [comment]
What python version do you use?

**Comment by NeoRanga** [comment]
~ $ python
Python 2.7.13 (default, Sep 26 2018, 18:42:22)
[GCC 6.3.0 20170516] on linux2

~ $ python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39)
[GCC 6.3.0 20170516] on linux


Yes, I changed the urls in Actions to ngrok.

**Comment by NeoRanga** [comment]
Removed the device from google home and tried to add it again. But now my auth key doesn't work. Same settings as when it worked.

**Comment by NeoRanga** [comment]
Did a test with a new Google Project and ngrok. But still the same. But i get this in ngrok log

POST /token                                                                  400 Bad Request
GET  /favicon.ico                                                            404 Not Found
GET  /https://oauth-redirect.googleusercontent.com/r/assistantdomoticz-**** 404 Not Found
GET  /favicon.ico                                                            404 Not Found
GET  /https://oauth-redirect.googleusercontent.com/r/assistantdomoticz-**** 404 Not Found
GET  /oauth                                                                  307 Temporary Redirect
POST /token                                                                  400 Bad Request
POST /login                                                                  301 Moved Permanently
GET  /favicon.ico                                                            404 Not Found
GET  /login                                                                  200 OK

**Comment by DewGew** [comment]
You ser the correct urls to put in action in the ui

**Comment by NeoRanga** [comment]
I use the correct urls, but this is the requests ngrok is getting.

**Comment by DewGew** [comment]
change clientid and secret
to "sampleClientId" and "sampleClientSecret"
then remove those in config.yaml / restart dzga server then update the urls in actions on google, press 'save' then 'test'

**Comment by NeoRanga** [comment]
Updated DZGA, and now it works. =D Don't know why. Thx for the help and the software.

**Comment by DewGew** [comment]
Great it works👍Kör hårt!
