### ISSUE TITLE
Need details for google conf

### ISSUE THREAD

**Issue by timetofly06** [DewGew/Domoticz-Google-Assistant#104]
Hi !

I followed the wiki until the action configuration where it is said to fill the reverse proxy url. 
Where can I get it as it is said on the dzga configuration file that we don't have to open any port on router and do not require a reverse proxy ? 
Can you give me an example ?
Does Ngrok inscription is really mandatory to keep connection alive ?

Thanks for all :-)

**Comment by DewGew** [comment]
Instantly create a public HTTPS URL. Don't have to open any port on router and do not require a reverse proxy.
Ngrok assigns random urls. When server restart the server gets a new url. When ngrok_tunnel set to true the auth token is required to keep the tunnel alive. Create account at ngrok.com and paste the token in configuration.

**Comment by timetofly06** [comment]
Thanks for your answer.

I'am trying to set it up on a Synology,  but I'm not very confortable with Ngrok and Google action console cause this is the first time I used it.

Created my account on Ngrok, pasted the auth token on config.yaml  file and restarted the server that fails with this message

_Installing package pyngrok
Traceback (most recent call last):
  File "/volume1/web/Domoticz-Google-Assistant/helpers.py", line 99, in <module>
    from pyngrok import ngrok
ImportError: No module named 'pyngrok'_

I downloaded the ngrok bynary and install the the token succesfully with the the ./ngrok authtoken command : _Authtoken saved to configuration file: /var/services/homes/admin/.ngrok2/ngrok.yml_

Restart server, but same errror unless I set to false the ngrok_tunnel flag in the conf file

**Comment by DewGew** [comment]
Did install with the install script in wiki for synology?

**Comment by DewGew** [comment]
If not goto Domoticz-Google-Assistant folder and run `pip install pyngrok`

**Comment by timetofly06** [comment]
Yes, I used the install script made for Synology.

The pip command is not found when I run it, It's quite strange ....Guess it should be included in the  Python3 package  (3.5.1 - 108 ) from Synology official source that I used prior to install dzga.

I am gonna try to re-install all and I let you know

**Comment by timetofly06** [comment]
Restart installation from scratch and unfortunately same error with pyngrok. I installed manually with success but got this error when lauching server.  Really would like to make it run, your project is really exciting !

_admin@HDSTATION:/volume1/web/Domoticz-Google-Assistant$ pip install pyngrok
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyngrok in /volume1/homes/admin/.local/lib/python3.5/site-packages (1.4.3)
Requirement already satisfied: future in /volume1/homes/admin/.local/lib/python3.5/site-packages (from pyngrok) (0.18.2)
Requirement already satisfied: pyyaml in /volume1/homes/admin/.local/lib/python3.5/site-packages (from pyngrok) (5.3)
admin@HDSTATION:/volume1/web/Domoticz-Google-Assistant$ sudo ./dzga-daemon status^C
admin@HDSTATION:/volume1/web/Domoticz-Google-Assistant$ cd ..
admin@HDSTATION:/volume1/web$ sudo ./dzga-daemon start
Starts Domoticz-Google-Assistant in moment ...
nohup: redirecting stderr to stdout
Domoticz-Google-Assistant is now running ...

admin@HDSTATION:/volume1/web$ sudo ./dzga-daemon status
Domoticz-Google-Assistant is Not running

admin@HDSTATION:/volume1/web$ cat dzga.log
Installing package pyngrok
Traceback (most recent call last):
  File "/volume1/web/Domoticz-Google-Assistant/helpers.py", line 107, in <module>
    from pyngrok import ngrok
ImportError: No module named 'pyngrok'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/volume1/web/Domoticz-Google-Assistant/__main__.py", line 4, in <module>
    from server import *
  File "/volume1/web/Domoticz-Google-Assistant/server.py", line 7, in <module>
    from smarthome import *
  File "/volume1/web/Domoticz-Google-Assistant/smarthome.py", line 14, in <module>
    import trait
  File "/volume1/web/Domoticz-Google-Assistant/trait.py", line 14, in <module>
    from helpers import SmartHomeError, configuration, logger, tempConvert
  File "/volume1/web/Domoticz-Google-Assistant/helpers.py", line 110, in <module>
    pip.main(['install', 'pyngrok'])
AttributeError: 'function' object has no attribute 'main'
Loading configuration...
admin@HDSTATION:/volume1/web$_

**Comment by DewGew** [comment]
I have dzga installed in a synology DS216se.  Its working fine. Just follow the wiki here in github.
dzga will be installed in virtual enviroment if you run the install script for synology.

Run manually:

```
cd /volume1/${USER}/ #Change to install folder
source Domoticz-Google-Assistant/env/bin/activate #Activates enviroment
pip install pyngrok #Install pyngrok package in the enviroment
python3 Domoticz-Google-Assistant #Manually run dzga
```

There is a built in reverse proxy and DDNS in synology better to use that before ngrok.

**Comment by timetofly06** [comment]
Great !!! it works fine :-)

I ran the commands as described in your last post and tunnel now works fine. I'm wondering where was the problem ...? Now  I can stop the server, and restart it normally  with  the **sudo ./dzga-daemon start** command :-)

So I can see the new associated service including the 22 devices set in Domoticz under my Google Home Assistant,

But, voice activation is not clear for me ... Sorry :-) !

My invocation name in google console is "Domotic'
Let's say I have those two devices : 

Idx=1 name=volet type=group State=scene  (room has no value)
Idx=2 name=portail type=push state=on (room has no value)

Do I have to add <voicecontrol> tag in the file in the config.yaml like this ?

<voicecontrol>
  nicknames = portal
  room = 
  ack = False
  report_state = false
</voicecontrol>

And how to invoke from Google assistant ? Hey google, open the portal ? or "Hey google" Domotic ( which is the invocation name) open the portal ?

Sorry for all my questions ...

**Comment by DewGew** [comment]
Nicknames, rooms, ack and report_state can be set in the Domoticz user interface. Simply put the device configuration in the device description, in a section between <voicecontrol> tags like:
```
<voicecontrol>
  nicknames = Portal
  report_state = false
</voicecontrol>
```
Other parts of the description are ignored, so you can still leave other useful descriptions. Every variable should be on a separate line.

Use a push button: 'Hey google, turn on portal'
Usa a scene: 'Hey google, turn on volet'
Those dont have any 'Off' states
