### ISSUE TITLE
Persistent and duplicated device when changing type

### ISSUE THREAD

**Issue by Potjoe-97** [DewGew/Domoticz-Google-Assistant#106]
Hello everyone, first of all thank your very much for all the work done on this great project !

**Describe the bug:**  
After changing a device type from light to fan in domoticz, and with the proper image_override parameter, the device (idx 56) seems to have been duplicated, according to the requests sent by GA. 

However, the device appears only once, in the dzga's device list and in Google Home app., 

**Logs:**

The request for an "on" command : 

```
2020-01-26 17:39:22 - INFO - Request {
  "inputs": [
    {
      "context": {
        "locale_country": "FR",
        "locale_language": "fr"
      },
      "intent": "action.devices.EXECUTE",
      "payload": {
        "commands": [
          {
            "devices": [
              {
                "id": "Light56"
              },
              {
                "id": "Fan56"
              }
            ],
            "execution": [
              {
                "command": "action.devices.commands.OnOff",
                "params": {
                  "on": true
                }
              }
            ]
          }
        ]
      }
    }
  ],
```
You can clearly see the two duplicated devices being sollicitated. 

And the error : 

```
2020-01-26 17:39:22 - INFO - Response {
  "requestId": ,
  "payload": {
    "commands": [
      {
        "ids": [
          "Light56"
        ],
        "status": "ERROR",
        "errorCode": "deviceOffline"
      },
      {
        "ids": [
          "Fan56"
        ],
        "status": "SUCCESS",
        "states": {
          "on": true
        }
      }
    ]
  }
}
```

The issue is bothering since any vocal command passed through my nest mini result with "I switched on the device. However, the device is not available" answer. 

**Desktop **
 - Domoticz version Stable 4.10717
 - Dzga version 1.5.7
 - Running on Raspberry pi 2

**Comment by DewGew** [comment]
When changing device or remove a device you have to make new sync

**Comment by Potjoe-97** [comment]
Sorry I haven't mentioned, but I already synced device with the sync devices button on the settings'page.

**Comment by DewGew** [comment]
I try to reproduce this

**Comment by Potjoe-97** [comment]
Thanks, tell me if you need anything to provide more details.

**Comment by DewGew** [comment]
I can't reproduce this. I changed name in domoticz, change icon, turn on/off without sync. It does not change Type until I request for a sync.

I run dzga in a synology with python 3.5.1, Latetst domoticz beta.
Also tryed fzga in RPI 2b with python 3.5.3, Latestet domoticz beta with same result
