### ISSUE TITLE
Running in main console

### ISSUE THREAD

**Issue by NeoRanga** [DewGew/Domoticz-Google-Assistant#108]
Hi, I have installed via the installation-script thru SSH. When i checked the screen connected to the RaspberryPi the script was running in foreground on the main console.

**Comment by DewGew** [comment]
I don't have any screen connected. I cant reproduce this

**Comment by bizziebis** [comment]
I also noticed this when running on a VM. I solved it by adding
`StandardOutput=null`
to dzga.service

I don't know if this will cause issues though.

**Comment by NeoRanga** [comment]
I will try that.

**Comment by NeoRanga** [comment]
@bizziebis It worked in a way. I don't see the output at boot anymore, but the login prompt doesn't appear when boot is finished.

**Comment by DewGew** [comment]
Try this:
```
[Service]
StandardOutput=null
StandardError=journal
```
and remove
`StandardInput=tty-force`

**Comment by NeoRanga** [comment]
@DewGew Tried it, but still no login after boot.

**Comment by DewGew** [comment]
Maybe standardInput need to be there anyway
