### ISSUE TITLE
Not linking hue scenes from domoticz, it does link hue devices from domoticz

### ISSUE THREAD

**Issue by vreesie18** [DewGew/Domoticz-Google-Assistant#119]
hi everybody,

Domoticzs is my central hub for all my home automation (many scripts). Thats the reason was my harmony and hue devices and scenes are all ported to and in Domoticz. I am very happy with dzga.

I have the following problem. I can link my hue devices from domoticz to Google Home by dzga  but.....this doesn't seem to work for hue scenes ?

Is this correct or am I doing someting wrong ?

Regards,
Andre

**Comment by DewGew** [comment]
How does the hue scenes apear in domoticz? I dont have any hue

**Comment by vreesie18** [comment]
![image](https://user-images.githubusercontent.com/37900374/74453787-2f54f280-4e83-11ea-85da-e7c7e038ff2e.png)

**Comment by vreesie18** [comment]
![image](https://user-images.githubusercontent.com/37900374/74453905-5b707380-4e83-11ea-8116-39be2df1f2ba.png)

Snake is a device, a Hue bulb
Scene soft is a scene

**Comment by vreesie18** [comment]
{
	"AddjMulti" : 1.0,
	"AddjMulti2" : 1.0,
	"AddjValue" : 0.0,
	"AddjValue2" : 0.0,
	"BatteryLevel" : 255,
	"Color" : "{\"b\":129,\"cw\":0,\"g\":211,\"m\":3,\"r\":254,\"t\":0,\"ww\":0}",
	"CustomImage" : 0,
	"Data" : "Set Color",
	"Description" : "Controlicz: Snake",
	"DimmerType" : "abs",
	"Favorite" : 1,
	"HardwareID" : 12,
	"HardwareName" : "hue",
	"HardwareType" : "Philips Hue Bridge",
	"HardwareTypeVal" : 38,
	"HaveDimmer" : true,
	"HaveGroupCmd" : false,
	"HaveTimeout" : false,
	"ID" : "00000002",
	"Image" : "Light",
	"IsSubDevice" : false,
	"LastUpdate" : "2020-02-13 17:04:06",
	"Level" : 100,
	"LevelInt" : 100,
	"MaxDimLevel" : 100,
	"Name" : "Snake",
	"Notifications" : "false",
	"PlanID" : "11",
	"PlanIDs" : [ 11, 16 ],
	"Protected" : false,
	"ShowNotifications" : true,
	"SignalLevel" : "-",
	"Status" : "Set Level: 100 %",
	"StrParam1" : "",
	"StrParam2" : "",
	"SubType" : "RGBWW",
	"SwitchType" : "Dimmer",
	"SwitchTypeVal" : 7,
	"Timers" : "false",
	"Type" : "Color Switch",
	"TypeImg" : "dimmer",
	"Unit" : 1,
	"Used" : 1,
	"UsedByCamera" : false,
	"XOffset" : "0",
	"YOffset" : "0",
	"idx" : "1733"
},
{
	"AddjMulti" : 1.0,
	"AddjMulti2" : 1.0,
	"AddjValue" : 0.0,
	"AddjValue2" : 0.0,
	"BatteryLevel" : 255,
	"CustomImage" : 0,
	"Data" : "On",
	"Description" : "",
	"DimmerType" : "none",
	"Favorite" : 0,
	"HardwareID" : 12,
	"HardwareName" : "hue",
	"HardwareType" : "Philips Hue Bridge",
	"HardwareTypeVal" : 38,
	"HaveDimmer" : true,
	"HaveGroupCmd" : false,
	"HaveTimeout" : false,
	"ID" : "00000819",
	"Image" : "Push",
	"InternalState" : "On",
	"IsSubDevice" : false,
	"LastUpdate" : "2020-02-13 17:03:59",
	"Level" : 0,
	"LevelInt" : 0,
	"MaxDimLevel" : 100,
	"Name" : "Scene Soft",
	"Notifications" : "false",
	"PlanID" : "11",
	"PlanIDs" : [ 11, 16 ],
	"Protected" : false,
	"ShowNotifications" : true,
	"SignalLevel" : "-",
	"Status" : "",
	"StrParam1" : "",
	"StrParam2" : "",
	"SubType" : "RGBW",
	"SwitchType" : "Push On Button",
	"SwitchTypeVal" : 9,
	"Timers" : "false",
	"Type" : "Color Switch",
	"TypeImg" : "push",
	"Unit" : 1,
	"Used" : 1,
	"UsedByCamera" : false,
	"XOffset" : "0",
	"YOffset" : "0",
	"idx" : "3981"
},

**Comment by DewGew** [comment]
Scenes is not visual in google home app. Do you see it in devices in dzga userinterface?

**Comment by DewGew** [comment]
It should work with voice e.g ”Hey google. Activate Scene soft”

**Comment by vreesie18** [comment]
I can tsee the hue devices in the dzga user intererfaces but not the hue scenes. I can see in the Google Home app that the scenes are not present from the dzga connection. Asking Google to do scene stuff doesn't work either.

Logically it seems to me that in the link from domoticz to dzga the scenes are not included for some reason. I would say, check the code :-)

**Comment by vreesie18** [comment]
![image](https://user-images.githubusercontent.com/37900374/74465790-536dff00-4e96-11ea-8f24-94deb5a32f30.png)

**Comment by DewGew** [comment]
Do you have other scenes. Does those work?

**Comment by vreesie18** [comment]
Yes I have but none of them work.

**Comment by DewGew** [comment]
> its not a scene like in domoticz.. its a push button. I think its not added yet to dzga. I will take look at this

**Comment by vreesie18** [comment]
No it's a hue scene and I changed its type in domoticz to type push button because the scene itself is not a state but more like an action. I would be very nice if this good be fixed. If it all works I kick Alexa en HA-bridge out :-)  Please keep me informed and many thanks for now!

**Comment by DewGew** [comment]
Try out latest Beta V.1.5.10

**Comment by vreesie18** [comment]
TESTED, WORKS, great feature fix, thanks!!!! 

I will continue testing/using dzga. Also the working of Harmony from Domoticz to dzga will be an interesting one.

Regards,
Andre
