### ISSUE TITLE
Update for chapter 5 of the installation guide

### ISSUE THREAD

**Issue by robertdelpeut** [DewGew/Domoticz-Google-Assistant#122]
Chapter five of the intallation guide did not work exactly as described, for me. I couldn't find the share icon. Instead of this icon I had to click the three dots next to my profile icon, then 'Manage user access' and 'Add' where I could add a new member.

I think this part of the guide needs an update, besides that it is working great and running within an hour.

**Comment by DewGew** [comment]
I have updated wiki to:

> If you want to allow other household users to control the devices:
> - Go to [Actions on Google Console](https://console.actions.google.com/).
> - Click three dots icon next to your profile icon, then click `Manage user access`:
>   - In [Google Cloud Platform](https://console.cloud.google.com/iam-admin/iam) click `ADD`.
>   - type the new user’s Google Account mail address as `New member`.
>   - `Select a role`  choose `Project -> Viewer`.
>   - click `SAVE`
> - Have the new user go to their Google Home app to add "[test]Your Appname" to their account. Login with Oauth credentials from configuration
