### ISSUE TITLE
set thermostat temperature range

### ISSUE THREAD

**Issue by wewa00** [DewGew/Domoticz-Google-Assistant#126]
Hello,

I use a Domoticz Dummy device of type Thermostat to set the setpoint for the temperature control of a warm water boiler. The problem here is, that the temperature range in Google Home reaches from 10°C to 32°C for every thermostat. But I need to set the setpoint for the boiler at about 55°C.

As far as I can see, Google provides the possibility to control the temperature range of a thermostat (search for thermostatTemperatureRange at https://developers.google.com/assistant/smarthome/traits/temperaturesetting). I suggest to make it possible to control this temperature range within the description field within Domoticz (e.g. `<voicecontrol>
  thermostatTemperatureRange = 45, 65
</voicecontrol>`).

Best regards,
wewa

**Comment by DewGew** [comment]
I look into this, should be possible.

**Comment by DewGew** [comment]
Its seem like Google dont support custom range for thermostats. The above works if and only if the device supports heatcool mode.

**Comment by wewa00** [comment]
Thank you so far.
Seems a little weird, the documentation suggests to use minThresholdCelsius and maxThresholdCelsius for setting the temperature range but does not state that this is depending on the actual mode.

What do you get if those traits are used in heating only mode?

**Comment by DewGew** [comment]
I tryed with and and it didnt work. I also read somewhere that google dont support custom range for theremostat.
https://stackoverflow.com/questions/59236298/smart-home-temperaturesetting-readingcelsius-custom-range

**Comment by wewa00** [comment]
`{
  "requestId": "ff36a3cc-ec34-11e6-b1a0-64510650abcf",
  "payload": {
    "agentUserId": "1836.15267389",
    "devices": [
      {
        "id": "123",
        "type": "action.devices.types.THERMOSTAT",
        "traits": [
          "action.devices.traits.TemperatureSetting"
        ],
        "name": {
          "name": "Homer Simpson Thermostat",
          "nicknames": [
            "living room thermostat"
          ]
        },
        "willReportState": true,
        "attributes": {
          "availableThermostatModes": "heat",
          "thermostatTemperatureUnit": "C",
          "thermostatTemperatureRange": {
            "minThresholdCelsius": 10.0,
            "maxThresholdCelsius": 20.0
           }
        }
      }
    ]
  }
}
`

**Comment by DewGew** [comment]
I have tryed this out but it dont work for me. I found this also:

https://www.reddit.com/r/GoogleAssistantDev/comments/f3bpur/thermostat_temperature_range/

**Comment by wewa00** [comment]
Hi DewGew,

any news on this issue?

Best regards
wewa
