### ISSUE TITLE
merge Dummy Temp and Dummy Thermostat as one Thermostat within Google Home

### ISSUE THREAD

**Issue by wewa00** [DewGew/Domoticz-Google-Assistant#127]
Hello,

in Domoticz I use a Dummy device of type Thermostat to set the setpoint for the temperature control of a warm water boiler and I use a Dummy device of type Temp to display the actual water temperature within the boiler. So those two devices correspond to one "thermostat control" (setpoint and actual value). But within Google Home there are two thermostats displayed and there is no possibility to merge them.

A feature would be great which allows to merge those two devices within Domoticz-Google-Assistant (e.g. using the description field within Domoticz `<voicecontrol> </voicecontrol>`).

Best regards,
wewa

PS: This request may be a duplicate to #114.

**Comment by DewGew** [comment]
Why merge temp with an theromostat? Its possible to view actual temp already with thermostat in domoticz?

**Comment by wewa00** [comment]
I fear this ist not possible with the Dummy Thermostat. The actual type of this device is "Thermostat Setpoint" and has only a setpoint value and no actual or ambient value.
Which thermostat device do you have in mind?

**Comment by DewGew** [comment]
I see now this updates the setpoint also

**Comment by DewGew** [comment]
Try latest Beta

**Comment by wewa00** [comment]
I gave it a try, but only the "hide" function is working.
The merge of a dummy thermostat with a dummy temperature is not working.
I was not sure if `merge_temp_idx = '123'` or `merge_temp_idx = 123` should be used in description in domoticz. So I gave both a try. But still Google Assistant does only displays the setpoint temperature of the thermostat as ambient temperature.

Please write if you need additional debug data.

**Comment by DewGew** [comment]
There is a small bug. The idx for the temp device need to be lower then the thermostat

**Comment by wewa00** [comment]
I have considered the idx issue and now also tried it with config.yaml. But still not working.

**Comment by DewGew** [comment]
Strange. I dont have any issues. Ay errors in logs?

```
Device_Config:
  234:
    actual_temp_idx: '123'
```

**Comment by wewa00** [comment]
Maybe that is the issue: You now wrote to use `actual_temp_idx` but in your changeset description you wrote to use `merge_temp_idx`.
Could this be the issue?

I'll check for logs at the next possibility.

**Comment by DewGew** [comment]
:) My fault. I change that just before publishing

**Comment by wewa00** [comment]
Tested it now with `actual_temp_idx` in description in domoticz and everything worked now (hide temperature in google assistant and show the ambient temperature for the thermostat).

Thank you so far. Great work :D, But keep on to fix the issue which needs to keep the temp idx below the thermostat idx ;-)
