### ISSUE TITLE
Hide devices from Google Assistant

### ISSUE THREAD

**Issue by wewa00** [DewGew/Domoticz-Google-Assistant#129]
Hello,

IMHO a possibility to hide devices from Google Assistant would bei great so that they are not seen and Not controlable by/from Google Assistant (e.g. with config.yaml or device description).

Ist ist possible right now or have you already thought about that?

Best regards,
wewa

**Comment by DewGew** [comment]
Already working on this :)

**Comment by DewGew** [comment]
Work around is to add your device you want to a room then add room idx in configuration

**Comment by DewGew** [comment]
Try latest Beta

**Comment by wewa00** [comment]
Thank you for that. The "hide" function is working with this revision.
