### ISSUE TITLE
Merge device idx

### ISSUE THREAD

**Issue by DewGew** [DewGew/Domoticz-Google-Assistant#134]
**Describe the bug:**  
When merge temp or selector device to thermostat, idx have to be lower than thermostat idx.

**Desktop (please complete the following information):**
 - Domoticz version, all
 - Dzga version 1.6.2 
 - Python Version 3.5, 3.6, 3.7, 3.8

**Smartphone (please complete the following information):**
 - Device: All

**Comment by wewa00** [comment]
Are you sure this is still an issue?
I use a thermostat with idx 20 and the actual temp has idx 47. The log displays following error, but temperature with idx 47 gets hidden. And thermostat (including setpoint and actual temperature) is displayed correctly within Google Home.
```
2020-04-25 13:18:51 - ERROR - Merge Error, Cant find temperature device with idx 47
2020-04-25 13:18:51 - ERROR - Make sure temperature device has a idx below 20
`````

**Comment by DewGew** [comment]
I will look into to this ..

**Comment by DewGew** [comment]
Can someone else confirm this?

**Comment by frankdpGH** [comment]
Hi,
Did some testing on 1.7.8 and dummy sensors.
I can confirm a merge error message in all cases but it is working. 

Have a thermostat/setpoint idx 167 and a temperature measurement idx 107.
It's working fine but Error message came :
2020-05-22 18:17:32 - ERROR - Merge Error, Cant find temperature device with idx 107
2020-05-22 18:17:32 - ERROR - Make sure temperature device has a idx below 167

Then changed temperature to another idx 178
2020-05-22 18:45:03 - ERROR - Merge Error, Cant find temperature device with idx 178
2020-05-22 18:45:03 - ERROR - Make sure temperature device has a idx below 167

Google Home is showing the correct information and setpoint is working in both cases.

**Comment by DewGew** [comment]
ok great thanks

**Comment by DewGew** [comment]
Merge devices seems to work anyway but there is still an exception. Need more feedback

**Comment by DewGew** [comment]
Close this for now..
