### ISSUE TITLE
Feedback Timer function

### ISSUE THREAD

**Issue by DewGew** [DewGew/Domoticz-Google-Assistant#136]
In latest beta I added timer function for lights, switches, fan, heater, kettle. 

To make this work you need Domoticz version **above** 4.11687 (dzVents 3.0.0). Also you need to add a dzVents script in Domoticz to act like a timer. You can name the script what ever you want.

dzVents script:
```lua
return {
	on = {
        customEvents = { 'TIMER' },
	},
	execute = function(dzga, item)
	    local device = dzga.devices(item.data.idx)
	    
	    if (device.active and item.data.cancel) then
	        dzga.log('Stop timer for ' .. device.name, dzga.LOG_FORCE)
	        device.cancelQueuedCommands()
        else
            dzga.log('No timer is running for' .. device.name, dzga.LOG_FORCE)
        end
        if  item.data.on == true then
            device.cancelQueuedCommands()
            device.switchOn()
            dzga.log('Switch ' .. device.name .. ' On for: ' .. item.data.time .. ' sec', dzga.LOG_FORCE)
            device.switchOff().afterSec(item.data.time)
        end
	end
}
```
Now you can use timer like:
_"Turn on kithen light for 5 minutes"_ or _"Turn on heater for 30 minutes"_
To cancel timer:
_"Stop kitchen light timer"_ (you have to turn off light/switch manually)
If you set a timer before the time run out. Time resets with new time.

**Feel free to improve!**

**Comment by HoekieN** [comment]
Really nice new feature, works good so far with the lights that i tested :)

**Comment by DewGew** [comment]
I have some issues with this function. Anyone more?
