### ISSUE TITLE
Speakers

### ISSUE THREAD

**Issue by eldigo** [DewGew/Domoticz-Google-Assistant#14]
Are you able to implement speakers based on this comment?

https://github.com/actions-on-google/smart-home-nodejs/issues/253#issuecomment-451782961

**Comment by DewGew** [comment]
You want to control volume?

**Comment by eldigo** [comment]
Yes volume controle.
Hey Google turn up the volume.. or set the volume to 20.

Currently volume is controlled like a light dimmer which is a bit
impractical

Op do 13 jun. 2019 23:23 schreef DewGew <notifications@github.com>:

**Comment by DewGew** [comment]
I take a look at this. Should not be a problem

**Comment by DewGew** [comment]
Added to latest #18

**Comment by eldigo** [comment]
Please add "TYPE_SPEAKER" to the config import in smarthome.py to get it wokring

**Comment by DewGew** [comment]
You have to manually copy missing variables from default_config.py
