### ISSUE TITLE
Ack and Switch Protection does not work

### ISSUE THREAD

**Issue by g1r1** [DewGew/Domoticz-Google-Assistant#145]
I am not able to get the ack = True or Switch Protection to work and I am not sure what I am doing wrong. FYI I don't have Homegraph setup; I am not sure that matters does it? I am able to Sync devices with "Sync all devices" command.

My language is "en". 

Ack issue
If I setup a switch with **ack** it displays "Do you want to switch on the device" on the Google Nest hub. If I say "Yes" or "No", the hub acknowledges it with something like "cool" but does not do anything. At the same time, if I press On the Yes or No that's displayed on the screen it does work.  So, it's not accepting a verbal Yes or No.

Switch Protection
This does not work at all. If I set it on, the hub displays the pin entry screen. Irrespective of the code entry or verbal pin it does not work and shows an error as "something went wrong with the device". If I enter a wrong passcode it does return with incorrect passcode.

Edit:
I also tried now with enabling HomeGraph and Smart-home-key. No luck.

**Comment by DewGew** [comment]
About Ack function, do you use english or other language?

**Comment by g1r1** [comment]
Just pulled the latest update. Now, I am able to use the 2FA pin code but again like the "ack" issue voice response does not work. If I enter the pin code on the nest hub screen it works fine.

When I try speaking the pin, it just responds with "I don't know how to help with that".  Seems to just ignore the voice input. I also tried with a Google Home Mini just to verify if it's an issue with a screen based assistant.

Do you think this a bug with Google's implementation?

**Comment by DewGew** [comment]
I manage to get it to work. But lately I have to try several times. Do you use multiple languages in Google Assistant? More than just english?

**Comment by g1r1** [comment]
Just english.

**Comment by DewGew** [comment]
https://issuetracker.google.com/issues/150292214

**Comment by DewGew** [comment]
I test my setup and it seems to work correct now. I think Google have fixed the issues with language support also. Please confirm.

**Comment by g1r1** [comment]
Yes. Thanks it's working now; seems Google has fixed this issue, though the issue at their end is still open.

Actually, now that  this is fixed is there a possibility of introducing different pin codes using <voicecontrol> tags? This will allow different pin codes for different things specifically for google assistant devices. What do you think?
