### ISSUE TITLE
Docker container doesn't start

### ISSUE THREAD

**Issue by dfandrew** [DewGew/Domoticz-Google-Assistant#148]
The conteiner does not start.
On the logs i can see only:
`standard_init_linux.go:211: exec user process caused "exec format error"`

Raspberry PI with Raspbian GNU/Linux 9 (stretch)
Docker version 19.03.8, build afacb8b

Thank you.

**Comment by DewGew** [comment]
Did you use docker-compose file?

**Comment by dfandrew** [comment]
Yes. I used it.

**Comment by mlstolk** [comment]
I can confirm this issue on a Raspberry Pi 3 with Buster.

**Comment by dfandrew** [comment]
Hi, maybe the problem is jfloff/alpine-python:3.7-slim. I try to use the image directly and I have the same error.
Why did you use the alpine version?

**Comment by DewGew** [comment]
There was another user that added this. Try another image maybe you can find anyone that works

**Comment by dfandrew** [comment]
The problem is the the image used in Dockerfile is no suitable for ARM.
For Raspberry Pi (ARM Architecture) I modified the Dockerfile in this way:

`FROM arm32v6/python:3.7-alpine
WORKDIR /usr/src/app
RUN mkdir -p config
COPY *.py /
COPY *.html /
COPY requirements/pip-requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt
# Create volume
VOLUME /config
# Configure Services and Port
CMD ["python", "/__main__.py"]
EXPOSE 3030`

and now the conteiner is up.

**Comment by DewGew** [comment]
Thanks, ill try to figure out how to add this to dockerhub

**Comment by DewGew** [comment]
I added this to wiki:
 https://github.com/DewGew/Domoticz-Google-Assistant/wiki/DZGA-with-Docker#docker-on-raspberry-pi-arm32v6

Please confirm that my instructions works.

**Comment by dfandrew** [comment]
It seems correct

**Comment by tofra** [comment]
Building fails on my RPi3b:
```
Building dz-googleassistant
Step 1/11 : FROM arm32v6/python:3.7-alpine
 ---> 7e50f5dc1bd8
Step 2/11 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 5e671e1d18ad
Step 3/11 : RUN mkdir -p config
 ---> Using cache
 ---> 49268485e102
Step 4/11 : COPY *.py /
 ---> Using cache
 ---> f2a6313927e6
Step 5/11 : COPY templates/ /templates/
 ---> Using cache
 ---> 9bfd8404b007
Step 6/11 : COPY static/ /static/
 ---> Using cache
 ---> 9c53206bc7a4
Step 7/11 : COPY requirements/pip-requirements.txt /requirements.txt
 ---> Using cache
 ---> 5b972dd8e211
Step 8/11 : RUN pip install --no-cache-dir -r /requirements.txt
 ---> Running in 1b84109c6838
Fatal Python error: _Py_InitializeMainInterpreter: can't initialize time
PermissionError: [Errno 1] Operation not permitted

Current thread 0x76f20390 (most recent call first):
ERROR: Service 'dz-googleassistant' failed to build: The command '/bin/sh -c pip install --no-cache-dir -r /requirements.txt' returned a non-zero code: 132
```
