### ISSUE TITLE
Setting for Monit config to check if dzga is running

### ISSUE THREAD

**Issue by vreesie18** [DewGew/Domoticz-Google-Assistant#149]
Can someone please provide me the correct settings for the config linux Monit utility so I can check if dzga is still running ?!

So far, I came to something like this but Monit will not start, config appears to be incorrect.

############
############
check program dzga with path /root/Domoticz-Google-Assistant/
    start program = "/usr/sbin/service dzga start" with timeout 60 seconds
    stop program  = "/usr/sbin/service dzga stop"
    if failed host 127.0.0.1 port 3030 with timeout 30 seconds for 5 cycles then restart
    if failed url http://192.168.1.28:3030/settings with timeout 30 seconds for 5 cycles then restart

Thank you!!

Regards,
Andre

**Comment by DewGew** [comment]
Are you runnig in raspian,  ubuntu or ?

**Comment by vreesie18** [comment]
Ubuntu 20.04 LTS

**Comment by DewGew** [comment]
check program dzga with path /etc/systemd/system/dzga/
start program = "/etc/systemd/system/dzga start" with timeout 60 seconds
stop program = "sudo systemtcl stop"
if failed host 127.0.0.1 port 3030 with timeout 30 seconds for 5 cycles then restart
if failed url http://192.168.1.28:3030/settings with timeout 30 seconds for 5 cycles then restart

**Comment by DewGew** [comment]
You cant use "check program" it dount find tha python program you need to use "check process", but for that you need a find pidfile for dzga but there is none. (maybe I add that later)

**Comment by vreesie18** [comment]
Exactly my finding...no pid

**Comment by vreesie18** [comment]
Smells like feature request :-)

**Comment by DewGew** [comment]
I have added pidfile in latest beta version 1.7.5
monit example:
```
check process dzga  with pidfile /var/run/dzga.pid
  start program = "systemctl start dzga" with timeout 60 seconds
  stop program = "systemctl stop dzga"
  if failed host 127.0.0.1 port 3030 with timeout 30 seconds for 5 cycles then restart
  if 5 restarts within 5 cycles then timeout
```

**Comment by DewGew** [comment]
> Don't forget to install: pip install pid

It's included in pip-requirements.txt

**Comment by vreesie18** [comment]
check

**Comment by DewGew** [comment]
Does it work? Can we close this?
