### ISSUE TITLE
Google Home: Temperature "Offline"

### ISSUE THREAD

**Issue by wewa00** [DewGew/Domoticz-Google-Assistant#150]
Hello DewGew,

when requesting the status of a domoticz temperature, Google Home does not display the current temperature (instead 32°C are displayed) and says the device is offline (it simply displays "Offline" in the center). It is working completely fine for a thermostat device where I combined a thermostat with a temperature sensor.

Please see the following logs. `Thermostat20` is displayed correctly within Google Home and `Temperture16` is showing the issues described above.

**Logs:**
```
2020-04-25 10:35:50 - INFO - Request {
  "inputs": [
    {
      "intent": "action.devices.QUERY",
      "payload": {
        "devices": [
          {
            "id": "Thermostat20"
          }
        ]
      }
    }
  ],
  "requestId": "8279954850886033917"
}
2020-04-25 10:35:51 - INFO - Response {
  "payload": {
    "devices": {
      "Thermostat20": {
        "descriptiveCapacityRemaining": "FULL",
        "online": true,
        "status": "SUCCESS",
        "thermostatMode": "heat",
        "thermostatTemperatureAmbient": 20.2,
        "thermostatTemperatureSetpoint": 21.5
      }
    }
  },
  "requestId": "8279954850886033917"
}
2020-04-25 10:35:56 - INFO - Request {
  "inputs": [
    {
      "intent": "action.devices.QUERY",
      "payload": {
        "devices": [
          {
            "id": "Temperture16"
          }
        ]
      }
    }
  ],
  "requestId": "6073356073797554444"
}
2020-04-25 10:35:57 - INFO - Response {
  "payload": {
    "devices": {
      "Temperture16": {
        "descriptiveCapacityRemaining": "FULL",
        "online": true,
        "status": "SUCCESS",
        "thermostatMode": "heat",
        "thermostatTemperatureAmbient": 48.9,
        "thermostatTemperatureSetpoint": 48.9
      }
    }
  },
  "requestId": "6073356073797554444"
}

```

**Desktop (please complete the following information):**
 - Domoticz version Stable 4.10717
 - Dzga version 1.7.3
 - Python Version 3.5.3 
 - Google Home App Version 2.21.1.10

BR wewa

**Comment by DewGew** [comment]
Have you tryed to restart dzga?

**Comment by wewa00** [comment]
Sure, but did not help.

**Comment by wewa00** [comment]
Do you have any idea about this? Is this issue caused by Google Home or is it Domoticz-Google-Assistant?

**Comment by DewGew** [comment]
See issue #126

**Comment by DewGew** [comment]
Set log to debug in config.You might find some more

**Comment by wewa00** [comment]
You are right, when asking Google Assistant, he tells me the correct temperature. So it is related to graphical UI of Google Home only. But maybe it should help if we try again to set the temperature range as suggested in #126?

**Comment by DewGew** [comment]
issue is not yet fix.. https://issuetracker.google.com/issues/145941828

**Comment by DewGew** [comment]
> You are right, when asking Google Assistant, he tells me the correct temperature. So it is related to graphical UI of Google Home only. But maybe it should help if we try again to set the temperature range as suggested in #126?

```
            'minThresholdCelsius': -20
            'maxThresholdCelsius': 40
```
Is already added in the script, so when its been added by google it we will notice..:)

**Comment by DewGew** [comment]
Same as #126

**Comment by DewGew** [comment]
Fixed ”offline” issue in latest version

**Comment by Catfriend1** [comment]
Mine is also displayed "offline", it's a temperature sensor device showing 20.4 °C in Domoticz and in DZGA Web UI. But Google Home says "offline" instead of 20.4 °C. Why does the value not get through?
