### ISSUE TITLE
change device type for temperature

### ISSUE THREAD

**Issue by wewa00** [DewGew/Domoticz-Google-Assistant#151]
**Describe the bug:**  
I tried to use following setting for a temperature sensor device. But within dzga the type stays `Temperature` and within Google Home App this device is displayed as a `Thermostat`.
```
<voicecontrol>
  devicetype = sensor
</voicecontrol>
```

**Expected behavior:** 
Device is displayed/reported as a sensor device.

**Desktop (please complete the following information):**
 - Domoticz version Stable 4.10717
 - Dzga version 1.3.1
 - Python Version 3.7.3

**Comment by DewGew** [comment]
Device type sensor is not yet supported.

From Wiki:
> Light Device types to choose from is:
> light, ac_unit, bathtub, coffemaker, 
> dishwasher, dryer, fan, heater, kettle, 
> media, microwave, outlet, oven, speaker, 
> switch, vacuum, washer, waterheater, 
> window, gate, garage.

**Comment by wewa00** [comment]
Which wiki do you mean? Could you please paste a link?

**Comment by DewGew** [comment]
https://github.com/DewGew/Domoticz-Google-Assistant/wiki/2.-Configuration#device-configuraton

**Comment by wewa00** [comment]
Hi, is support for this functionality planned in future?
