### ISSUE TITLE
Page not found!: 'NoneType' object has no attribute 'active_branch'

### ISSUE THREAD

**Issue by vreesie18** [DewGew/Domoticz-Google-Assistant#152]
After upgrading to Ubuntu 20.04 LTS is get after logging in into de dzga webinterface the following error on a empty white page: Page not found!: 'NoneType' object has no attribute 'active_branch'

Anyone how to fix this ? Thanks!

Regards

**Comment by DewGew** [comment]
Seems like git is broken. try reinstall. Backup config/config.yaml then remove dzga folder. Last run install script

**Comment by vreesie18** [comment]
Tried that, same problem. 

In the log file I found ERROR - Connection to Github refused! Check configuration.

**Comment by DewGew** [comment]
Set check update to false

**Comment by DewGew** [comment]
set logs to debug in config.yaml

**Comment by vreesie18** [comment]
Log debug enabled, see log below, there seems to be a problem with domoticz. Accessing domoticz from web browser url http://domoticz.lava:8181 is working. Could it not have somsting to so with the new domoticz version released the day before yesterday (2020.2)  ?! Before I user Ubuntu 18.04 LTS. 

regards


2020-04-28 23:43:11 - ERROR - Error in  getting devices and settings
2020-04-28 23:50:40 - INFO - Connecting to Domoticz on http://domoticz.lava:8181
2020-04-28 23:50:40 - ERROR - Connection to Domoticz refused with error: HTTPConnectionPool(host='domoticz.local', port=8181): Max retries exceeded with url: /json.htm?type=command&param=addlogmessage&message=Connected%20to%20Google%20Assistant%20with%20DZGA%20v1.7.4 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc35dfc39d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2020-04-28 23:50:40 - ERROR - Connection to Github refused! Check configuration.

**Comment by vreesie18** [comment]
sorry but change of .lava to .local is not done consequently in the pasted log above but in real all use the same .lava extension

**Comment by DewGew** [comment]
dzga works with latest domoticz. Is domoticz in your local network?

**Comment by DewGew** [comment]
run `sudo systemctl status dzga` whats the output?

**Comment by vreesie18** [comment]
root@lavaportal:~# sudo systemctl status dzga
● dzga.service - Domoticz-Google-Assistant Service
     Loaded: loaded (/etc/systemd/system/dzga.service; enabled; vendor preset: >
     Active: active (running) since Wed 2020-04-29 09:42:51 CEST; 3h 56min ago
   Main PID: 24564 (python3)
      Tasks: 1 (limit: 18951)
     Memory: 24.1M
     CGroup: /system.slice/dzga.service
             └─24564 /usr/bin/python3 /root/Domoticz-Google-Assistant/

Apr 29 09:42:51 lavaportal systemd[1]: Started Domoticz-Google-Assistant Servic>

**Comment by vreesie18** [comment]
dzga and domoticz are on the same server. The only change the last days was a upgrade to Ubuntu 20.04 LTS and version update of Domoticz. Till then everything was working okay. Dzga is still workig form the perspective of Google Assistant, commands are still being executed, only the web interface crasshes.

**Comment by DewGew** [comment]
change domoticz ip to localhost or 127.0.0.1

**Comment by vreesie18** [comment]
No gui, Ubuntu server, but tried with wget

 **wget http://localhost:3030/settings**


<html>

<head>
<title>Domoticz Google Assistant</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=0.86, maximum-scale=3.0, minimum-scale=0.86">

<style>
body{
	margin:0;
	color:#fff;
	background:#c8c8c8;
	font:600 16px/18px 'Open Sans',sans-serif;
}
*,:after,:before{box-sizing:border-box}
.clearfix:after,.clearfix:before{content:'';display:table}
.clearfix:after{clear:both;display:block}
a{color:inherit;text-decoration:none}

.login-wrap{
	width:100%;
	margin:auto;
	max-width:525px;
	min-height:670px;
	position:relative;
	background:url(https://d1e0w1wydjks4d.cloudfront.net/wp-content/uploads/2018/11/26060521/google-home-ecosystem.jpg) no-repeat center;
	box-shadow:0 12px 15px 0 rgba(0,0,0,.24),0 17px 50px 0 rgba(0,0,0,.19);
}
.login-html{
	width:100%;
	height:100%;
	position:absolute;
	padding:90px 70px 50px 70px;
	background:rgba(0,150,136,.7);
}
.login-html .sign-in-htm,
.login-html .sign-up-htm{
	top:0;
	left:0;
	right:0;
	bottom:0;
	position:absolute;
	transform:rotateY(180deg);
	backface-visibility:hidden;
	transition:all .4s linear;
}
.login-html .sign-in,
.login-html .sign-up,
.login-form .group .check{
	display:none;
}
.login-html .tab,
.login-form .group .label,
.login-form .group .button{
	text-transform:uppercase;
}
.login-html .tab{
	font-size:22px;
	margin-right:15px;
	padding-bottom:5px;
	margin:0 15px 10px 0;
	display:inline-block;
	border-bottom:2px solid transparent;
}
.login-html .sign-in:checked + .tab,
.login-html .sign-up:checked + .tab{
	color:#fff;
	border-color:#009688;
}
.login-form{
	min-height:345px;
	position:relative;
	perspective:1000px;
	transform-style:preserve-3d;
}
.login-form .group{
	margin-bottom:15px;
}
.login-form .group .label,
.login-form .group .input,
.login-form .group .button{
	width:100%;
	color:#fff;
	display:block;
}
.login-form .group .input,
.login-form .group .button{
	border:none;
	padding:15px 20px;
	border-radius:25px;
	background:rgba(255,255,255,.4);
}
.login-form .group input[data-type="password"]{
	text-security:circle;
	-webkit-text-security:circle;
}
.login-form .group .label{
	color:#aaa;
	font-size:12px;
}
.login-form .group .button{
	background:#009688;
}
.login-form .group label .icon{
	width:15px;
	height:15px;
	border-radius:2px;
	position:relative;
	display:inline-block;
	background:rgba(255,255,255,.1);
}
.login-form .group label .icon:before,
.login-form .group label .icon:after{
	content:'';
	width:10px;
	height:2px;
	background:#fff;
	position:absolute;
	transition:all .2s ease-in-out 0s;
}
.login-form .group label .icon:before{
	left:3px;
	width:5px;
	bottom:6px;
	transform:scale(0) rotate(0);
}
.login-form .group label .icon:after{
	top:6px;
	right:0;
	transform:scale(0) rotate(0);
}
.login-form .group .check:checked + label{
	color:#fff;
}
.login-form .group .check:checked + label .icon{
	background:#009688;
}
.login-form .group .check:checked + label .icon:before{
	transform:scale(1) rotate(45deg);
}
.login-form .group .check:checked + label .icon:after{
	transform:scale(1) rotate(-45deg);
}
.login-html .sign-in:checked + .tab + .sign-up + .tab + .login-form .sign-in-htm{
	transform:rotate(0);
}
.login-html .sign-up:checked + .tab + .login-form .sign-up-htm{
	transform:rotate(0);
}

.hr{
	height:2px;
	margin:60px 0 50px 0;
	background:rgba(255,255,255,.2);
}
.foot-lnk{
	text-align:center;
}
</style>

</head>
<div class="login-wrap">
	<div class="login-html">
        <h2 class="label">Domoticz Google Assistant</h2>
		<input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab">Sign In</label>
		<input id="tab-2" type="radio" name="tab" class="sign-up"><label for="tab-2" class="tab"></label>
		<div class="login-form">
        <form action='login' method='post' id='loginform'>
			<div class="sign-in-htm">
				<div class="group">
					<label for="username" class="label">Username</label>
					<input id="username" type="text" class="input">
				</div>
				<div class="group">
					<label for="userpass" class="label">Password</label>
					<input id="userpass" type="password" class="input" data-type="password">
				</div>
                        <input type="hidden" name="redirect">
                        <input type="hidden" name="client_id">
                        <input type="hidden" name="redirect_uri">
                        <input type="hidden" name="state">
                        <input type="hidden" name="username">
                        <input type="hidden" name="password">
				<div class="group">
					<input type="submit" class="button" value="Sign In" OnClick="formSubmit()">
				</div>
				<div class="hr"></div>
				<div class="foot-lnk">
					<a href="https://github.com/DewGew/Domoticz-Google-Assistant">Google Assistant for Domoticz on Github</a>
				</div>
			</div>
            </form>
		</div>
	</div>
</div>

	<script>
        function getUrlParameters () {
            // Get each parameter
            let query = window.location.search.substr(1);
            // Split each parameter into a key-value pair
            let keyValues = query.split('&');
            let parameterMap = new Map();
            for (let i in keyValues) {
                // Split into <key>=<value>
                let param = keyValues[i];
                let splitParam = param.split('=');
                parameterMap.set(splitParam[0], splitParam[1]);
            }
            return parameterMap;
        }

        function formSubmit () {
            // Get URL parameters
            let params = getUrlParameters();
            // Set each hidden input from a value obtained from the URL
            document.querySelector('[name="redirect"]').value = params.get('redirect');
            document.querySelector('[name="redirect_uri"]').value = params.get('redirect_uri');
            document.querySelector('[name="client_id"]').value = params.get('client_id');
            document.querySelector('[name="state"]').value = params.get('state');
            document.querySelector('[name="username"]').value = document.querySelector('input[id="username"]').value;
            document.querySelector('[name="password"]').value = document.querySelector('input[id="userpass"]').value;
            document.querySelector('#loginform').submit();
        }
    </script> 
	
</html>

**Comment by DewGew** [comment]
you can reach you dzga UI then.. from other computer

**Comment by vreesie18** [comment]
yes, I can reach it until the loginscherm, after entering username and password en clicking sign in, the error appears...Page not found!: 'NoneType' object has no attribute 'active_branch'

**Comment by DewGew** [comment]
Try set CheckForUpdates: False

**Comment by vreesie18** [comment]
Tried it, same error

**Comment by DewGew** [comment]
its something with git.. is there a .git folder in dzga folder?

**Comment by vreesie18** [comment]
![image](https://user-images.githubusercontent.com/37900374/80601793-8ef87e00-8a2e-11ea-8303-86f8e21318ef.png)

**Comment by vreesie18** [comment]
![image](https://user-images.githubusercontent.com/37900374/80601925-c0714980-8a2e-11ea-90ef-db965556cfdc.png)

**Comment by DewGew** [comment]
Maybe git module is missing, Try this:
1. goto terminal
2. cd into Domoticz-Google-Assistant folder
3. source env/bin/activate
4. pip install GitPython
5. restart dzga
6. open dzga UI

**Comment by vreesie18** [comment]
Yeeeeeaaahhhhh...works, .you are a genius, never give up !!!! 

Didn't understand what to do with ....source env/bin/activate

**Comment by DewGew** [comment]
dzga runs in a virtual enviroment, you need to activate that enviromen before installing the modules

**Comment by vreesie18** [comment]
but is it upgrade Ubuntu 20.04 related ?!

**Comment by DewGew** [comment]
It might,, Ubuntu 20.04 use python 3.8..

**Comment by vreesie18** [comment]
Many thanks!!

**Comment by vreesie18** [comment]
Woke up this morning and ofcourse do a check as always and logged in into the web interface.....**Page not found!: 'dzversion'.** What happended overight ??!

**Comment by vreesie18** [comment]
Hint: if I stop the dzga and start the service form the command line like below, it works..

root@mycomputer:~# **/usr/bin/python3 /root/Domoticz-Google-Assistant/**
Loading configuration...
Connecting to Domoticz on http://domoticz.lava:8181
========
Started DZGA v1.7.4 server at port 3030

   Visit http://localhost:3030/settings to access the user interface

=========
Visit the Actions on Google console at http://console.actions.google.com
Under Develop section, replace the fulfillment URL in Actions with:
   https://[your public url]/smarthome

In Account linking, set the Authorization URL to:
   https://[your public url]/oauth

Then set the Token URL to:
   https://[your public url]/token

Finally press 'SAVE' and then 'TEST' button
=======
(Press CTRL+C to stop server)
192.168.1.89 - - [30/Apr/2020 10:26:00] "GET /settings HTTP/1.1" 307 -
192.168.1.89 - - [30/Apr/2020 10:26:00] "GET /login?redirect_uri=settings HTTP/1.1" 200 -

**Comment by DewGew** [comment]
You are running as root for some reason I recommend running as a user.. looks like you lost connection to domoticz
