### ISSUE TITLE
git pull -> update not correct updated.

### ISSUE THREAD

**Issue by SargonofAssyria** [DewGew/Domoticz-Google-Assistant#154]
I found out that with the latest beta update that the python pidfile was not installed.
I did only 'git pull' to update the beta to the latest.
Only found out later that the python pidfile was needed and that dzga did not start.

**Comment by DewGew** [comment]
I you use the update button in UI or run install script the pip requirements is installed also. if you only do a git pull the missing modules will not install.  Additionally you can run `pip install -r ~/Domoticz-Google-Assistant/requirements/pip-requirements.txt` after git pull.

**Comment by SargonofAssyria** [comment]
Tnx, I will only do it in the GUI in the future.
