### ISSUE TITLE
after install - page not found

### ISSUE THREAD

**Issue by Geronimooo** [DewGew/Domoticz-Google-Assistant#155]
Hi.

Following the install instructions it says you can set your settings after install by logging in. But doing that gives an empty page with "Page not found!: 'dzversion'"
Only after I manually entered my domoticz url and user/pass did I manage to enter the settings page.

So my suggestion is to make the settings page work despite an invalid domoticz url or to update the install instructions.

Using the beta branch.

**Comment by DewGew** [comment]
Thanks for pointing this out 👍
