### ISSUE TITLE
Docker Python error [Asustor NAS]

### ISSUE THREAD

**Issue by rezzalex** [DewGew/Domoticz-Google-Assistant#158]
**Describe the bug:**  

Python error when trying to run the latest Docker image.
Exactly the same bug as described here : https://github.com/DewGew/Domoticz-Google-Assistant/issues/135

**Expected behavior:**  
No errors in logs and a web response when trying to reach http://locahost/3030/settings/

**Logs:**

```
Collecting pyasn1<0.5.0,>=0.4.6,
  Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB),
Could not build wheels for future, since package 'wheel' is not installed.,
Could not build wheels for PyYAML, since package 'wheel' is not installed.,
Could not build wheels for setuptools, since package 'wheel' is not installed.,
Installing collected packages: certifi, chardet, future, idna, pid, PyYAML, urllib3, requests, smmap, gitdb, GitPython, pyasn1, pyasn1-modules, cachetools, six, rsa, google-auth,
    Running setup.py install for future: started,
    Running setup.py install for future: finished with status 'done',
    Running setup.py install for PyYAML: started,
    Running setup.py install for PyYAML: finished with status 'done',
Successfully installed GitPython-3.1.2 PyYAML-5.3.1 cachetools-4.1.0 certifi-2020.4.5.1 chardet-3.0.4 future-0.18.2 gitdb-4.0.5 google-auth-1.14.2 idna-2.9 pid-3.0.3 pyasn1-0.4.8 pyasn1-modules-0.2.8 requests-2.23.0 rsa-4.0 six-1.14.0 smmap-3.0.4 urllib3-1.25.9,
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz,
(1/24) Purging build-base (0.5-r1),
(2/24) Purging file (5.37-r1),
(3/24) Purging g++ (9.2.0-r4),
(4/24) Purging gcc (9.2.0-r4),
(5/24) Purging binutils (2.33.1-r0),
(6/24) Purging libatomic (9.2.0-r4),
(7/24) Purging libgomp (9.2.0-r4),
(8/24) Purging libstdc++ (9.2.0-r4),
(9/24) Purging make (4.2.1-r2),
(10/24) Purging libc-dev (0.7.2-r0),
(11/24) Purging musl-dev (1.1.24-r2),
(12/24) Purging fortify-headers (1.1-r0),
(13/24) Purging git (2.24.3-r0),
(14/24) Purging libc6-compat (1.1.24-r2),
(15/24) Purging linux-headers (4.19.36-r0),
(16/24) Purging libgcc (9.2.0-r4),
(17/24) Purging libmagic (5.37-r1),
(18/24) Purging isl (0.18-r0),
(19/24) Purging mpc1 (1.1.0-r1),
(20/24) Purging mpfr4 (4.0.2-r1),
(21/24) Purging gmp (6.1.2-r1),
(22/24) Purging libcurl (7.67.0-r0),
(23/24) Purging nghttp2-libs (1.40.0-r0),
(24/24) Purging pcre2 (10.34-r1),
Executing busybox-1.31.1-r9.trigger,
OK: 14 MiB in 38 packages,
Installing APK requirements...,
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz,
OK: 14 MiB in 38 packages,
Loading configuration...,
No config.yaml found...,
Loading default configuration...,
Create config.yaml...,
Traceback (most recent call last):,
  File "/__main__.py", line 4, in <module>,
    from server import *,
  File "/server.py", line 7, in <module>,
    from smarthome import *,
  File "/smarthome.py", line 15, in <module>,
    import trait,
  File "/trait.py", line 13, in <module>,
    from helpers import SmartHomeError, configuration, logger, tempConvert,
  File "/helpers.py", line 121, in <module>,
    configuration['ClientID'] = 'sampleClientId',
TypeError: 'str' object does not support item assignment,
/requirements.installed file exists-- skipping requirements installs.,
Traceback (most recent call last):,
  File "/__main__.py", line 4, in <module>,
    from server import *,
  File "/server.py", line 7, in <module>,
    from smarthome import *,
  File "/smarthome.py", line 15, in <module>,
    import trait,
  File "/trait.py", line 13, in <module>,
    from helpers import SmartHomeError, configuration, logger, tempConvert,
  File "/helpers.py", line 121, in <module>,
    configuration['ClientID'] = 'sampleClientId',
TypeError: 'str' object does not support item assignment,
Loading configuration...,
/requirements.installed file exists-- skipping requirements installs.,
Loading configuration...,
Traceback (most recent call last):,
  File "/__main__.py", line 4, in <module>,
    from server import *,
  File "/server.py", line 7, in <module>,
    from smarthome import *,
  File "/smarthome.py", line 15, in <module>,
    import trait,
  File "/trait.py", line 13, in <module>,
    from helpers import SmartHomeError, configuration, logger, tempConvert,
  File "/helpers.py", line 121, in <module>,
    configuration['ClientID'] = 'sampleClientId',
TypeError: 'str' object does not support item assignment,
/requirements.installed file exists-- skipping requirements installs.,
Loading configuration...,
Traceback (most recent call last):,
  File "/__main__.py", line 4, in <module>,
    from server import *,
  File "/server.py", line 7, in <module>,
    from smarthome import *,
  File "/smarthome.py", line 15, in <module>,
    import trait,
  File "/trait.py", line 13, in <module>,
    from helpers import SmartHomeError, configuration, logger, tempConvert,
  File "/helpers.py", line 121, in <module>,
    configuration['ClientID'] = 'sampleClientId',
TypeError: 'str' object does not support item assignment,
/requirements.installed file exists-- skipping requirements installs.,```-->

**Desktop (please complete the following information):**
 - Domoticz version <!--beta 2020 build 12017-->
 - Dzga version <!-- dewgew/domoticz-google-assistant:latest -->
 - Python Version <on my Asustor NAS, i have Python 2.7 AND 3.5 but is it relevant for a docker image ?>
- Docker Version <!--Docker-ce 19.03.8.r4 official Asustor App-->


**Additional context, screenshot:**  
<!-- I have also Portainer installed but I didnt' use it in our case. I have followed the docker compose instructions in the Wiki-->

**Comment by DewGew** [comment]
Is it a arm hardware in your nas?

**Comment by rezzalex** [comment]
Hello @DewGew, no I have a Intel® Celeron™ CPU @ 1.60GHz,, so no arm hardware. correct ?

**Comment by rezzalex** [comment]
/volume1/.@root # docker-compose version
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
root@NASADAM:/volume1/.@root #

**Comment by DewGew** [comment]
Did you git clone before you run docker compose?

**Comment by rezzalex** [comment]
I did all this.

**Comment by DewGew** [comment]
> I did all this.

Like this?
`- /volume1/${USER}/Domoticz-Google-Assistant/config:/config`

**Comment by rezzalex** [comment]
No. You are right. Not exactly like this.
I connect to my NAS in SSH as root and git clone here :  /Volume1/Docker/ 
But I did changed the yaml file accordingly. Then  I have executed docker-compose directly from here. With not the whole path.

**Comment by rezzalex** [comment]
This time I did exactly the same commands... With the same result... ;-)

**Comment by DewGew** [comment]
> This time I did exactly the same commands... With the same result... ;-)

According to your log. It cant find configuration. Docker cant find volume /config. Your Path seems not to be correct.

**Comment by rezzalex** [comment]
Hello @DewGew ,
I gave all possible rights to the /config rep, and even after 1st container launch, I stopped it and give all possible rights to the /config/config.yaml file.
it seems the bind is correct
![image](https://user-images.githubusercontent.com/35136439/81548481-aa904c80-937d-11ea-962d-47f25d7ed18e.png)

**Comment by rezzalex** [comment]
After executing this command : git clone https://github.com/DewGew/Domoticz-Google-Assistant -b docker --single-branch
the /config Folder only contain a README.md file and that's all, Is it normal ?

**Comment by DewGew** [comment]
default_config is moved to another folder and i created during first run

**Comment by rezzalex** [comment]
Ok. Sony any idea about the cause of my issue ?
I am using exactly the same mechanism in another docker container to bind local volume. It is for domoticz. the container normally read and write inside the binded volume...

**Comment by DewGew** [comment]
json file is read only. Is there anything written in the created config.yaml at first run?

**Comment by rezzalex** [comment]
Nothing seems to be written in the file. As already said, I can't even open the file through ssh...

**Comment by DewGew** [comment]
sudo nano ?

**Comment by rezzalex** [comment]
Not nano. vi as root

**Comment by DewGew** [comment]
Seems like permissons issue. Script need a write permission to volume. Is dzga run as root or user? I recomend running as a user.

**Comment by rezzalex** [comment]
As I have executed all the commands connected in SHH as Root, I supposed the container run as ROOT... correct ? and as already said, I have tried set all possibles permissions to the /config folder and yaml file, with no sucess

Worst case, could I compose the manually the Yaml file and put it inside the /config folder, so that the container will skipp the file creation and correctly (I Hope) read the Yalm file ?

**Comment by DewGew** [comment]
Try that. I dont use docker my self. I only tested on ubuntu. NAS like yours and synology has a diffrent way of handling this.

**Comment by rezzalex** [comment]
I will try, But are you sure it is NAS specific ? : 
![image](https://user-images.githubusercontent.com/35136439/81670761-5ef6a500-9448-11ea-80be-71861bc528bf.png)

**Comment by DewGew** [comment]
Issue with ubuntu is resolved

**Comment by rezzalex** [comment]
I tried to create/edit and give all read and write permissions to the confi yaml fie, but it can t be read by the container... :-(

is this error message in logs could be related ? : 

**Logs:**


Could not build wheels for future, since package 'wheel' is not installed.
Could not build wheels for PyYAML, since package 'wheel' is not installed.
Could not build wheels for setuptools, since package 'wheel' is not installed.

**Comment by DewGew** [comment]
I cant help you with docker..but you can install without docker. Use same as setup as synology [here](https://github.com/DewGew/Domoticz-Google-Assistant/wiki/1.-Installation#installation-synology)

**Comment by rezzalex** [comment]
The Synology start-up script di not work for my Asustor NAS.

is it possible that the container try to use a Wrong version of Python ?

**Comment by rezzalex** [comment]
For docker, I have tried to change the PUID and GID to match the same user I have used to create the 1sr docker commands.... No success..

**Comment by DewGew** [comment]
dzga requires python3.5 or above

**Comment by rezzalex** [comment]
> I cant help you with docker..but you can install without docker. Use same as setup as synology [here](https://github.com/DewGew/Domoticz-Google-Assistant/wiki/1.-Installation#installation-synology)

Thanks a lot for your help. Who could help me then on Docker ? Who build the Docker version of your app ?

**Comment by rezzalex** [comment]
> dzga requires python3.5 or above

Is the python version on the Host can have an impact on the python inside the container ? Because I have several different versions on my host and it seems the defaut one is 2.7...

**Comment by rezzalex** [comment]
is it correct that ALL the configuration on Google Console side is supposed to be done AFTER the first launch of the local web GUI ?

**Comment by DewGew** [comment]
no it can be done before also

**Comment by rezzalex** [comment]
Is my error could come from my internet connection : I am temporary connected with a 4G router, and so, can't be reached from outside my Lan, I know it will be a problem later-on, but is the creation of the yaml config file (or the reading of the [minimal one :](https://github.com/DewGew/Domoticz-Google-Assistant/wiki/2.-Configuration) ) required to be reachable from external network ?

**Comment by DewGew** [comment]
No, the UI should work locally. its something with dockerfile or composer. I've only tested in ubuntu 18.04

**Comment by rezzalex** [comment]
thank you, so what could be the best idea to work on : ? file system  differences between Ubuntu and My ASUSTOR linux (ADM) ? interactions between the host and the container (As my host is very different from an Ubuntu ? Docker specificity on my Asustor ? User and rights management ?

**Comment by rezzalex** [comment]
> > This time I did exactly the same commands... With the same result... ;-)
> 
> According to your log. It cant find configuration. Docker cant find volume /config. Your Path seems not to be correct.

Maybe this will sound silly but... Are you sure the /systemd folder and it's " default config file" are "taken" while building the container ?

I ask because with my 1st test , the yaml conf file had been created (so no write permission issue here) but the content was something like "problem opening this file".
What do you think ?

Thanks a lot

**Comment by DewGew** [comment]
The python program is working correct. It is the same program if you are using docker or not.

**Comment by rezzalex** [comment]
> If there is none config.yaml in config folder the script is copying and rename `systemd/default_config` to `config/config.yaml`

I saw that in your python code and I am sure that the python program is correct.
I suspect the docker file to forget the `systemd/default_config`
I saw the line of code that take part of the requirement folder. But I didn't see the line of code for the `systemd/default_config` ...

**Comment by DewGew** [comment]
I added a default config.yaml to config folder in docker branch. There is an issue like you told with creating the config file with docker.
Try agin.
1. Remove dzga container and images form docker
2. Remove Domoticz-Google-Assistant folder`sudo rm -r Domoticz-Google-Assistant`
3. then `git clone https://github.com/DewGew/Domoticz-Google-Assistant -b docker --single-branch`

**Comment by rezzalex** [comment]
IT WORKED ! Thanks
![image](https://user-images.githubusercontent.com/35136439/81919550-461cf980-95d8-11ea-839d-9ea582f59c3c.png)

**Comment by DewGew** [comment]
there is an other issue when you login :(

**Comment by rezzalex** [comment]
admin, admin :  ??
![image](https://user-images.githubusercontent.com/35136439/81920064-f1c64980-95d8-11ea-935d-688fe3d16618.png)

**Comment by DewGew** [comment]
yepp trying to fix this..

**Comment by DewGew** [comment]
try again update this line your docker-composer file:
`image: dewgew/domoticz-google-assistant`
to
`image: dewgew/domoticz-google-assistant:beta`

**Comment by rezzalex** [comment]
WORK IN BETA ! : 
![image](https://user-images.githubusercontent.com/35136439/81924893-04904c80-95e0-11ea-87c4-4acb15e96898.png)

**Comment by rezzalex** [comment]
Sorry to have pushed you and thank for your help. I will try to manage the conf in the next days...

**Comment by rezzalex** [comment]
When can I leave the beta and swtich to the Master ?

**Comment by DewGew** [comment]
I have updated master. Just change from :beta to :latest in composer file
