### ISSUE TITLE
More control over response from Google

### ISSUE THREAD

**Issue by SargonofAssyria** [DewGew/Domoticz-Google-Assistant#159]
I love Google Home/Mini and DZGA.
I love the way Google gives a response to me asking to turn all lights of in a room where Google Home/Mini is located with just a 'plonk'
I am fed up with the response of Google Home/Mini when it is not in the same room, by mentioning that Google turns of X lights.
I would love some sort of setting that Google minimized the response to such a request by a 'plink' ( other pitch or tone height) or just by nothing and only respond if it could not comply with my wishes.

I hope that such a thing could be a setting in DZGA.

**Comment by DewGew** [comment]
Those responses is handle by Google. Some error responses can be handled by dzga.

**Comment by SargonofAssyria** [comment]
Did you raise an issue at Google, or do you know where I could?

**Comment by DewGew** [comment]
Try here; https://issuetracker.google.com/issues?q=componentid:655104%20status:open
or 
here: https://www.reddit.com/r/GoogleAssistantDev/
