### ISSUE TITLE
Cannot save Configuration from DZGA GUI

### ISSUE THREAD

**Issue by SargonofAssyria** [DewGew/Domoticz-Google-Assistant#160]
**Describe the bug:**  
In the GUI I change the loglevel from Debug to Info and then hit 'Save' button.
I get this response back.
`This page isn’t working192.168.x.xxx didn’t send any data.
ERR_EMPTY_RESPONSE`

**Expected behavior:**  
Just execute the save action.

**Logs:**
Nothing but:
`2020-05-12 09:17:59 - DEBUG - Starting new HTTPS connection (1): raw.githubusercontent.com:443
2020-05-12 09:18:00 - DEBUG - https://raw.githubusercontent.com:443 "GET /DewGew/Domoticz-Google-Assistant/beta/const.py HTTP/1.1" 200 13005
`
**Desktop (please complete the following information):**
 - Domoticz version 2020.2
 - Dzga version 1.7.7
 - Python Version 3.7.3

**Comment by DewGew** [comment]
Same after a restart?

**Comment by SargonofAssyria** [comment]
Yes, and I looked in the ssh console too, there is no change in the file content of config.yaml and also no change in the access or modify date of that file.

**Comment by DewGew** [comment]
Have you updated domoticz or something else before?

**Comment by DewGew** [comment]
@SargonofAssyria  Are you using nginx reverse proxy? Check if nginx is running correct.

**Comment by SargonofAssyria** [comment]
I have updated Domoticz some days ago to version 2020.2
I am using my own reverse proxy on my Synology NAS.
But in the GUI I login directly in the local network on port 3030.
DGZA works also normally, but I cannot save settings in the GUI.

**Comment by DewGew** [comment]
Strange i cant reproduce this error. Ive only seen this error on nginx server not running correct Or when certificates are not valid

**Comment by DewGew** [comment]
reinstall dzga. Just make a copy of config/config.yaml:
```
cd /home/${USER/
sudo cp Domoticz-Google-Assistant/config/config.yaml config.yaml
```
then:

```
sudo systemctl stop dzga
sudo systemctl disable dzga
sudo rm /etc/systemd/system/dzga.service
sudo rm -r Domoticz-Google-Assistant

```
Run the installer:
`bash <(curl -s https://raw.githubusercontent.com/DewGew/dzga-installer/master/install.sh)`

add your copy of config.yaml to config folder and restart dzga:
```
sudo cp config.yaml Domoticz-Google-Assistant/config/config.yaml
sudo systemctl restart dzga
```

**Comment by SargonofAssyria** [comment]
I did it ALL (incl. cp of smart-home-key.json) but unfortunately it did not solve the problem.
Service is running as pi, these are the file rights.
`-rw-r--r-- 1 pi pi 3840 May 13 09:50 config.yaml
-rw-r--r-- 1 pi pi 3136 Mar 23 19:17 config.yaml.org
-rw-r--r-- 1 pi pi   99 May 13 09:49 README.md
-rw-r--r-- 1 pi pi 2299 Jan 28 12:24 smart-home-key.json
`

**Comment by DewGew** [comment]
Try with another browser

**Comment by SargonofAssyria** [comment]
I tried with latest MS Edge and 'old' MS IE and Firefox.
But ALL gave the same kind error. The result is not saved.

**Comment by DewGew** [comment]
are you using dzga Master or Beta

**Comment by SargonofAssyria** [comment]
DZGA Version: 1.7.7 beta
Domoticz Version: 2020.2

**Comment by DewGew** [comment]
It has to be somting at you setup. wrong port or something...?

**Comment by SargonofAssyria** [comment]
No, using 3030. I guess that file setting of 0644 for pi:pi is OK?

**Comment by SargonofAssyria** [comment]
Everytime I hit the save button this is in the logging of dzga. So 3 times the same.
`2020-05-13 13:56:39 - DEBUG - Starting new HTTPS connection (1): raw.githubusercontent.com:443
2020-05-13 13:56:40 - DEBUG - https://raw.githubusercontent.com:443 "GET /DewGew/Domoticz-Google-Assistant/beta/const.py HTTP/1.1" 200 13050
2020-05-13 13:56:40 - DEBUG - Starting new HTTPS connection (1): raw.githubusercontent.com:443
2020-05-13 13:56:40 - DEBUG - https://raw.githubusercontent.com:443 "GET /DewGew/Domoticz-Google-Assistant/beta/const.py HTTP/1.1" 200 13050
2020-05-13 13:56:40 - DEBUG - Starting new HTTPS connection (1): raw.githubusercontent.com:443
2020-05-13 13:56:40 - DEBUG - https://raw.githubusercontent.com:443 "GET /DewGew/Domoticz-Google-Assistant/beta/const.py HTTP/1.1" 200 13050

`

**Comment by DewGew** [comment]
Thats is for checking for dzga updates, that suppost to be like that.

**Comment by DewGew** [comment]
There is nothing wrong with dzga.. I've restarted and removed my setup. Its working fine here

**Comment by SargonofAssyria** [comment]
It gets even funnier. When I click the button "backup Config" then the copy of config.yaml with extention .bak is created. When in the GUI I change something in the config and before I click Save I delete the config.yaml file on the RaspPi then I get the same error.
Could I add some logging in saveFile in helpers.py or smarthome.py where the file gets saved?
If so what?

**Comment by SargonofAssyria** [comment]
I got a little bit further, because a tool I use gives back "504 Gateway Timeout Error"
For me it is not that much of a problem, because I can change settings via a SSH session.
I would love to have some lines for logging/debugging in the functions.

**Comment by DewGew** [comment]
I use `def readFile` and `def saveFile` functions in helpers.py to read and save config.yaml in UI.
Save button send a post request to smarthome.py https://github.com/DewGew/Domoticz-Google-Assistant/blob/fa2fd03e1ab142ad29221cb21967d774b937da0c/smarthome.py#L708

**Comment by SargonofAssyria** [comment]
I do not have enough knowledge of Python.
I tried to get some lines in like.
logger.info(textToSave) and logger.info(codeToSave) to get some info if there is something 'special' in it, but dzga won't start anymore.
The message 'Config saved' does not get into the logfile.
I do not understand the 'code = file.read()' in def saveFile.

**Comment by DewGew** [comment]
If you updated dzga correct then its not dzgs problem. Try start over with a new config.yaml maybe something missing or wrong spelling.

**Comment by SargonofAssyria** [comment]
Did all that, but still the same.
Like I wrote, I can change setting in the config.yaml itself.
Until I am not the only one, i will close the issue.
Tnx, for your support.
