### ISSUE TITLE
Different PIN/security code for each device

### ISSUE THREAD

**Issue by g1r1** [DewGew/Domoticz-Google-Assistant#161]
Is there a possibility of introducing different pin codes using voicecontrol tags? 

Currently, we can only configure only one security / pin code, which is used by all devices using Domoticz. Could this be extended with a PIN code for each device maybe like this:

<voicecontrol>
pin = 1234
</voicecontrol>

**Comment by DewGew** [comment]
It can be done but, there might be a problem with protected switch is on in domoticz and you set another pin in dzga, you need 2 pincodes.

**Comment by g1r1** [comment]
That's fine I guess. We can call that "high security" feature :-)

**Comment by DewGew** [comment]
I doubt Google Assistant can to handle 2 pins.

**Comment by g1r1** [comment]
What if the pin voicecontrol tag is only used if the switch is not in protected mode. Is that possible?

**Comment by DewGew** [comment]
That can work...
