### ISSUE TITLE
Domoticz connection problem

### ISSUE THREAD

**Issue by rezzalex** [DewGew/Domoticz-Google-Assistant#169]
**Describe the bug:**  

**Expected behavior:**  

**Logs:**

```
Starting new HTTP connection (1): 192.168.2.111:8080,
http://192.168.2.111:8080 "GET /json.htm?type=devices&plan=0&filter=all&used=true HTTP/1.1" 503 105,
Starting new HTTP connection (1): 192.168.2.111:8080,
http://192.168.2.111:8080 "GET /json.htm?type=settings HTTP/1.1" 401 91,
Starting new HTTP connection (1): 192.168.2.111:8080,
http://192.168.2.111:8080 "GET /json.htm?type=command&param=getversion HTTP/1.1" 503 105,
{,
  "dzversion": "Unavailable",,
  "dzVents": "1.0.0",
},
```

**Desktop (please complete the following information):**
 - Domoticz version 
 - Dzga version 
 - Python Version 

**Additional context, screenshot:**

**Comment by rezzalex** [comment]
Working Json request : 
![image](https://user-images.githubusercontent.com/35136439/81944253-c6edec80-95fc-11ea-88de-9967ec379176.png)

Working PING domoticz from DZGA container : 
![image](https://user-images.githubusercontent.com/35136439/81944361-f0a71380-95fc-11ea-8d46-fa33367b9e4d.png)

**Comment by rhuijben** [comment]
I also have a failed upgrade using the upgrade button in the UI. Service now fails to start.

**Comment by rezzalex** [comment]
Work !

**Comment by DewGew** [comment]
What was the issue?

**Comment by rezzalex** [comment]
Needed to have the "http " in the ip address and the login and password, even if I don't needed normally in my local network. But here it is communication from container to container...
