### ISSUE TITLE
PID file disapears.

### ISSUE THREAD

**Issue by SargonofAssyria** [DewGew/Domoticz-Google-Assistant#170]
**Describe the bug:**  
At start of dzga the PID file is created in /run/users/1000 but disappears after some time.

**Expected behavior:**  
Not to disappear, because I want to use monit to monitor dzga

**Logs:**
Nothing in log that point to the loss of the file.

```
2020-05-15 08:51:34 - DEBUG - <pid.posix.PidFile object at 0xb5b56920> entering setup
2020-05-15 08:51:34 - DEBUG - <pid.posix.PidFile object at 0xb5b56920> create pidfile: /run/user/1000/dzga.pid
2020-05-15 08:51:34 - DEBUG - <pid.posix.PidFile object at 0xb5b56920> check pidfile: /run/user/1000/dzga.pid
2020-05-15 08:51:34 - INFO - ========
2020-05-15 08:51:34 - INFO - Started DZGA v1.7.8 server at port 3030

```

**Desktop (please complete the following information):**
 - Domoticz version 2020.2
 - Dzga version 1.7.8
 - Python Version 3.7.3

**Comment by SargonofAssyria** [comment]
B.t.w. in the doc. about monit systemctl should be /bin/systemctl
Otherwise the program can not be found.

**Comment by DewGew** [comment]
Updated wiki

**Comment by DewGew** [comment]
pid file should be in  var/run/dzga.pid

**Comment by DewGew** [comment]
After how long time?

**Comment by SargonofAssyria** [comment]
That's really hard to tell, but I started 08:51 and now it is gone. I started monit 09:10
And until now monit is not complaining. Monit thinks everything is OK. My monit file.
`check process dzga  with pidfile /run/user/1000/dzga.pid
  start program = "/bin/systemctl start dzga" with timeout 60 seconds
  stop program = "/bin/systemctl stop dzga"
  if failed host 127.0.0.1 port 3030 with timeout 30 seconds for 5 cycles then restart
  if 5 restarts within 5 cycles then timeout
`

**Comment by DewGew** [comment]
If pid is missing should monit restart dzga?

**Comment by SargonofAssyria** [comment]
I don't know monit exactly, but it might be that monit reads the pid file and then just periodically check if a process with that pid number still runs. Would be logical. If that is so, then monit is still right, because the original process with that pid number still runs.
Apparently monit does not care is the PID file is still there. I don't care either but just want to mention what I saw. The meaning of the PID file is it stays there.
I just want you to know. If I can test anything else, just let me know.

**Comment by vreesie18** [comment]
I am also missing the pid file for dzga

**Comment by vreesie18** [comment]
Found it at /run/user/0

No longer at /run

Location changed ?

**Comment by DewGew** [comment]
It dependent what platform you run in and what user you run it with.

**Comment by DewGew** [comment]
Monit config in wiki is just an example

**Comment by DewGew** [comment]
@SargonofAssyria @vreesie18 Try latetest beta. I hardcoded the path to pidfile to `/var/run/dzga.pid`

**Comment by vreesie18** [comment]
Tested it and it seems to be working, even after restarting (Ubuntu 20.04 lts) a couple of times the pid fill appears on the same location /var/run.

**Comment by SargonofAssyria** [comment]
Via the GUI I installed the latest.
It failed to start afterwards and also manually.
Have to investigated tomorrow.
In the partial logging I saw the path /var/run for the PID, but then it stopped.

**Comment by SargonofAssyria** [comment]
Sorry it took a little bit longer.
Today the GUI update went fine to version DZGA Version: 1.7.11 beta and Domoticz Version: 2020.2 (build 12077)
In the logfile I saw that the PID file is created in /run/usr/1000 and it is.
I change the location to /var/run in the config.yaml and dzga would not start.
Changed to to /run, would not start either.
Debugging is on, but no clue why dzga would not start.
The default from the default_config config/dzga.pid works.
No have to see if it stays.

**Comment by DewGew** [comment]
> Sorry it took a little bit longer.
> Today the GUI update went fine to version DZGA Version: 1.7.11 beta and Domoticz Version: 2020.2 (build 12077)
> In the logfile I saw that the PID file is created in /run/usr/1000 and it is.
> I change the location to /var/run in the config.yaml and dzga would not start.
> Changed to to /run, would not start either.
> Debugging is on, but no clue why dzga would not start.
> The default from the default_config config/dzga.pid works.
> Now have to see if the PID file stays.

Now it you can set any path you want.

**Comment by SargonofAssyria** [comment]
Happy to confirm that after almost a day the PID file in the config directory is still there and monit is fine with that.
I could not find a reason why the PID file disappears in /run/user/1000 and that /var/run and /run are not accepted, probably authorization issue.

**Comment by DewGew** [comment]
Can be user permissions for /run folder
