### ISSUE TITLE
Local fulfillment

### ISSUE THREAD

**Issue by asquelt** [DewGew/Domoticz-Google-Assistant#172]
is Local fulfillment considered in future versions?

i do have some sensitive physical access control devices, that i'm not willing to expose to the internet. i would still be happy to use voice assistant for my domoticz instance. it turns out that recently google allows to run discovery (SYNC) through cloud, but then actual commands through LAN (IDENTIFY and EXECUTE). that would require splitting setup into two parts, where one is connected to the internet and advertises devices and the second one is responsible for command and control. that two should be designed to be run disconnected (possibly exchanging device ids through a config file or unidirectional LAN => cloud API).

sdk docu: https://developers.google.com/assistant/smarthome/concepts/local
how to: https://developers.google.com/assistant/smarthome/develop/local

**Comment by rhuijben** [comment]
Would certainly be a nice feature
