### ISSUE TITLE
Cannotget connected with Google Home / Actions

### ISSUE THREAD

**Issue by SargonofAssyria** [DewGew/Domoticz-Google-Assistant#175]
Running dzga 1.7.12 beta.
For some reason I lost connection with Google.
I tried to press the 'Test' button again, it worked before, but that did not solve the problem.
I did ALL the steps from 'menu3' in the dzga GUI in ALL variations none of those worked.
I tried a sync request and got
`Page not found!: 404 Client Error: Not Found for url: https://homegraph.googleapis.com/v1/devices:requestSync`
In the dzga logging I got:
`2020-05-31 17:29:47 - DEBUG - Starting new HTTPS connection (1): accounts.google.com:443
2020-05-31 17:29:47 - DEBUG - https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None
2020-05-31 17:29:47 - DEBUG - Starting new HTTPS connection (1): homegraph.googleapis.com:443
2020-05-31 17:29:48 - DEBUG - https://homegraph.googleapis.com:443 "POST /v1/devices:requestSync HTTP/1.1" 404 None`

End result, I got nothing. I am lost. I did this several time before and it always worked. Probably I am overlooking something.
Btw  `Click 'OAuth client ID'
Choose 'other'`
The 'other' does not exist anymore.
Who points me to the right direction?

**Comment by SargonofAssyria** [comment]
Oeps, found it  ----> sampleClientId etc..... forgot to change that....

**Comment by vreesie18** [comment]
Having same problem, can you please explain what to do ? Thanks!!
