### ISSUE TITLE
Error: action.devices.SYNC

### ISSUE THREAD

**Issue by webpatrick** [DewGew/Domoticz-Google-Assistant#180]
**Describe the bug:**  
I deleted my entry in the Google Home App. Now I want to reconnect, but it won't work

**Expected behavior:**  
it works! But it doesn't

**Logs:**
```
2020-06-25 17:26:42 - DEBUG - http://192.168.2.101:5084 "GET /json.htm?type=command¶m=getversion HTTP/1.1" 200 183
2020-06-25 17:26:42 - ERROR - 'dzvents_version'
2020-06-25 17:26:42 - ERROR - Error handling message {'inputs': [{'intent': 'action.devices.SYNC'}], 'requestId': '14097417850400601058'}: {'errorCode': 'unknownError'}
2020-06-25 17:26:49 - DEBUG - Starting new HTTPS connection (1): raw.githubusercontent.com:443
```

**Desktop (please complete the following information):**
 - Domoticz version Version 3.8153 on Synology DS213, cannot update unfortunately
 - Dzga version 1.7.12 master
 - Python Version ? virtual version
**Smartphone (please complete the following information):**
 - Device: Android v10 Phone (Huawei Mate 20 Pro)

**Additional context, screenshot:**  
result of getversion
```
{
   "DomoticzUpdateURL" : "",
   "HaveUpdate" : false,
   "Revision" : 0,
   "SystemName" : "linux",
   "build_time" : "2017-07-30 12:19:41",
   "hash" : "494fff7-modified",
   "status" : "OK",
   "title" : "GetVersion",
   "version" : "3.8153"
}
```

Message in Home App (translated from dutch): cannot update settings: check your connection

**Comment by DewGew** [comment]
You have an older version of domoticz, in lateter versions you can get dzvents_version. 
If you dont want to upgrade domoticz you can comment out this line https://github.com/DewGew/Domoticz-Google-Assistant/blob/9e884ed619c41646feef46e782f31082434b9599/smarthome.py#L408

**Comment by webpatrick** [comment]
Unfortunately, I cannot update domoticz on my Synology DS213. This is the latest supported version.

**Comment by DewGew** [comment]
> Unfortunately, I cannot update domoticz on my Synology DS213. This is the latest supported version.
http://www.jadahl.com/domoticz_stable_6.2.2020/

**Comment by webpatrick** [comment]
> > Unfortunately, I cannot update domoticz on my Synology DS213. This is the latest supported version.
> > http://www.jadahl.com/domoticz_stable_6.2.2020/

If you click on DS213, you'll see there is no download available.

**Comment by webpatrick** [comment]
With the new version it works again 👍
