### ISSUE TITLE
Home security panel not updated

### ISSUE THREAD

**Issue by steljwagh** [DewGew/Domoticz-Google-Assistant#183]
**Describe the bug:**  
When you set the home security panel to any status (normal/armed home/armed away), it's not updated in DZGA. When I switch another device **after** changing the security panel arming status, the correct status on the security panel is retrieved only after setting another device.

Example:

If you set home security from normal to armed away, the command is executed correctly to Domoticz. But, after that it's not possible to disarm from google because the status is not updated. 

Whenever I switch device X from Domoticz, the status is also not updated in DZGA, also if I synchronize the devices, the status is not updated whenever a devices changed within Domoticz. (Hence the security panel 30s delay) If I send a command from google assistant 

When device X has changed from Domoticz and after that device Y is switched from Google Assistant, also the status from device X is correctly changed, so after that X and Y have the correct status in DZGA.

**Expected behavior:**  
Getting the correct device status in DZGA from Domoticz, not a big problem with lights, but for the security panel and voice arming / disarming your home it's essential.

**Logs:**
I renamed my Domoticz security panel to "Home Security". In the logs nothing special can be found. I think it has to do with the 30 seconds delay.

```
DZGA Version:
1.8.5
Domoticz Version:
2020.2 (build 12221)
```

**Comment by DewGew** [comment]
try without the delay. You change that in domoticz settings.
