### ISSUE TITLE
Multiple rooms 

### ISSUE THREAD

**Issue by rrraf** [DewGew/Domoticz-Google-Assistant#184]
Hi,

Could it be possible to have more than 1 room in the `<voicecontrol>`  tag (like with the nicknames) ?

Some devices can belong to multiple rooms (i.e. an open kitchen/living room with only one temperature sensor) :
- what's the temperature in the kitchen ?
- what's the temparature in the living room ?

It would also be possible to regroup devices in virtual rooms :
- switch off the living room light
- switch off the lights downstairs (i.e. living room light + kitchen light + hall light)

```
<voicecontrol>
   nicknames = living room light
   room = living room, downstairs
   ack = False
   hide = False
</voicecontrol>
```

It can be manually done within the google home app, but it would be nice to be able to set it up in domoticz once and for all ;-)

Regards,
raf

**Comment by DewGew** [comment]
"room"  Provides the current room of the device in the user's home to simplify setup. As you told you can add more in google home app.  Google Assistant requsets this is a string. Can only have 1 room at the moment.

**Comment by rrraf** [comment]
there's a trick to link a device to two rooms : 
setting room name to "Living Room, Salon"
the device can be reached in English and French (salon is french for living room)
one issue : there's a limitation of 26 characters max
and technically "Living Room, Salon" is a separate room as "Living Room".
