### ISSUE TITLE
"Auto" mode for thermostats issue

### ISSUE THREAD

**Issue by rrraf** [DewGew/Domoticz-Google-Assistant#185]
Hi,

I'm having an issue with the "Auto" mode for thermostats : it doesn't seem to be supported and displays "Other mode" instead of "Auto". The option is not available in the mode menu (only 4 options).

> For thermostat devices only.
Function to merge actual temperature from another temp device or modes from selector device to thermostat. Merged device will automaticly hidden. Levels from selector device supported is: Off - Heat - Cool - Auto - Eco.
_Bug Thermostat idx must be a number above Temp/selector idx._

Following the instrcutions, everything works fine with the thermostats (amazing feature to regroup temperatures and selectors, thanks a lot !!!) and other modes work as expected. 

All the modes in screenshots below (except for "Cool", same as "Heat" but blue).

Regards,
raf

![Screenshot_20200818-181415 - Copy](https://user-images.githubusercontent.com/29224455/90539562-46e99c80-e180-11ea-852e-6df8bb89b8de.png) ![Screenshot_20200818-181329 - Copy](https://user-images.githubusercontent.com/29224455/90539558-45b86f80-e180-11ea-901a-4675ce3b74a3.png) ![Screenshot_20200818-181340 - Copy](https://user-images.githubusercontent.com/29224455/90539560-46510600-e180-11ea-9f98-485e51482cb6.png) ![Screenshot_20200818-181350 - Copy](https://user-images.githubusercontent.com/29224455/90539561-46510600-e180-11ea-8201-4f44bab1b39a.png)

**Comment by DewGew** [comment]
That's an issue for Google Assistant. There is an open issue here https://issuetracker.google.com/issues/157717871
