### ISSUE TITLE
Docker issue on RPi3

### ISSUE THREAD

**Issue by saidlm** [DewGew/Domoticz-Google-Assistant#187]
Hi,
I am trying to create and run docker container on RPi but unfortunately I have no success. I have followed step by step the procedure but finally it ends with error message.

Creating domoticz-google-assistant ... error

ERROR: for domoticz-google-assistant  Cannot start service dz-googleassistant: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"python3 /__main__.py\": stat python3 /__main__.py: no such file or directory": unknown

ERROR: for dz-googleassistant  Cannot start service dz-googleassistant: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"python3 /__main__.py\": stat python3 /__main__.py: no such file or directory": unknown
ERROR: Encountered errors while bringing up the project.

Can you help me to fix this issue, please.

Thank you.

**Comment by DewGew** [comment]
Use the arm32v6 version for RPI. Some users had to change the Dockerfile to 
`CMD ["python3", "/__main__.py"]`

**Comment by saidlm** [comment]
Hi,
I am using arm version of code. It wasn't the issue. 
The change you proposed solved the problem.

Thank you for help.
