### ISSUE TITLE
Issue with handling Scenes and Groups

### ISSUE THREAD

**Issue by saidlm** [DewGew/Domoticz-Google-Assistant#188]
Hi,
**Describe the bug:**  
When I would like to hide scene or group with: 

<voicecontrol>
hide = True
</voicecontrol>

in scene/group description and then try to synchronize devices it doesn't work. It shows me error message:

Page not found!: 400 Client Error: Bad Request for url: https://homegraph.googleapis.com/v1/devices:requestSync

As soon as I remove it everything is ok and sync is working again.

Empty voice tag didn't cause the problem the same behavior was with ack = True inside which worked to me.

**Logs:**

```
2020-09-16 15:42:48 - ERROR - 'result'
2020-09-16 15:42:48 - ERROR - Error handling message {'inputs': [{'intent': 'action.devices.SYNC'}], 'requestId': '11958690563145085108'}: {'errorCode': 'unknownError'}
2020-09-16 15:43:01 - INFO - Request {
  "inputs": [
    {
      "intent": "action.devices.SYNC"
    }
  ],
  "requestId": "1151962022791975004"
}
```

**Desktop (please complete the following information):**
 - Domoticz version 2020.1
 - Dzga version 1.8.5 

BR,
Martin

**Comment by DewGew** [comment]
Maybe "hide" does not work with scenes and groups. I look into this.

**Comment by DewGew** [comment]
Tyed to add this function to scenes and groups but cant make it work..
