### ISSUE TITLE
Device "door lock inverted" doesn't work properly

### ISSUE THREAD

**Issue by saidlm** [DewGew/Domoticz-Google-Assistant#189]
Hi,
one of my device is electromagnetic lock which can be opened for few second by sending of short electrical pulse. From domoticz itself it works as device type "door lock inverted" without any issue for years.

When I try to link it with google assistant I am experiencing the issue with "polarity" of the signal coming from dzga to domoticz. When i say "Ok, google. Open the door" or "Ok, google. Unlock the door" domoticz receive OFF command instead of ON. 

It there any possibility to invert the command/signal?

Thanks,
Martin

**Comment by DewGew** [comment]
door lock inverterd is not implemented yet. I'll look into it

**Comment by DewGew** [comment]
Let me know if you get it right :)

**Comment by saidlm** [comment]
Thank you for answer.

It looks that the issue is in if statement above the part of code you mentioned.  The code can't distinguish between lock and lockinv. The fist part of code is activated in my case which most probably means that this part of code is used for the both types of devices - lock and lockinv as well.
I have changed the code by swapping On an Off in the first part of the code (for domain = lock) which in fact solve my issue now. But anyway it is not the solution. As soon as there are the both types of door lock configured in domoticz it will not help.

**Comment by DewGew** [comment]
OK, try change row 98 in **const.py** to:
`'lockinv': 'DoorLockInv',`
Then you can see in devices tab under tab if the device gets right type

**Comment by saidlm** [comment]
One more related information. 
In device list it is shown as DoorLock. Is it right? I suppose DoorLockInverted to be there.

**Comment by DewGew** [comment]
Its shows DoorLock in both, but if you change to above it will show DoorLockInv

**Comment by saidlm** [comment]
It looks that it solves the problem. I have already reverted previous changes with On and Off and in domoticz log I can still see the right command.

**Comment by DewGew** [comment]
Thanks, for pointing this out 👍
