### ISSUE TITLE
The possibility to change default behavior from show everything hide selected to hide everything show selected

### ISSUE THREAD

**Issue by saidlm** [DewGew/Domoticz-Google-Assistant#192]
Hi,
during the configuration of my system I have recognized that I have more devices which are hidden than the active ones.
I have the idea to add global parameter in configuration which will change this behavior and will automatically hide all device instead of that ones which have hide = false in their configuration.  

May be that the idea is valid not only for hide function and can be apply for next ones (e.g. ack??).

Thank you.

**Comment by simple-technician** [comment]
I solved this by creating another user (no need to be admin user) in Domoticz and put this username and password in DzGa config.
In Domoticz you can simply set the devices you want to show up via setup -> more options -> edit users -> set devices.
This doesn't work for scenes and groups though. You can show or hide them all by turning the scenes slider on or off in the acive menus section of that user.

I really like this repository, great work!

**Comment by Tobydeteckel** [comment]
> I solved this by creating another user (no need to be admin user) in Domoticz and put this username and password in DzGa config.
> In Domoticz you can simply set the devices you want to show up via setup -> more options -> edit users -> set devices.
> This doesn't work for scenes and groups though. You can show or hide them all by turning the scenes slider on or off in the acive menus section of that user.
> 
> I really like this repository, great work!

This doesnt change the hidden tag.

**Comment by simple-technician** [comment]
> > I solved this by creating another user (no need to be admin user) in Domoticz and put this username and password in DzGa config.
> > In Domoticz you can simply set the devices you want to show up via setup -> more options -> edit users -> set devices.
> > This doesn't work for scenes and groups though. You can show or hide them all by turning the scenes slider on or off in the acive menus section of that user.
> > I really like this repository, great work!
> 
> This doesnt change the hidden tag.

That's true, you can still hide or show devices using the hidden tag, but only the devices you granted user access for in Domoticz wil be affected.
By creating a new user in Domotics and only give access to a few devices, only those devices wil be visible by default and you don't have do use the hide tag on all your other devices.
Offcourse, in Domoticz settings you have to use webiste protection and don't include DzGa server ip-address in local networks, or DzGa server will still log on as admin in Domoticz.

**Comment by Tobydeteckel** [comment]
always better using a "User" account instead of a "Admin" account accessible from the internet.

But still, If u use different accounts the hidden tags will be active.

**Comment by DewGew** [comment]
Create a room and add those devices you need in dzga there. Then the add the room idx in config:
`roomplan: '123' #Idx of room`
