### ISSUE TITLE
Dont see thermostat of heater with merge_thermo_idx

### ISSUE THREAD

**Issue by k20human** [DewGew/Domoticz-Google-Assistant#199]
**Describe the bug:**  
I use `merge_thermo_idx` feature on my heater to display thermostat on it. Thermostat is marked as merged. When i open heater on Google Home on my phone i only see switch button On / Off, no thermostat settings.

**Expected behavior:**  

**Logs:**
I see on debug mode `temperatureSetpointCelsius` and `temperatureAmbientCelsius` send to Google API

**Desktop (please complete the following information):**
 - Domoticz version : 4.11074
 - Dzga version : lastest master
 - Python Version : 3.73

**Smartphone (please complete the following information):**
 - Device: Redmi Note 6

**Additional context, screenshot:**

**Comment by DewGew** [comment]
There is no UI in google home app for those you can only use with voice.

**Comment by k20human** [comment]
Ok ! So sad :(

Thanks !
