### ISSUE TITLE
For security reasons: log failed login attempts

### ISSUE THREAD

**Issue by sjoerdj** [DewGew/Domoticz-Google-Assistant#201]
Hej DewGew, thanks for this great software!

As the Domoticz Google Assistant is exposed to the internet, I would like to protect it from password guesses and brute force attacks by a solotion that monitors logfiles for failed login attempts. Unfortunately, as far as I can see, none of the loglevels provides for logging failed login attempts.

Therefore, it would be great if logging could be extended with timestamped recording of each failed login attempt that indicates the ip address from which the attempt was made, e.g.:
_2020-10-12 17:18:14 - ERROR - Failed login from 140.82.121.3_

This would allow the monitoring solution to (temporarily) ban the originating ip address.

**Comment by DewGew** [comment]
Can be difficullt if you are using a reverse proxy. You will get the reverse proxy servers ip when you login. Maybe someone have an idea about this.

**Comment by sjoerdj** [comment]
Just did a quick search. It seems that both Nginx and Apache can pass the original IP-address via the X-Forwarded-For header:

- https://www.networkinghowtos.com/howto/set-the-x-forwarded-for-header-on-a-nginx-reverse-proxy-setup/
- https://stackoverflow.com/questions/760283/apache-proxypass-how-to-preserve-original-ip-address

The 'real' webserver can then be configured to use this forwarded address as client ip address:

- https://www.globo.tech/learning-center/x-forwarded-for-ip-nginx/

**Comment by Tobydeteckel** [comment]
#202 
current setup is logging IPs as "none"
Im using only SSL.

Thanks a lot!

**Comment by DewGew** [comment]
> #202
> current setup is logging IPs as "none"
> Im using only SSL.
> 
> Thanks a lot!

#204
