### ISSUE TITLE
Settings page error: module 'pkg_resources' has no attribute 'resource_string'

### ISSUE THREAD

**Issue by sebflipper** [DewGew/Domoticz-Google-Assistant#203]
**Describe the bug:**  
When following the [setup guide to install and run in Docker on a Raspberry Pi](https://github.com/DewGew/Domoticz-Google-Assistant/wiki/DZGA-with-Docker#docker-on-raspberry-pi-arm32v6) the `docker-compose` command successfully builds and starts Domoticz Google Assistant via Docker, however going to http://localhost:3030/settings shows: `Page not found!: module 'pkg_resources' has no attribute 'resource_string'`.

**Expected behaviour:**  
Settings page should be correctly displayed.

**Workaround**
I was able to get it correctly running and setup, however I had to stop the container and rebuild the image using:

1. `cd Domoticz-Google-Assistant`
2. `wget https://bootstrap.pypa.io/ez_setup.py`
3. `chmod +x ez_setup.py`
4. Add `RUN /ez_setup.py` to `Dockerfile` line ~11

I also had to change `${USER}` in `docker-compose.yaml` to be `pi` to get the correct config volume path.

**Raspberry Pi Model/setup:**
* Raspberry Pi 3 Model B Rev 1.2
* Raspbian 8 (jessie)
* Docker version 18.06.3-ce, (build d7080c1)
* docker-compose version 1.25.4

**Comment by DewGew** [comment]
Before I change anything , I need more feedback if there more users having this issue.
