### ISSUE TITLE
Docker container ( on synology ) crashes with upgrading pip on /entrypoint.sh: line 144:   

### ISSUE THREAD

**Issue by mk2k** [DewGew/Domoticz-Google-Assistant#205]
Trying to deploy this image on my docker running on Synology. But it constantly crashes. I tried using the docker compose file and manually creating the container. But all the time it crashes with the following error:
```

First run, checking for any requirements...


Installing all APK requirements...


fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz


(1/24) Installing libgcc (9.3.0-r0)


(2/24) Installing libstdc++ (9.3.0-r0)


(3/24) Installing binutils (2.33.1-r0)


(4/24) Installing libmagic (5.37-r1)


(5/24) Installing file (5.37-r1)


(6/24) Installing gmp (6.1.2-r1)


(7/24) Installing isl (0.18-r0)


(8/24) Installing libgomp (9.3.0-r0)


(9/24) Installing libatomic (9.3.0-r0)


(10/24) Installing mpfr4 (4.0.2-r1)


(11/24) Installing mpc1 (1.1.0-r1)


(12/24) Installing gcc (9.3.0-r0)


(13/24) Installing musl-dev (1.1.24-r2)


(14/24) Installing libc-dev (0.7.2-r0)


(15/24) Installing g++ (9.3.0-r0)


(16/24) Installing make (4.2.1-r2)


(17/24) Installing fortify-headers (1.1-r0)


(18/24) Installing build-base (0.5-r1)


(19/24) Installing nghttp2-libs (1.40.0-r1)


(20/24) Installing libcurl (7.67.0-r1)


(21/24) Installing pcre2 (10.34-r1)


(22/24) Installing git (2.24.3-r0)


(23/24) Installing libc6-compat (1.1.24-r2)


(24/24) Installing linux-headers (4.19.36-r0)


Executing busybox-1.31.1-r9.trigger


: 208 MiB in 62 packages


Pip requirements file detected!


Upgrading Pip...


/entrypoint.sh: line 144:    16 Killed                  pip install $PIP_FLAGS --upgrade pip
```

The config folder is mapped with write permissions and  changed the docker compose file with the correct path.

**Comment by DewGew** [comment]
Any more users that have this issue?

**Comment by DewGew** [comment]
Maybe this have something todo with latest update on python3 packages?

**Comment by goliath49** [comment]
I have the same issue.

Here are some of my experiments, if it can help:

1. Based on DewGew/Domoticz-Google-Assistant:
$ git clone https://github.com/DewGew/Domoticz-Google-Assistant
$ cd Domoticz-Google-Assistant
$ sudo docker build .
$ sudo docker-compose -f docker-compose.yaml up
   => domoticz-google-assistant exited with code 137
$ sudo docker run --rm -it dewgew/domoticz-google-assistant
   => /entrypoint.sh: line 144:    16 Killed                  pip install $PIP_FLAGS --upgrade pip
$ sudo docker run --rm -it dewgew/domoticz-google-assistant /bin/sh
   => /entrypoint.sh: line 144:    16 Killed                  pip install $PIP_FLAGS --upgrade pip

2. Based on jfloff/alpine-python:3.6
Modified Dockerfile with: FROM jfloff/alpine-python:3.6
$ sudo docker build --file Dockerfile_3.6 --tag dzga_3.6  .
$ sudo docker-compose -f docker-compose_3.6.yaml up
   => domoticz-google-assistant3.6 exited with code 2
$ sudo docker run --rm -it dzga_3.6
   => [dumb-init] python3 /__main__.py: No such file or directory
$ sudo docker run --rm -it dzga_3.6 /bin/sh
   # python3 __main__.py 
   => ModuleNotFoundError: No module named 'pid'

**Comment by etmmast** [comment]
yes i have the same problems :(

**Comment by etmmast** [comment]
i think the problem is the path structure, because on the synology there is no home map, there is a homes map with the maps for each user. but only if you switch the home maps on at the users configuration.
when the upgrade comes from the pip, then the file entrypoint.sh uses the wrong path

**Comment by FabrizioRoncato** [comment]
Hello,

I'm facing the same problem with a Synology RS815RP+, the container starts and suddenly stops after some seconds, the container log report the error: "/entrypoint.sh: line 144:    15 Killed                  pip install $PIP_FLAGS --upgrade pip"

Anyone could help me to fix this issue?

Thank you very much
![pip error](https://user-images.githubusercontent.com/45759035/147494074-70f609c1-8633-48eb-b2a4-6ae47366f9c6.jpg)
"
