### ISSUE TITLE
DZGA won't "randomly" started correctly : Program already running with pid: %d" % pid, pid=pid)

### ISSUE THREAD

**Issue by rezzalex** [DewGew/Domoticz-Google-Assistant#213]
**Describe the bug:**  
when starting my NAS every day, sometimes DGZA started smoothly, sometimes not

**Expected behavior:**  
start smoothly with no error

**Logs:**

```
Loading configuration...

Traceback (most recent call last):
  File "/__main__.py", line 109, in <module>
    startServer()
  File "/__main__.py", line 33, in startServer
    with pidfile as p:
  File "/usr/local/lib/pyenv/versions/3.7.3/lib/python3.7/site-packages/pid/base.py", line 239, in __enter__
    self.create()
  File "/usr/local/lib/pyenv/versions/3.7.3/lib/python3.7/site-packages/pid/base.py", line 204, in create
    check_result = self.check()
  File "/usr/local/lib/pyenv/versions/3.7.3/lib/python3.7/site-packages/pid/base.py", line 189, in check
    return self._inner_check(self.fh)
  File "/usr/local/lib/pyenv/versions/3.7.3/lib/python3.7/site-packages/pid/base.py", line 159, in _inner_check
    raise PidFileAlreadyRunningError("Program already running with pid: %d" % pid, pid=pid)
pid.base.PidFileAlreadyRunningError: Program already running with pid: 7
```

**Desktop (please complete the following information):**
 - Domoticz version  beta close to the latest
 - Dzga version DOCKER latest
 - Python Version - the one included in the Docker container

**Additional context, screenshot:**

**Comment by DewGew** [comment]
Do you restart it everyday??

**Comment by rezzalex** [comment]
Yes, my NAS is stoped and restarted everyday automatically.

**Comment by DewGew** [comment]
Best way is to close dzga before you restart your NAS.

**Comment by rezzalex** [comment]
But it is a nas system schedule task.

Do you recommend I close the container ? Kill it ? Or only the DZDGA app ?

**Comment by DewGew** [comment]
Try run a task like docker-compose.yaml stop before doing the restart or a bash script.

**Comment by steljwagh** [comment]
I can confirm this is a issue on running on Docker / Ubuntu

It doesn't matter if you use:
docker-compose -f /home/${USER}/Domoticz-Google-Assistant/docker-compose.yaml start
docker-compose -f /home/${USER}/Domoticz-Google-Assistant/docker-compose.yaml stop

Still pid error.

**Comment by hoppie-1971** [comment]
Hello,
I have the same problem as razzalex.
Docker on synology.
I think it has something to do with the port number which docker assigns to container when started.
I saw i started with 32780 ok
Stopped
Started 32781 nok  
Started 32782 nok
......
Startec 32790 ok !

Maybe this is helpfull.
I think the router or something else thinks the last port before stopped is still open to the public

**Comment by rezzalex** [comment]
I precise that previously I have modified the container's behavior in Portainer to make it "restart always". After testing the new beta version (bravo for the GUI by the way) I have successfully started the container manually this morning, having previously forgot to change this "restart always" parameter.

**Comment by rezzalex** [comment]
> Hello,
> I have the same problem as razzalex.
> Docker on synology.
> I think it has something to do with the port number which docker assigns to container when started.
> I saw i started with 32780 ok
> Stopped
> Started 32781 nok
> Started 32782 nok
> ......
> Startec 32790 ok !
> 
> Maybe this is helpfull.
> I think the router or something else thinks the last port before stopped is still open to the public

Hello hoppie-1971, are you randomly changing the port number to access the container's web interface , or are you mixing up with the PID number ? It's since to be a PID issue. It seems the previous pid number is not killed or free at container closing...

**Comment by hoppie-1971** [comment]
> > Hello,
> > I have the same problem as razzalex.
> > Docker on synology.
> > I think it has something to do with the port number which docker assigns to container when started.
> > I saw i started with 32780 ok
> > Stopped
> > Started 32781 nok
> > Started 32782 nok
> > ......
> > Startec 32790 ok !
> > Maybe this is helpfull.
> > I think the router or something else thinks the last port before stopped is still open to the public
> 
> Hello hoppie-1971, are you randomly changing the port number to access the container's web interface , or are you mixing up with the PID number ? It seems to be a PID issue. It seems the previous pid number is not killed or free at container closing...

Hello razza,
First i had a static portnumber. 32780 in docker on synology
Because thats what i wanted.
But because i had this issue i have now set it on auto. (in docker of synology i set this field empty)
And know after some stops and starts. Some moment i get a 'good' port number. And then i change the nat on router to this portnumber.
Not ideal, but it works.
Maybe this has nothing to do with the problem. But i mentioned it may be it can help.

**Comment by rezzalex** [comment]
Here what I have changed in my conf file... since 1 or 2 days. I am using the beta from a couple of days too, 
It seems to be fine now... to be monitored and confirmed : 
"
# Change pidfile name and path if needed
#PidFile: '/var/run/dzga.pid'
PidFile: '/config/dzga.pid'

"
So now my PID file is directly on my Host.I don't know if it make a difference or If i just have luck so far...

**Comment by rezzalex** [comment]
Finally. No, same issue this morning....

**Comment by DewGew** [comment]
I don't use docker and I don't know how docker works.

**Comment by rbrouwer** [comment]
I will go with:

PidFile: '/dev/null'

That seems to work for me!

**Comment by rezzalex** [comment]
> I will go with:
> 
> PidFile: '/dev/null'
> 
> That seems to work for me!
> 
> You can also go with: "PidFile: '/config/dzga.pid'", which will make the .pid file visible in the host. If you remove it there, it will also work start fine.

Thank you !

I have restarted the container 3x, no PID fil pb ! :-) let's wait for a Host shutdown and restart to be sure !

**Comment by hoppie-1971** [comment]
Hello 
With latest beta build i have this issue no more.
I made a new container for beta and i checked the automatically startup in docker container,
I did nothing specially for pid file
Thx
Gerard

**Comment by rezzalex** [comment]
The issue disappeared.

Close it.
