### ISSUE TITLE
Docker set time zone

### ISSUE THREAD

**Issue by eldigo** [DewGew/Domoticz-Google-Assistant#215]
It would you could add/read out Time Zone (TZ) from the docker environment variable
environment:
      - TZ="Europe/Amsterdam"

I don't have /etc/timezone or /etc/localtime available on my QNAP running docker
Thanks!

**Comment by DewGew** [comment]
Users dont live in the same timezone, this was the best option but you can change your docker-compose file locally to match your needs.

**Comment by eldigo** [comment]
of course that's why TZ is a variable to be filled in by the user 
setting it to Europe/Amsterdam was just an example.

**Comment by eldigo** [comment]
`apk add tzdata`
Now you can choose any timezone you want
`ls /usr/share/zoneinfo`
`cp /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime`
