### ISSUE TITLE
Google uses technical Domoticz name in confirmation action

### ISSUE THREAD

**Issue by vreesie18** [DewGew/Domoticz-Google-Assistant#216]
I started recently using the latest version of dzga and noticed something important for me seems to be changed. See part of my config below. 

**Earlier version:**
When I asked Google with "okay Google, turn on Nanoleaf Scene Ocean", Google replied with "okay, I will turn **Nanoleaf Scene Ocean** on"

**Current version:**
When I asked Google with "okay Google, turn on Nanoleaf Scene Ocean", Google replies with "okay, I will turn **dzga alx1 nanoleaf ocean** on"

So Google replies with the technical name from Domotiz instead of the name I entered in the config and used to speak to Google.

Is this a change somewhere, is it fixable, I don't like this at all. Btw old versions stills works okay, so it seems to be dzga related.

I hope I made myself clear, otherwise please ask.
Regards,
Andre

**dzga config**
 18634:
    ack: false
    room: 'xxxyyyzzz'
    nicknames:
      - 'Nanoleaf Scene Ocean'

**Domoticz**
Idx: 18634
Name: dzga and nanoleaf ocean

**Comment by vreesie18** [comment]
I noticed that the effect as described above sometimes disappears after some time and appears again after a restart of the dzga server. At the moment (restarted yesterday) it still listens to the nicknames (**Nanoleaf Scene Ocean**) as entered in the dzga config but does reply with the original, in my case more technical, domoticz name, in my example **dzga alx1 nanoleaf ocean**.

Can anyone explain this behavior ?

Regards,
Andre

**Comment by DewGew** [comment]
I dont have that issue. I tryed to reproduce this. Is it only your ocean devices or all devices?

**Comment by vreesie18** [comment]
The problem is for every device I have in dzga. I have tried everything I could:

- Changing the port
- Changing the URL
- Tried multiple times to setup dzga from the beginning

Now, it's sometimes a different story, because what I have seen I have a few variants of this bug:

1. The Google Home can listen to the nicknames, but replies with system name
2. The Google Home can only listen to sytem names
3. The Google Home says, that every device needs to be configured

It a really weird behaviour, because it's not always the same. Already tried to find the logic, but no success.
I understand that if something isn't reproducible it's hard to fix. For now, I changed the names of the devices in the Google Home app, but I am afraid that when I sync devices again, the names will be overwritten again.

PS: Maybe a little feature request.... If you give one or more nicknames in the config.yaml, then the first one should be primary name on the Google Home. Perhaps it's a good idea to let it be triggered by an extra variable in the config.yaml, to disable and enable it. I will be more then happy to test it for you 👍 


Your dzga remains brilliant!!!

**Comment by DewGew** [comment]
do you use device_config in config.yaml. does it have same issue if you use <voicecontrol> tags in device description in domoticz?

**Comment by vreesie18** [comment]
In my config.yaml I have set every device like this:
```
Device_Config:
  17875:
    ack: false
    room: 'Kamer Alexander'
    nicknames:
      - 'Alexander thermostaat'
      - 'Thermostaat Alexander'

  17871:
    ack: false
    room: 'Kamer Valerie'
    nicknames:
      - 'Valerie thermostaat'
      - 'Thermostaat Valerie'
```

The "voicecontrol" tags in domoticz don't do the trick, already tried that!

**Comment by DewGew** [comment]
Primary name dzga gets that from domoticz name. You can change that in Google Home app. The nicknames google just listens for. I think google speaks out primary name or name you enter in google home app.

**Comment by vreesie18** [comment]
I think that that is not true, if I said to Google in the recent past: : "hey Google, turn on Chromecast", Google replied with "Turning Chromecast" where Cromemecast was the nickname for this device in the config.yaml and "dzga harmony chromecast" was the device name in Domoticz and the name in the google home app. 

So Google always replied with the used nickname instead of the Google Home app device  name (=Domoticz device name).

Something, somewhere must have been changed recently, most likely on the Google side. Of course there is a work-a-round by changing the names in the Google Home App, but the way it worked by the config.yaml was much easier to maintain.

I leave it for now and wait for perhaps any more users encountering this problem.

Thanks!!

Regards,
Andre

**Comment by DewGew** [comment]
#224 #223
