### ISSUE TITLE
Cast RTSP stream to Chromecast

### ISSUE THREAD

**Issue by vreesie18** [DewGew/Domoticz-Google-Assistant#217]
### Problem
I am followed the guide about: "Stream camera to chromecast", but I think the guide is missing information. When I ask Google Home to turn on the device with the given IDX in the `config.yaml`, she says that she turned on the device, but doesn't cast the stream to the Chromecast. 

### What I did
- I created a mp4 file with a live stream of my security camera.
- I added the config (given in the guide) to the `config.yaml`, with the right IDX and URL.
- I restarted the dzga server and syncronized the devices

### What I want
Could you please tell me what I am missing in these steps or provide me more information about this section of your guide? I have done everything the guide said (which is not much), but no luck in casting the stream to the Chromecast.

Please let me know!

**Comment by DewGew** [comment]
you need to setup a rtsp server for example this https://github.com/aler9/rtsp-simple-server.
I use shinobi video where I can get mp4 stream from my cameras

**Comment by vreesie18** [comment]
Thats not the problem. I created a dummy switch with an underlying script that starts an rstp stream, which saves a mp4 file on a location that is accessible from the web. In domoticz I also created a camera device and attached the same dummy switch to it, so if the camera is activated, the rtsp stream will start. However, I am missing the connection between the Google Home and the Chromecast. How does the Google Home know that he has to play the stream on the Chromecast in my livingroom (we have multiple chromecasts)? I got the feeling that I am missing pieces from the puzzle

**Comment by DewGew** [comment]
Its connected to your chromecast thrue your Google Account (Google Home App). Dont forget in domoticz you need to attach a switch to your camera ( Settings/Camera, add the switch to the camera).

This works with shinobi:
```
Camera_Stream:
  Enabled: true
  Cameras:
    Idx:
      - '429'
    Camera_URL:
      - 'http://192.168.1.202:8080/fdoj1m7mRkkmRSdFZ7TGBGizIBPKa5/mp4/admin/Camera1/s.mp4
```

**Comment by vreesie18** [comment]
My questions are:
- what does the (dummy) switch in Domoticz need to do ? Starting a script to convert the cams rstp to a mp4 file  and save on a web accesible  locations  (http:.......mp4) ?
- why is switch in domoticz attached to a camera ? Does it need to start recording when the camera turns on ?
- how is the menaning of the cam configuration in config.yaml ? Does the idx tag in this file needs to be set to the idx number of the switch in domoticz ?
- what is the command to google home assistant to start streaming the cam on Chromecast

Missing sort of the whole picture, the documentation on this subject might be a more detailed.

Thank you

**Comment by DewGew** [comment]
To get the camera device in Google home app. I use a dummy switch attached to a camera.

**Comment by DewGew** [comment]
Still an issue?

**Comment by vreesie18** [comment]
yes, I still don't understand the whole picture. Would be nice to have a sort of example of the config.yaml.

For now, this is my situation where 19136 is the idx of the switch in Domoticz which start the recording to the mp4 file:

Camera_Stream:
  Enabled: false
  Cameras:
    Idx:
      - '19316'
    Camera_URL:
      - 'https://..........nl/mp4/cam1.mp4'

**Comment by DewGew** [comment]
Enabled: True

**Comment by vreesie18** [comment]
And what should be the spoken commando to activate the stream om chromecast, let's say the camera name in domoticz is 'camera front door' ?

**Comment by DewGew** [comment]
”Show front door camera on [Chromecast device name]”

**Comment by vreesie18** [comment]
So frustrating, still the same, starts playing all kind of camera related youtube movies on my chronecast but not my http mp4 stream. I read on discord that a user named Thatch had the same issue. Looks like its solved on his site but I could not read any solution on discord how the problem was fixed.

**Comment by DewGew** [comment]
Try change name on switch to somthing else eg. ”Show [dummy switch name] on [Chromecast device name]”

**Comment by vreesie18** [comment]
yes

**Comment by DewGew** [comment]
Try this in config (dont change the url):
```

Camera_Stream:
  Enabled: true
  Cameras:
    Idx:
      - '19316'
    Camera_URL:
      - 'https://content.jwplatform.com/manifests/yp34SRmf.m3u8'
```
Name you dummy camera switch to maybe "front door camera"
Your chromecast name is maybe "Livingroom TV"

then restart dzga
sync your devices (by voice or button in UI)

then try commands:
**User:** Show front door camera on livingroom TV.
**Google:** Streaming front door camera on livingroom TV.

Now you should see someone riding a bike on you livingroom TV...

**Comment by vreesie18** [comment]
Eventually....Shinobi did the job :-)

**Comment by vreesie18** [comment]
Thanks for your support!!
