### ISSUE TITLE
On upgrade 'somehow' verify if new dependencies are already available

### ISSUE THREAD

**Issue by rhuijben** [DewGew/Domoticz-Google-Assistant#220]
**Describe the bug:**  

Over the last few upgrades my raspberry pi failed to restart on the upgrade. In most cases this was caused by new requirements being added to DZGA.

It would be nice if DZGA could somehow detect this case before the restart. Perhaps by just running
$ bash Domoticz-Google-Assistant/scripts/install.sh
as that fixed it this time

**Expected behavior:**  

The upgrade button shouldn't just break DZGA. It should at least give an error that helps me recover from this issue.

**Logs:**

```
Paste the dzga logs here.
```
The relevant case from last beta to current was:
Jinja2-2.11.2 MarkupSafe-1.1.1

**Desktop (please complete the following information):**
 - Domoticz version 
 - Dzga version 
 - Python Version 

**Smartphone (please complete the following information):**
 - Device: 

**Additional context, screenshot:**

**Comment by rhuijben** [comment]
Otherwise: Nice upgrade with the new UI :-)

**Comment by DewGew** [comment]
pip requirements (your case jinja2) is suppost to be updated when hitting the update button in UI.
I changed to call pip3 instaed of pip in master branch

**Comment by DewGew** [comment]
Fixed in latest beta (V.1.9.2)
