### ISSUE TITLE
Google Home app primary naming switch

### ISSUE THREAD

**Issue by vreesie18** [DewGew/Domoticz-Google-Assistant#223]
**Current situation**
The primary name for a device in Domiticz will be transferred as the primary name of the device in the Google Home app.

**Issue**
For those people like me who use an other language or more technical naming convention for their devices in Domoticz, they have to rename the primay names in the Google Home app to have proper spoken confirmation messages from Google. This is a lot of work, and all the work will be gone with a relink or any other hick-up in the link to dzga from the Google Home app.

**Suggestion**
My suggestion for fixing this issue would be:

- create an extra config parameter in the config.yaml like PrimaryNamingSource which can have the values Domoticz (default) or Nickname
- with the value Domoticz all stays the same, the primary name from Domoticz will be the primary name in the Google Home app
- _with the value **Nickname**, the software needs the check if a device has nicknames in the config.yaml. If it has nicknames, the first nickname will be the primary name in the Google home app. If it hasn't nicknames, the Domoticz name will be the primary name in the Google Home app._

With this implementation, the only thing you need to have in place, is a proper config.yaml. Now you can link and unlink without manuall having to set all the primary devices names for proper spoken confimation messages from Google. 

I will be more then happy to test it for you 👍

Regards,
Andre

**Comment by DewGew** [comment]
Try latest beta

<voicecontrol>
name = My cool name
<voicecontrol>
or

Device_Config:
  123:
    name: 'My cool name'

**Comment by vreesie18** [comment]
Tried beta, looks nice, like the new layout,

one small thing, device name in GH app isn't updated after it was changed afterwards in the name tag of the config.yaml.

Lets say at first entry the name of a device was 'livingroom' in the config.yaml, so in GH app is also 'livingroom'.

If you now change the name tag in config.yaml to 'living room' and click on restart server and update devices, the name will not be update in the GH app.


regards,
Andre

**Comment by DewGew** [comment]
If you change in config.yaml you need to restart dzga then sync devices. If you use the voicecontrol in descripthion youjust need to sync devices.

**Comment by vreesie18** [comment]
Even after a server restart (use config.yaml) and sync is not gonna happen.

**Comment by vreesie18** [comment]
Clear name in GH app first works.
