### ISSUE TITLE
Small Gui scroll bug.

### ISSUE THREAD

**Issue by SargonofAssyria** [DewGew/Domoticz-Google-Assistant#228]
**Describe the bug:**  
When, in the nice new GUI, you click on devices and scroll a page or more downwards and then click on Configuration you are presented with an almost empty screen, because the Config box is at the top.
The same happens with other menu items.

**Expected behavior:**  
Start at the top of the screen.

**Desktop (please complete the following information):**
 - Domoticz version Beta 2020.2 build 12644
 - Dzga version 1.9.5. beta
 - Python Version 3.7.3

B.t.w. Very nice new GUI>

**Comment by DewGew** [comment]
Trying to find this issue...
