### ISSUE TITLE
Installation problem on Synology

### ISSUE THREAD

**Issue by goliath49** [DewGew/Domoticz-Google-Assistant#229]
My platform is Synology Model DS1511+, INTEL Atom D525, DSM 6.2.3-25426 Update 2
I created an account « domoticz » in admin group 

I have troubles when installing with both approaches:  1. Installation Synology & 2. Manual installation  [cf. https://github.com/DewGew/Domoticz-Google-Assistant/wiki/1.-Installation]

1. Installation Synology
$ cd /volume1/${USER}/ -> not valid on my Synology =>
$ cd /var/services/homes/domoticz
$ git clone https://github.com/DewGew/Domoticz-Google-Assistant
$ sudo bash Domoticz-Google-Assistant/scripts/install_synology.sh
=>Error: "Create virtual enviroment...
Error: Command '['/volume1/homes/domoticz/Domoticz-Google-Assistant/env/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1."

2. Manual installation
$ pip install -r Domoticz-Google-Assistant/requirements/pip-requirements.txt
=> Error: "ERROR: Could not find a version that satisfies the requirement GitPython>=3.0.5 (from -r Domoticz-Google-Assistant/requirements/pip-requirements.txt (line 9)) (from versions: 0.1.7, 0.2.0b1, 0.3.0b1, 0.3.0b2, 0.3.1b2, 0.3.2rc1, 0.3.2, 0.3.2.1, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 1.0.0, 1.0.1, 1.0.2, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9.dev0, 2.0.9.dev1, 2.0.9, 2.1.0, 2.1.1, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7, 2.1.8, 2.1.9, 2.1.10, 2.1.11, 2.1.13, 2.1.14, 2.1.15)
ERROR: No matching distribution found for GitPython>=3.0.5 (from -r Domoticz-Google-Assistant/requirements/pip-requirements.txt (line 9))"

**Comment by DewGew** [comment]
This issue is with synology latest python3 package. Pip and virtualenv is not included anymore.

**Comment by DewGew** [comment]
Try change in install_synology.sh in row 55 to:
`python3 -m virtualenv ${INSTALL_DIR}/env`

**Comment by goliath49** [comment]
It leads now to the error:
/usr/local/bin/python3: No module named virtualenv

So I had to add the following:
wget https://bootstrap.pypa.io/get-pip.py
python3 get-pip.py
python3 -m pip install virtualenv
python3 -m virtualenv ${INSTALL_DIR}/env

As is, this leads to error:
sudo: /volume1/homes/domoticz/dzga-daemon: command not found

But I realized I was in /volume1/homes/domoticz/Domoticz-Google-Assistant instead of /volume1/homes/domoticz (my mistake), so 1st line was probably useless.
And in this case, when launching
$ sudo bash Domoticz-Google-Assistant/scripts/install_synology.sh
then all is ok!

Thanks DewGew

**Comment by DewGew** [comment]
Thanks, i got it working too

**Comment by webpatrick** [comment]
Great find, my DZGA on Synology DS213 stopped working last week, this fixed it.
