### ISSUE TITLE
Trouble with report_state

### ISSUE THREAD

**Issue by nonameboy007** [DewGew/Domoticz-Google-Assistant#236]
Hello, 

First of all, sorry for my bad english 😅

I have a trouble with my use of this spectacular plugin. 

I've done what is written on your installation page, and all working very well. But when i tell Google to close a blind, he tell me that he already closed... 
Its possible to force him to close anyway?

This is what i have in my config.yaml file:

> Device_Config:
  75:
    report_state: false
    nicknames:
    - tata

Voicematch work when I'm saying tata, but the directive report_state seems to not being working...

This is what i have on the dzga.log:

> 2020-12-02 02:31:09 - INFO - Request {
  "inputs": [
    {
      "context": {
        "locale_country": "FR",
        "locale_language": "fr"
      },
      "intent": "action.devices.EXECUTE",
      "payload": {
        "commands": [
          {
            "devices": [
              {
                "id": "Blind75"
              }
            ],
            "execution": [
              {
                "command": "action.devices.commands.OpenClose",
                "params": {
                  "openPercent": 0
                }
              }
            ]
          }
        ]
      }
    }
  ],
  "requestId": "126XXXXXXXX"
}
2020-12-02 02:31:09 - ERROR - Unable to execute action.devices.commands.OpenClose for Blind75. Already in state

Any clue for me?

Thank you for your help 

Cheers

**Comment by DewGew** [comment]
Do you use blind precentage or just open/close blinds, Inverted ?

**Comment by nonameboy007** [comment]
Hi,

Thanks for your response, i m using blinds only, with open/stop/close commands.

these are somfy blinds, used with the RFY protocol. 

Sometimes I use home automation, sometimes I use the somfy remote control.  

That's why I don't want the state to be recovered, and actions to be executed regardless of the state. Its possible?

**Comment by DewGew** [comment]
Then you have to modify your self. In trait.py under class OpenCloseTrait, change from row 394 to 403:
```
if p == 100 and state in ['Closed', 'Stopped', 'On']:
  # open
  url += 'Off'
elif p == 0 and state in ['Open', 'Stopped', 'Off']:
  # close
  url += 'On'
else:
  raise SmartHomeError(ERR_ALREADY_IN_STATE,
                       'Unable to execute {} for {}. Already in state '.format(command,
                                                                               self.state.entity_id))
```
to: 

```
if p == 100
  # open
  url += 'Off'
elif p == 0 
  # close
  url += 'On'
```

**Comment by nonameboy007** [comment]
Hi DewGew,

Thank you for your feedback.

Its good for me now.

Cheers
