### ISSUE TITLE
Hide category of devices (by default), or another method to hide a lot of devices at once

### ISSUE THREAD

**Issue by Whizzzer** [DewGew/Domoticz-Google-Assistant#237]
Maybe it's already available and I didn't find it. So if this is the case, please let me know! Or if a creative solution/workaround exists, also fine!

Thing is, I have a bunch of temp/hum devices, motion sensors and other sensors (acting as switches) within Domoticz. They are important for my smarthome, yet not for the Google Assistant integration. At this point they all show up in my Google Home App, which is kind of useless... I'm aware of the "voicecontrol" option you can put in the description of the device in Domoticz, but then I have to adjust >90 devices.

It would be nice if there was an option to hide a complete category of devices. And if needed, you can enable specific devices via the "voicecontrol" option or something similar. So basically the opposite of what happens at this moment.

At this point from all the devices in my Domoticz setup, I only would like a handful in my Google Home app... I would think I'm not the only one who would like this, but since I can't find any similar request/issue, I'm either the first one, or it is already possible...

**Comment by DewGew** [comment]
There is several sulutions for this. As you said hide to true in voicecontrol or in device_config in config.yaml. You also can create a separate user in domoticz and attach the devices you want for GA. Or putt devices for GA in a room then add the roomplan idx in config.yaml

**Comment by Whizzzer** [comment]
The "roomplan" option is indeed a nice one for this since you can attach one device to multiple rooms. This way it won't mess up your already configured roomplan.
