### ISSUE TITLE
Failed to link account

### ISSUE THREAD

**Issue by lily148** [DewGew/Domoticz-Google-Assistant#24]
Hi, I follow your tutorial to try out the service. But I can't link my account.
After I enter the outh username and password I specified in the config.py, it just refresh the page with:
https://mypublicip.com/login?client_id=None&redirect_uri=None&redirect=None&state=None

At the server log:
"POST /login HTTP/1.1" 301 -
103.220.5.154 - - [10/Jul/2019 17:17:13] "GET /login?client_id=None&redirect_uri=None&redirect=None&state=None HTTP/1.1" 200 -

Did I do anything wrong?

**Comment by lily148** [comment]
I found the issue.. .it seem like the outh password cannot have symbol...

**Comment by DewGew** [comment]
Great👍
