### ISSUE TITLE
Sending text queries to Google Assistant

### ISSUE THREAD

**Issue by twoenter** [DewGew/Domoticz-Google-Assistant#243]
Is it possible to send a command to the Google home, which will run it and give a voice response?

My goal is to receive a notification via the Google home when the laundry is ready or when someone rings the bell. I want to use the broadcast function for that. The advantage of this is that the music or video that plays continues after the notification. 

Like in this thread https://www.domoticz.com/forum/viewtopic.php?t=24557&sid=68c8b1f137f093e759b89dcba0666e88

And this user can send text queries to google home

https://github.com/endoplasmic/google-assistant

Can we do this with dzga?

**Comment by DewGew** [comment]
Read #239

**Comment by twoenter** [comment]
Thank you for reply.

It is not the same. If I understand it correctly, the solution of issue 239 plays the notification and does not resume playing current media. With the broadcast function it does. My feature request is to send a notification with the broadcast feature of Google nest which pauses media, play notification and resumes playing media.

**Comment by DewGew** [comment]
This would be great to implement.  Broadcast function require google assistant sdk. I will look into this. You can also look at https://github.com/greghesp/assistant-relay this offers what you ask in a separate node.js server

**Comment by twoenter** [comment]
> 
> 
> This would be great to implement. Broadcast function require google assistant sdk. I will look into this. 

That would be nice! 




> 
> 
> You can also look at https://github.com/greghesp/assistant-relay this offers what you ask in a separate node.js server

Cool project. Did not found it myself. Thanks!
Dived into it, does not run on my synology because the syno fails at the install of gprc and node-pre-gyp. 

Hope your implementation does work at synology NAS!

**Comment by rezzalex** [comment]
> > 
> > 
> > This would be great to implement. Broadcast function require google assistant sdk. I will look into this. 
> 
> That would be nice! 
> 
> 
> 
> 
> > 
> > 
> > You can also look at https://github.com/greghesp/assistant-relay this offers what you ask in a separate node.js server
> 
> Cool project. Did not found it myself. Thanks!
> Dived into it, does not run on my synology because the syno fails at the install of gprc and node-pre-gyp. 
> 
> Hope your implementation does work at synology NAS!

@twoenter , there is a container for that
Try on your Nas: https://github.com/Apipa169/Assistant-Relay-Docker

**Comment by twoenter** [comment]
> @twoenter , there is a container for that
> Try on your Nas: https://github.com/Apipa169/Assistant-Relay-Docker

Thanks! My syno ds216j has no support for docker😭
