### ISSUE TITLE
do not use absolute path for URL

### ISSUE THREAD

**Issue by Damien60** [DewGew/Domoticz-Google-Assistant#244]
**Describe the bug:**  
0 connected devices when connected from Internet with https://[public_url]/assistant/settings.
Nginx is configured with **reverse proxy** to http://localhost:3030 and **rewrite** ^/assistant/?(.*) /$1 break;
Everything is OK from local network and http://localhost:3030.

The problem is that functions.js uses absolute path for /states and /log to generate the URL.
And from internet, https://[public_url]/states is not accessible. ("assistant" is missing)

**Expected behavior:**  
With relative path ("./states" & "./log"), it's OK.
There is maybe more paths to fixed.
Check with web console in navigator.

Thanks

**Comment by DewGew** [comment]
Somthing with this?
```
location /assistant {
      rewrite ^/assistant/?(.*) /$1 break;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Scheme $scheme;
      proxy_pass https://localhost:3030; #local ipno to dzga
      proxy_read_timeout  90;
}
```

**Comment by Damien60** [comment]
yes
but proxy_pass http://localhost:3030

**Comment by VedeeM** [comment]
I can confirm. I have the same problem
Solution of @Damien60 works for me

dzga version 1.10.6 beta
domoticz 2020.2

**Comment by DewGew** [comment]
Create a pull request with your changes to beta branch

**Comment by Justdigit** [comment]
Same problem especially when you want to do a reverse proxy with Nginx reverse Proxy manager.
