### ISSUE TITLE
Kodi support

### ISSUE THREAD

**Issue by Enjoy-Combi** [DewGew/Domoticz-Google-Assistant#247]
**Is your feature request related to a problem? Please describe.**
No interaction with media player kodi when asking to google assistant.
**Describe the solution you'd like**
control kodi by voice for pause, play, volume,...
**Describe alternatives you've considered**
GoogleHomeKodi but this one relies on IFTTT
**Additional context**

**Comment by DewGew** [comment]
Thanks, I put that on my list.

**Comment by DewGew** [comment]
Still on my list..
