### ISSUE TITLE
Reversed State in Garage Door as Inverted Blinds with Partial FIX

### ISSUE THREAD

**Issue by j0nson** [DewGew/Domoticz-Google-Assistant#249]
**Suggested Partial Fix**
Line 383 in trait.py:
if p == 100 and state in ['Closed', 'Stopped', 'On']:

Line 386 in trait.py
elif p == 0 and state in ['Open', 'Stopped', 'Off']:

This partial fix only allows one cycle of opening or closing the door, after the action is done once, GHA reports the door in the incorrect state (open when closed, or closed when open). 

**Describe the bug:**  
Google Home Assistant reports garage doors as open when they are closed, and vice-versa. So, when I request to open the garage door, GHA reports the door is already open. If I ask GHA to close the door when it's already closed, it opens the garage door.

**Expected behavior:**  
Correct reporting state of inverted blinds

**Logs:**
2021-03-12 16:56:42 - DEBUG - {
  "Garage Door 2": {
    "idx": 54,
    "type": "BlindInverted",
    "state": "Closed",
    "lastupdate": "2021-03-12 11:52:20",
    "nicknames": [
      "Garage Door Number 2"
    ],
    "willReportState": false
  }
}
xxxxxxxxxx

2021-03-12 17:04:02 - INFO - Request {
  "inputs": [
    {
      "context": {
        "locale_country": "US",
        "locale_language": "en"
      },
      "intent": "action.devices.EXECUTE",
      "payload": {
        "commands": [
          {
            "devices": [
              {
                "id": "BlindInverted54"
              }
            ],
            "execution": [
              {
                "command": "action.devices.commands.OpenClose",
                "params": {
                  "openPercent": 100
                }
              }
            ]
          }
        ]
      }
    }
  ],
  "requestId": "13926520598232829014"
}
2021-03-12 17:04:02 - ERROR - Unable to execute action.devices.commands.OpenClose for BlindInverted54. Already in state 

**Desktop (please complete the following information):**
DZGA Version: 1.9.6
Domoticz Version: 2020.2
Python Version 3.6.9

**Comment by DewGew** [comment]
What happens if you dont use blinds inverted as for your garage door?

**Comment by Tezzlicious** [comment]
It seems the Blind type state is indeed inverted. Domoticz (latest beta) is reporting it closed, while Domoticz-Google-Assistant UI says it's open. When I tell Google to close it, it get's synced...

**Comment by DewGew** [comment]
@Tezzlicious is this issue when using as Door or Blinds, or in both?

**Comment by Edwin-z** [comment]
Same problem here. It works as aspected when using non inverted blinds
