### ISSUE TITLE
Room change

### ISSUE THREAD

**Issue by paifre** [DewGew/Domoticz-Google-Assistant#25]
Hello,

I noticed that once you are not publishing a room in the config.py for a device, then updating the room in the config.py is not reported in the application.
The nickname was updated correctly in GA after several changes in the config.py

For sure, I have resync and restarted several times :)

This is a minor problem as you are not supposed to moved all devices to another room every day...

One comment out of this context: Adding a comment in the config.py or readme: "Not end Domoticz URL with a slash character" would avoid a trap, I fall in...
2nd comment: Having a list all URLs to be reversed proxied (inc. /login /sync) would remove a second trap. I fall in too :)

In all cases, really great job.  I would love have it merge natively into Domoticz

Thx

**Comment by DewGew** [comment]
rThanks for reporting this. You are wlcome to contibute with a pull request on this issue.

**Comment by DewGew** [comment]
I think I found whats wrong Try change in the config.py 
`room : 'Kitchen'`, 
to
`room : ['Kitchen'],`
