### ISSUE TITLE
Agregar pagina web html en /

### ISSUE THREAD

**Issue by nbaglietto** [DewGew/Domoticz-Google-Assistant#254]
Hola ya eche a correr el servidor y funciona ok pero el problema que tengo es que al poner la dirección de mi sitio https://ezpeleta.myftp.org/ me muestra "Page not found!: '/'" y quisiera que ahí mostrase una pagina propia index.html 
Probé de diferentes formas modificar la configuración de /etc/nginx/sites-enabled/default sin éxito.
Como podria lograr que nginx pueda mostrar dos carpetas tipo:
https://ezpeleta.myftp.org/dgza/settings y otra que fuera https://ezpeleta.myftp.org/index.html ?

Gracias
Nahuel

**Comment by deexiz** [comment]
https://ezpeleta.myftp.org/login?redirect_uri=settings

**Comment by nbaglietto** [comment]
no comprendo https://ezpeleta.myftp.org/login?redirect_uri=settings funciona ok.
pero como tengo que hacer para q nignix me muestre otra pagina en el home tipo:  https://ezpeleta.myftp.org/index.html

Gracias

**Comment by DewGew** [comment]
Please you english language!

**Comment by DewGew** [comment]
This issue has nothing to do with dzga. Its a nginx issue. https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/
