### ISSUE TITLE
Docker container (on synology) crashes with upgrading pip on /entrypoint.sh

### ISSUE THREAD

**Issue by FabrizioRoncato** [DewGew/Domoticz-Google-Assistant#272]
Hello,

I'm facing problem to start the container with a Synology RS815RP+, DSM 7.0, the container starts and suddenly stops after some seconds, the container log report the error: "/entrypoint.sh: line 144: 15 Killed pip install $PIP_FLAGS --upgrade pip"

Anyone could help me to fix this issue?

Thank you very much
![147494074-70f609c1-8633-48eb-b2a4-6ae47366f9c6](https://user-images.githubusercontent.com/45759035/147564989-6877998c-de98-49c9-b68a-72d4a18d68e8.jpg)

**Comment by FabrizioRoncato** [comment]
@DewGew hello, could you please help me to solve this problem?
I really can't understand why I am having this issue

Thank you very much!

**Comment by vespino** [comment]
Facing the same issue here.

**Comment by FabrizioRoncato** [comment]
> Facing the same issue here.

Try to execute this command via ssh console:

`sudo /volume1/dzga-daemon start`

The dzga will start and will be reachable at ip:3039/settings

Obly thing is that there isn't the container running under the docker list on Synology

**Comment by FabrizioRoncato** [comment]
> Since we’re talking about Docker, how is it I have to use that command? It’s not on my Synology.

Hello,

read carefully my first post, I am talking about docker problem with a Synology NAS.

Bye bye

**Comment by vespino** [comment]
Correct, so if you’re using Docker, there is no such thing as dzga-daemon on Synology.

**Comment by FabrizioRoncato** [comment]
> Correct, so if you’re using Docker, there is no such thing as dzga-daemon on Synology.

Yes instead, because dzga is running in a docker, could you help?

**Comment by vespino** [comment]
@FabrizioRoncato like I said, I'm facing the same issue and was hoping @DewGew could help up.

**Comment by DewGew** [comment]
Hi all sorry for the late reply.
Im not using docker myself so I have to rely on those who uses docker. Any contribution is welcome.

**Comment by DewGew** [comment]
Still an issue?

**Comment by vespino** [comment]
I’m not using it.
