### ISSUE TITLE
"doorbell" notification type not working

### ISSUE THREAD

**Issue by rezzalex** [DewGew/Domoticz-Google-Assistant#298]
Here is my "conf" in DZ :

![image](https://user-images.githubusercontent.com/35136439/207841589-b60c4c2e-3499-4c53-a502-41121025875b.png)

when I click  on "test", I don't have any notification and receive this error message in DZGA logs : 

`
ERROR - something went wrong, check your notification settings!`

**Comment by DewGew** [comment]
You cant use test, but according to log message its working. Add the correct entity_id for your device in notifications settings according to wiki, then test by puhing the doorbell button.
