### ISSUE TITLE
Reversed operation of blinds in Google Home

### ISSUE THREAD

**Issue by Xavier82** [DewGew/Domoticz-Google-Assistant#301]
**Describe the bug:**  

I use Shelly 2.5 devices to control my blinds, the are added in Domoticz by Shelly MQTT script.
All devices are synced between Domoticz and DZGA.
The state of the blinds (percentage) is shown in Domoticz as for example "Open", the state in DZGA is also shown as "Open" but the state in Google Home is shown as closed, so reversed, relative to Domoticz/DZGA.
When giving a voice command to our Google home hubs: "Open all blinds" then the action is that all blinds stay closed instead of opening. when giving the voice command "Close all blinds" then the action is that all blinds go open.

**Expected behavior:**  

Based on the voice command (but also the CLI in Google Assistant) the action should be the same as the (voice) command.

**Logs:**

N/A, no error in logs just inverted operation.

```
Paste the dzga logs here.
```

**Desktop (please complete the following information):**
 - Domoticz version 2022.2
 - Dzga version 1.22.32 master
 - Python Version 3.9

**Smartphone (please complete the following information):**
 - Device: Google Home Hubs or Android devices (Samsung) with Google Assistant/Google Home apps installed.

**Additional context, screenshot:**

**Comment by DewGew** [comment]
Try change reverse state https://www.domoticz.com/wiki/Blinds

**Comment by Xavier82** [comment]
No change.
I thought I had a solution, I can change within de Shelly MQTT plugin the "reverse state of blinds", I tried that with no luck.
After that I changed the reverse state of 1 blind to test, neighter a solution, Google Home app keeps showing the oposite state (in Domoticz and DZGA state is open, in Google Home app state is closed.)

**Comment by DewGew** [comment]
Whats your states im shelly Mqtt blinds? 
In GA is 100% = Open, 0% = Closed

**Comment by Xavier82** [comment]
In Domoticz after al adjustments it was open =0% and closed 100%, after changing back the configs Now in domoticz 100% = open and 0% = closed, I also had to force a sync (sync devices) on my Google Home Hub and Android devices, since I did this it now looks fine.

Sorry for the inconvenience....

I think his issue can be closed :)
