### ISSUE TITLE
bash <(curl -s https://raw.githubusercontent.com/DewGew/dzga-installer/master/install.sh) does not work anymore

### ISSUE THREAD

**Issue by Braveboy1970** [DewGew/Domoticz-Google-Assistant#303]
**Describe the bug:**  
After running bash "<(curl -s https://raw.githubusercontent.com/DewGew/dzga-installer/master/install.sh)" the install seems all right but the webservice don't get online.

When I enter "sudo systemctl status dzga" I get;

× dzga.service - Domoticz-Google-Assistant Service
Loaded: loaded (/etc/systemd/system/dzga.service; enabled; vendor preset: enabled)
Active: failed (Result: exit-code) since Fri 2022-12-23 15:42:52 CET; 33min ago
Process: 13775 ExecStart=/home/pedro/Domoticz-Google-Assistant/env/bin/python3 /home/pedro/Domoticz-Google-Assistant/ (code=exited, status=203/EXEC)
Main PID: 13775 (code=exited, status=203/EXEC)
CPU: 2ms

dec 23 15:42:52 HTPC systemd[1]: dzga.service: Scheduled restart job, restart counter is at 5.
dec 23 15:42:52 HTPC systemd[1]: Stopped Domoticz-Google-Assistant Service.
dec 23 15:42:52 HTPC systemd[1]: dzga.service: Start request repeated too quickly.
dec 23 15:42:52 HTPC systemd[1]: dzga.service: Failed with result 'exit-code'.
dec 23 15:42:52 HTPC systemd[1]: Failed to start Domoticz-Google-Assistant Service.

When I enter "journalctl -e" I get;
dec 23 15:42:51 HTPC sudo[13766]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
dec 23 15:42:51 HTPC systemd[1]: Started Domoticz-Google-Assistant Service.
dec 23 15:42:51 HTPC systemd[13770]: dzga.service: Failed to locate executable /home/pedro/Domoticz-Google-Assistant/env/bin/python3: No such file or directory
dec 23 15:42:51 HTPC sudo[13766]: pam_unix(sudo:session): session closed for user root
dec 23 15:42:51 HTPC systemd[13770]: dzga.service: Failed at step EXEC spawning /home/pedro/Domoticz-Google-Assistant/env/bin/python3: No such file or directory
dec 23 15:42:51 HTPC systemd[1]: dzga.service: Main process exited, code=exited, status=203/EXEC
dec 23 15:42:51 HTPC systemd[1]: dzga.service: Failed with result 'exit-code'.
dec 23 15:42:51 HTPC systemd[1]: dzga.service: Scheduled restart job, restart counter is at 1.
dec 23 15:42:51 HTPC systemd[1]: Stopped Domoticz-Google-Assistant Service.
dec 23 15:42:51 HTPC systemd[1]: Started Domoticz-Google-Assistant Service.
dec 23 15:42:51 HTPC systemd[13772]: dzga.service: Failed to locate executable /home/pedro/Domoticz-Google-Assistant/env/bin/python3: No such file or directory
dec 23 15:42:51 HTPC systemd[13772]: dzga.service: Failed at step EXEC spawning /home/pedro/Domoticz-Google-Assistant/env/bin/python3: No such file or directory
dec 23 15:42:51 HTPC systemd[1]: dzga.service: Main process exited, code=exited, status=203/EXEC
dec 23 15:42:51 HTPC systemd[1]: dzga.service: Failed with result 'exit-code'.
dec 23 15:42:51 HTPC systemd[1]: dzga.service: Scheduled restart job, restart counter is at 2.
dec 23 15:42:51 HTPC systemd[1]: Stopped Domoticz-Google-Assistant Service.
dec 23 15:42:51 HTPC systemd[1]: Started Domoticz-Google-Assistant Service.
dec 23 15:42:51 HTPC systemd[13773]: dzga.service: Failed to locate executable /home/pedro/Domoticz-Google-Assistant/env/bin/python3: No such file or directory
dec 23 15:42:51 HTPC systemd[13773]: dzga.service: Failed at step EXEC spawning /home/pedro/Domoticz-Google-Assistant/env/bin/python3: No such file or directory
dec 23 15:42:51 HTPC systemd[1]: dzga.service: Main process exited, code=exited, 

So I think some files and folders are missing after installation or the scripts must been reviewed.
The script fails on my Ryzen HTPC with Linux Mint 21.1 on it and fails on my Domoticz-server on Ubuntu server basis with Ubuntu 22.04.1 LTS.

**Comment by DewGew** [comment]
try this if you still have Domoticz-Google-Assistant folder:
```
cd /home/${USER}/
sudo bash Domoticz-Google-Assistant/scripts/install.sh
```
Check if you get any errors
else:
`sudo systemctl start dzga`
