### ISSUE TITLE
Chromecast Notifications

### ISSUE THREAD

**Issue by DewGew** [DewGew/Domoticz-Google-Assistant#304]
**Describe the bug:**  

I'm trying to get Chromecast Notifications working, in config.yaml I have Chromecast_Name: LOunge
WHen I open http://dzgaserver:3030/play?doorbell1.mp3 I get the following:-
Page not found!: 'NoneType' object has no attribute 'volume_level'

**Expected behavior:**  

Play doorbell1.mp3 on my chromecast device

**Logs:**

```
ERROR - Chromecast playmedia unsuccefull, error : Chromecast None:8009 is connecting...
```

**Desktop (please complete the following information):**
 - Domoticz version  2022.2
 - Dzga version V.1.22.34

**Smartphone (please complete the following information):**
 - Device:  Iphone 12 pro

**Additional context, screenshot:**  

Fix. Need to add @50 to set the volume eg.

`http://dzgaserver:3030/play?doorbell1.mp3@50`

**Comment by peteralm097** [comment]
I have had similar issues with chromecast notifications. It looks like the devices are all asked to get the sound from an http:// connection but my dgza seems to only be responding on an https:// - or having tested, the sounds are available from the direct url with https and not http.
