### ISSUE TITLE
DZGA latest beta cannot connect anymore above version Version: 2023.1 (build 15178)

### ISSUE THREAD

**Issue by davidKooreman** [DewGew/Domoticz-Google-Assistant#309]
**Describe the bug:**  
 anymore above version of domoticz Version: 2023.1 (build 15178

**Expected behavior:**  
 no connection to domoticz can be made. Restoring older version of domoticz solves the problem but is unwanted

**Logs:**

Not available 
```
Paste the dzga logs here.
```

**Desktop (please complete the following information):**
 - Domoticz version 
 - Dzga version  latest beta
 - Python Version  

**Smartphone (please complete the following information):**
 - Device: 

**Additional context, screenshot:**

**Comment by perkovich** [comment]
I have problem with the connection between dzga and domiticz since a few days back. Spent two ours yesterday trying to resolve it without success. 
![C1517F28-7339-4F73-850D-756BFF58ADCA](https://user-images.githubusercontent.com/148353/228328159-90e94aa0-0f86-4cd0-a615-53c61798f401.png)

**Comment by davidKooreman** [comment]
Restore a backup of domoticz (if available) wil solve your problem


Op di 28 mrt. 2023 20:04 schreef Per Åström ***@***.***>:

**Comment by bever66** [comment]
Same here, unfortunately I only have a database backup. I cannot revert (easily) to older Domoticz.

**Comment by DewGew** [comment]
I dont have any issues. Try enable Allow Basic Authentication over plain HTTP in security tab in settings.
After enabled it restart domoticz.

**Comment by davidKooreman** [comment]
Thanks that setting solves the problem

Op ma 10 apr. 2023 11:35 schreef DewGew ***@***.***>:
