### ISSUE TITLE
Security ArmDisarm not working context Domoticz Ver 2023.1 <-> Dzga 1.23.2

### ISSUE THREAD

**Issue by mealgi** [DewGew/Domoticz-Google-Assistant#311]
Describe the bug:
I have 50 devices declared in Domoticz version 2022.1 which are interfaced with Domoticz-Google-Assistant v1.11.10
The interface was operating correctly.

I have recently upgraded Domoticz to version 2023.1 and DZGA to 1.23.2.
Since then the Security functionality ArmDisarm is not working anymore. It was working in Domoticz version 2022.1 and DZGA 1.11.10.

When I intent to set the "alarm home" using Google Assistant I am not prompted to provide the security code and I get the message
ERROR - Unable to execute action.devices.commands.ArmDisarm for Security17 - challenge needed
in the log

Expected behavior:
To be prompted for the security code when invoquing the ArmDisarm security in Google Assistant and be able to set or unset the Alarm in Domoticz via voice control.

Logs:
2023-04-20 22:50:05 - INFO - {
  "inputs": [
    {
      "context": {
        "locale_country": "FR",
        "locale_language": "fr"
      },
      "intent": "action.devices.EXECUTE",
      "payload": {
        "commands": [
          {
            "devices": [
              {
                "id": "Security17"
              }
            ],
            "execution": [
              {
                "command": "action.devices.commands.ArmDisarm",
                "params": {
                  "arm": true,
                  "armLevel": "Arm Home"
                }
              }
            ]
          }
        ]
      }
    }
  ],
  "requestId": "5959643188380242688"
}
2023-04-20 22:50:05 - INFO - Google Assistant requests an action.devices.EXECUTE
2023-04-20 22:50:05 - ERROR - Unable to execute action.devices.commands.ArmDisarm for Security17 - challenge needed 
2023-04-20 22:50:06 - ERROR - 400 Client Error: Bad Request for url: https://homegraph.googleapis.com/v1/devices:reportStateAndNotification
2023-04-20 22:50:06 - ERROR - Error handling message {'inputs': [{'context': {'locale_country': 'FR', 'locale_language': 'fr'}, 'intent': 'action.devices.EXECUTE', 'payload': {'commands': [{'devices': [{'id': 'Security17'}], 'execution': [{'command': 'action.devices.commands.ArmDisarm', 'params': {'arm': True, 'armLevel': 'Arm Home', 'online': True}}]}]}}], 'requestId': '5959643188380242688'}: {'errorCode': 'unknownError'}

Desktop (please complete the following information):

Domoticz on RPI3B
Version: 2023.1 (build 15182)
Build Hash: 34815c1a9-modified
Compile Date: 2023-04-10 17:22:59
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Oct 31 2022, 14:04:00) [GCC 8.3.0]
Domoticz-Google-Assistant 1.23.2
Smartphone (please complete the following information):

Device: iPhone6

Additional context, screenshot:
The parameter "followUpToken" described in the https://developers.google.com/actions/smarthome/traits/armdisarm specification in not defined in the above payload.

BR

**Comment by mealgi** [comment]
Hello,

I added 
<voicecontrol>
report_state = False
</voicecontrol>
in the device description and now I can voice control the security (Arm Away/Arm Home/Disarm).

The security state is not reported in Google Home. I only get the setting in google home.

BR

**Comment by mealgi** [comment]
Hello,

Is it needed to add report_state = False in the device description in version 1.32.3 ?

BR

**Comment by mealgi** [comment]
Sorry version 1.23.3.

**Comment by DewGew** [comment]
> Hello,
> 
> Is it needed to add report_state = False in the device description in version 1.32.3 ?
> 
> BR

Yes it is for now!
