### ISSUE TITLE
Docker "ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with LibreSSL 3.0.2."

### ISSUE THREAD

**Issue by rbrouwer** [DewGew/Domoticz-Google-Assistant#319]
**Describe the bug:**  
Starting the current docker image will not work.

The docker container will continuously restart.

**Expected behavior:**  
I expect the docker container to install everything needed and start after that.

**Logs:**

```
dzga  | Traceback (most recent call last):
dzga    |   File "/__main__.py", line 4, in <module>
dzga    |     from server import *
dzga    |   File "/server.py", line 6, in <module>
dzga    |     from helpers import FILE_DIR
dzga    |   File "/helpers.py", line 14, in <module>
dzga    |     import requests
dzga    |   File "/usr/local/lib/pyenv/versions/3.7.3/lib/python3.7/site-packages/requests/__init__.py", line 43, in <module>
dzga    |     import urllib3
dzga    |   File "/usr/local/lib/pyenv/versions/3.7.3/lib/python3.7/site-packages/urllib3/__init__.py", line 39, in <module>
dzga    |     "urllib3 v2.0 only supports OpenSSL 1.1.1+, currently "
dzga    | ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with LibreSSL 3.0.2. See: https://github.com/urllib3/urllib3/issues/2168
```

**Desktop (please complete the following information):**
 - Domoticz version 2023.1 (build 15112)
 - Dzga version V.1.23.2
 - Python Version 3.7

**Smartphone (please complete the following information):**
 - Device: Desktop

**Comment by cvc90** [comment]
I had everything working correctly, when updating the docker it gives me the same error.

**Comment by DewGew** [comment]
I don't use docker. I will need some help fixing this issue.

**Comment by rbrouwer** [comment]
@DewGew, it is not limited to docker, but it will most likely slow up there.

I believe one of your [requirements](https://github.com/DewGew/Domoticz-Google-Assistant/blob/master/requirements/pip-requirements.txt) is "urllib3>=1.25.7", which [released version 2.0](https://github.com/urllib3/urllib3/releases/tag/2.0.0) last week. This is likely what triggered this error to happen.

A quick fix would likely be limiting to urllib3 < 2 and monitor [this issue](https://github.com/urllib3/urllib3/issues/2168) as well.

Also the docker images are based on [alpine-python](https://github.com/jfloff/alpine-python), which sadly is still not really well maintained. It is still based on Alpine 3.11, which is old and already EoL since 2021-11-01. That's possibly why there is no OpenSSL 1.1.1+ support in that base image.

**Comment by rbrouwer** [comment]
For those really wanting their DZGA docker to work now, here is a workaround:

Download the [requirements file](https://raw.githubusercontent.com/DewGew/Domoticz-Google-Assistant/4ee9c89e742377054660f50b05d360fec8f8be35/requirements/pip-requirements.txt) and replace the line:
`urllib3>=1.25.7`
with the following line:
`urllib3>=1.25.7,<2`

Then adjust your docker to mount that file in /requirements.txt by adjusting the container. For docker compose, just could adjust the file to contain:
```
    volumes:
      - <path to adjusted requirements.txt file>:/requirements.txt:ro
```

The docker should work again. Of course this should be undone when this issue is resolved.

**Comment by cvc90** [comment]
I checked what you say and it didn't work for me, but after changing the line from urllib3>=1.25.7 to urllib3==1.25.7 in the requirements file, I was able to make it work!

> For those really wanting their DZGA docker to work now, here is a workaround:
> 
> Download the [requirements file](https://raw.githubusercontent.com/DewGew/Domoticz-Google-Assistant/4ee9c89e742377054660f50b05d360fec8f8be35/requirements/pip-requirements.txt) and replace the line: `urllib3>=1.25.7` with the following line: `urllib3>=1.25.7,<2`
> 
> Then adjust your docker to mount that file in /requirements.txt by adjusting the container. For docker compose, just adjust the file to contain:
> 
> ```
>     volumes:
>       - <path to adjusted requirements.txt file>:/requirements.txt:ro
> ```
> 
> The docker should work again. Of course this should be undone when this issue is resolved.

**Comment by DewGew** [comment]
Try latsest beta, test if its working..

**Comment by rbrouwer** [comment]
I believe your commit/fix will not work:

You've got:
`urllib3>=1.26,<3`
, which would allow urllib3 version _**2**_ to be used/installed, which will not work within your docker.

It should be
`urllib3>=1.26,<2`

**Comment by cvc90** [comment]
The new version still doesn't work. As you can see in the image, it continues to download the version "urllib3-2.0.2-py3-none-any.whl", modifying the requirements file, it continues to work correctly with the new version DZGA v1.23.6.

![image](https://user-images.githubusercontent.com/76731844/236787547-93d83011-2c1c-483c-8cd7-82dfc901ea7e.png)

**Comment by DewGew** [comment]
> The new version still doesn't work. As you can see in the image, it continues downloading the version "urllib3-2.0.2-py3-none-any.whl".
> 
> ![image](https://user-images.githubusercontent.com/76731844/236787547-93d83011-2c1c-483c-8cd7-82dfc901ea7e.png)
> 
> Modifying the requirements file as @rbrouwer comments with the option urllib3>=1.26,<2 will work correctly with the new version DZGA v1.23.6.
> 
> ![image](https://user-images.githubusercontent.com/76731844/236789018-18336e74-2dc9-47c5-9db8-9fcd5a84428e.png) ![image](https://user-images.githubusercontent.com/76731844/236789645-0883294b-69fd-4d50-9aef-7f108bda3e26.png)

Changed  to `urllib>=1.26,<2` pip-requrement.txt

**Comment by cvc90** [comment]
I confirm that the latest version DZGA v1.23.7 in Docker works correctly.

![image](https://github.com/DewGew/Domoticz-Google-Assistant/assets/76731844/a920a0f5-5ab7-4a9d-9bc5-921a5316a05a)
