### ISSUE TITLE
ERROR - UNABLE TO EXECUTE ACTION.DEVICES.COMMANDS.ONOFF FOR GROUP8. ALREADY IN STATE

### ISSUE THREAD

**Issue by cvc90** [DewGew/Domoticz-Google-Assistant#320]
Hello, every time I try to turn on a group/scene an error occurs that it is already on even if the group/scene is off, if I look at it from the google home app I see that the scenes/groups are always on even if I turn them off, how can I fix this bug? Thank you.

**Logs:**
ERROR - UNABLE TO EXECUTE ACTION.DEVICES.COMMANDS.ONOFF FOR GROUP8. ALREADY IN STATE

**Comment by DewGew** [comment]
I have the same issue. Can't find whats wrong yet...

**Comment by cvc90** [comment]
When you can update the Docker version, to check if the bugs have been fixed, thanks!
