### ISSUE TITLE
change API command to correct command for Domoticz Version: 2023.2

### ISSUE THREAD

**Issue by TommyZ1234** [DewGew/Domoticz-Google-Assistant#336]
since update to Domoticz Version: 2023.2
logging in domoticz says:
[WebServer] Deprecated RType (devices) for API request. Handled via fallback (getdevices), please use correct API Command!
DZGA still works awesome, but creates a lot of logging in Domoticz

**Comment by DewGew** [comment]
> since update to Domoticz Version: 2023.2
> 
> logging in domoticz says:
> 
> [WebServer] Deprecated RType (devices) for API request. Handled via fallback (getdevices), please use correct API Command!
> 
> DZGA still works awesome, but creates a lot of logging in Domoticz

There is already a PR for this issue.

**Comment by TommyZ1234** [comment]
> > since update to Domoticz Version: 2023.2
> > logging in domoticz says:
> > [WebServer] Deprecated RType (devices) for API request. Handled via fallback (getdevices), please use correct API Command!
> > DZGA still works awesome, but creates a lot of logging in Domoticz
> 
> There is already a PR for this issue.

OK , sorry and thanks

**Comment by TommyZ1234** [comment]
Thank you for your help
