### ISSUE TITLE
Selector Switches not working with GA commands

### ISSUE THREAD

**Issue by Wwilcz2** [DewGew/Domoticz-Google-Assistant#340]
When trying to command selector switches with GA commands, like "Set [device nickname] to 20", I get a reply "Sorry, it looks like this device hasn't been set up yet. You can do that in Assistant settings.". Testing this command in the Actions simulator also doesn't work.

All other device types work as expected, both when using the phone and in Actions simulator.

**Comment by DewGew** [comment]
does your selector levels have "20" as name?

**Comment by Wwilcz2** [comment]
Theese are my settings:

![Screenshot_20230826_133941_Chrome](https://github.com/DewGew/Domoticz-Google-Assistant/assets/84280217/52169dfa-cead-448c-9999-5e0efd0d0c01)

**Comment by DewGew** [comment]
Try remove % or write percent in your language
