### ISSUE TITLE
Password options

### ISSUE THREAD

**Issue by jpvaneijk** [DewGew/Domoticz-Google-Assistant#341]
Hi all,

I have just successfully installed DZGA. 
My Google password - as well as the login credentials of many devices in my home - have a password that includes an & character.
In the configuration this & character does not seem to work because you cannot log into the user interface if there is an & character embedded in the password.

Is it possible to modify the password manager to allow the use of an & character? Too many changes have to be made at home otherwise.

Thanx in @vance

**Comment by DewGew** [comment]
Why? its a separete user to DZGA? its not the same user as in domoticz.
