### ISSUE TITLE
exec /usr/local/bin/python3: exec format error

### ISSUE THREAD

**Issue by MikeZMssl** [DewGew/Domoticz-Google-Assistant#343]
**Describe the bug:**  
I am trying to use your tool, but cannot seems to get the container running
I have a raspberry PI 4B running on ubuntu, and am trying to start the container using docker-compase.yml

However, the container seems not to be created
Would prefer to use the docker-compose.yml and not the git-clone option ? 

docker ps :  Restarting (1) 7 seconds ago 
docker logs DZGA : 
exec /usr/local/bin/python3: exec format error
exec /usr/local/bin/python3: exec format error
exec /usr/local/bin/python3: exec format error
exec /usr/local/bin/python3: exec format error
exec /usr/local/bin/python3: exec format error
exec /usr/local/bin/python3: exec format error
exec /usr/local/bin/python3: exec format error
exec /usr/local/bin/python3: exec format error
exec /usr/local/bin/python3: exec format error
exec /usr/local/bin/python3: exec format error
exec /usr/local/bin/python3: exec format error
exec /usr/local/bin/python3: exec format error
exec /usr/local/bin/python3: exec format error
exec /usr/local/bin/python3: exec format error
exec /usr/local/bin/python3: exec format error
exec /usr/local/bin/python3: exec format error
exec /usr/local/bin/python3: exec format error
exec /usr/local/bin/python3: exec format error
exec /usr/local/bin/python3: exec format error
exec /usr/local/bin/python3: exec format error
exec /usr/local/bin/python3: exec format error
exec /usr/local/bin/python3: exec format error
exec /usr/local/bin/python3: exec format error
exec /usr/local/bin/python3: exec format error

My configutation (have tried 2 different approaches) (the version and service part are included in top of file ; the yml file is used to create multuple containers) : 

  dz-googleassistant:
    image: dewgew/domoticz-google-assistant
    container_name: DZGA
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    ports:
      - 3030:3030
    volumes:
      - ./Domoticz-Google-Assistant/config:/config
    restart: unless-stopped
	
  dz-googleassistant:
    image: dewgew/domoticz-google-assistant
    container_name: DZGA
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 3030:3030
    volumes:
      - ./Domoticz-Google-Assistant/config:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

**Expected behavior:**  
A running container

**Logs:**
exec /usr/local/bin/python3: exec format error

```
Paste the dzga logs here.
not running

**Desktop (please complete the following information):**
 - Domoticz version <2023 2 build 19efd039c>
 - Dzga version <image dewgez/domoticz-google-assistant>
 - Python Version <within container ; not starting >

**Smartphone (please complete the following information):**
 - Device: <!-- e.g. iPhone6 -->

**Additional context, screenshot:**  
<!-- Add any other context or screenshot about the problem here. -->

**Comment by DewGew** [comment]
cd /home/${USER}
git clone https://github.com/DewGew/Domoticz-Google-Assistant  --single-branch
docker-compose -f /home/${USER}/Domoticz-Google-Assistant/docker-compose.yaml up -d
