### ISSUE TITLE
Notifications of type Doorbell not sent to Google Home speakers, SmokeDetector works

### ISSUE THREAD

**Issue by thijsniehof** [DewGew/Domoticz-Google-Assistant#345]
**Describe the bug:**  
When trying to setup sending notifications on pressing the doorbell to google home speakers, the doorbell doesn't show up in the Google Home app.
A Smoke detector does show up, and can be configured to play notifications from within the Home app.

**Expected behavior:**  
Doorbell showing up in the Home app, so notifications can be configured.

**Logs:**
ERROR - Something went wrong, check your notification settings

**Desktop (please complete the following information):**
 - Domoticz version 2023.2
 - Dzga version 1.23.10
 - Python Version 3.7.3
 - running DZGA in Docker container, using https://hub.docker.com/r/dewgew/domoticz-google-assistant

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6 Pro

**Additional context, screenshot:**  
HTTP notifications test is working, confirmation appears in DZGA log
Real or dummy-switch doorbell (type doorbell) doesn't work: does not show up in Home app, when pressing the button a log entry appears: ERROR - Something went wrong, check your notification settings
Dummy switch of type Smoke Detector works, I get notifications via Home speakers

**Comment by rezzalex** [comment]
I have recently a doorbell device in DZ, that is true that I have never see any doorbell showing-up in the Google Home app.
never checked the logs, but I will

**Comment by thijsniehof** [comment]
the only thing I can see in the logs is the error: Something went wrong, check your notification settings.
But because the dummy smoke detector does work, it tells me that the notification settings are correct.
If I delete the notification settings, DZGA still sees the doorbell type and smokedetector type in it's devices list.. the Google Home app only sees the smokedetector, that tells me that the notification setup is not the problem.

**Comment by rezzalex** [comment]
where are the notification settings you are talking about ?

**Comment by rezzalex** [comment]
For me, yes

**Comment by DewGew** [comment]
but not in Google Assistant?

**Comment by thijsniehof** [comment]
> where are the notification settings you are talking about ?

In Domoticz: Setup --> Settings --> Notifications

**Comment by thijsniehof** [comment]
> Does the doorbell shows up in devices tab in the UI?
> 
> > the only thing I can see in the logs is the error: Something went wrong, check your notification settings. But because the dummy smoke detector does work, it tells me that the notification settings are correct. If I delete the notification settings, DZGA still sees the doorbell type and smokedetector type in it's devices list.. the Google Home app only sees the smokedetector, that tells me that the notification setup is not the problem.
> 
> Does the doorbell shows up in devices tab in the UI?

In DZGA in the devices list yes, for both doorbell and smokedetector.
In google home app, only smokedetector shows up.

**Comment by DewGew** [comment]
I made some changes on doorbell, try latest master

**Comment by thijsniehof** [comment]
> I made some changes on doorbell, try latest master

Got the new docker image, but unfortunately, it still doesn't show up..
testing it gives the same error:
Something went wrong, check your notification settings.

The smoke detector still works correctly

**Comment by rezzalex** [comment]
I confirm, I had doubts previously because I used Scrypted,  which can create a doorbell device (and a cam) on Google Home as well. I have removed the link between GHome and Scryted, updated to the latest  DZGA image and still don't see my DZ doorbell device in GHome, and I can see it in DZGA UI list

**Comment by DewGew** [comment]
Try enable camera and add a camara url in config assigned to doorbell idx. if you dont have a doorbell camera you can use "https://content.jwplatform.com/manifests/yp34SRmf.m3u8" instead.

**Comment by thijsniehof** [comment]
> Try enable camera and add a camara url in config assigned to doorbell idx. if you dont have a doorbell camera you can use "https://content.jwplatform.com/manifests/yp34SRmf.m3u8" instead.

Unfortunately no difference..

**Comment by rezzalex** [comment]
@DewGew , I think I saw that the doorbell thing is to be used with a dz switch attached to a cam, does it change anything that the dz device is a "doorbell" device type ?
