### ISSUE TITLE
Make contextroot configurable

### ISSUE THREAD

**Issue by ronsmits** [DewGew/Domoticz-Google-Assistant#35]
when you have one "gateway server" like nginx or apache that proxies from the big bad internet to the safety of the internal network. One of the biggest challenges is setting up all forwarding.

DGA forces to have the context root at /. Can this be changed into a configuration?

**Comment by DewGew** [comment]
You want to spilt the files to 2 folder? 1 for http.server then 1 for smarthome?

**Comment by ronsmits** [comment]
I use nginx as gatekeeper so curently I have the following port forwardings:
notmydomain.com/otg -> to an internal owntrack server
notmydomain.com/seafile -> internal seafile server
 notmydomain.com/ -> domoticz-google-assistent.

I would love to be able to do "notmydomain.com/dga" -> domoticz-google-assistant.

I tried to solve it with port-forwarding and rewriting. but I could not get it to work

**Comment by DewGew** [comment]
This i just a simple http server. But you already have nginx, make a reverse proxy to dga. I do like that on my synology
