### ISSUE TITLE
Duplicate Domoticz requests

### ISSUE THREAD

**Issue by JordiBoerman** [DewGew/Domoticz-Google-Assistant#39]
Sadly I'm new to Git and currently have no time to sort it al out. I had BIG issues with DZGA performing duplicate requests to Domoticz. Took me ages to figure out where it came from (GActions, Proxy, Domoticz, or somewhere in the DZGA code), but I found it. Probably every single user has this issue, but it feels I'm the only one who noticed and had issues with it (due to IR).

The issue is on line 431 of smarthome.py:

`print(json.dumps(self.smarthome_process(message, token), indent=2, sort_keys=False))`

In this line the smarthome_process call is made a second time. It can be fixed by replacing with:

`print(json.dumps(response, indent=2, sort_keys=False))`

I hope it helps.

**Comment by DewGew** [comment]
Where do you have the duplicate request? This code above just Prints in the terminal.

**Comment by JordiBoerman** [comment]
I had it all the time... In line 421 the same call is made;

`response = self.smarthome_process(message, token)`

**Comment by DewGew** [comment]
I mean Line 431 only writes in terminal. Does not request anyting to domotics

**Comment by DewGew** [comment]
I've updated smarthome.py

**Comment by JordiBoerman** [comment]
> I mean Line 431 only writes in terminal. Does not request anyting from or to Domoticz. You can simply delete this line.
> 
> Anyway thanks for pointing that out 👍

What I meant:

Line 421:
response = self.smarthome_process(message, token)

Line 431:
print(json.dumps(self.smarthome_process(message, token), indent=2, sort_keys=False))

Both lines in the same function made a call to `self.smarthome_process(message, token)` which caused a duplicate request to Domoticz.
