### ISSUE TITLE
WW/CW bulb apears wrong and color temperature does not seem to work

### ISSUE THREAD

**Issue by brammp** [DewGew/Domoticz-Google-Assistant#44]
Hi,

I have a WW/CW and RGBW Bulb connected in Domoticz.
But in google assistant sees the  WW/CW bulb as a RGBW bulb.
And for both bulbs the color temperature options in the Color list in google assistant does not seem to work.

**Comment by DewGew** [comment]
I noticed this before I dont have any warm white or cold white bulbs my self. 
Need some rewriting for colorsettings trait. Improve Color temperature feature.

**Comment by brammp** [comment]
Thanks for the quick response,
The colors seems to be inverted if i selct cold white i get warm white and vice versa

**Comment by brammp** [comment]
It works like intended,
Thanks for the greate work,
