### ISSUE TITLE
Milights issue

### ISSUE THREAD

**Issue by DewGew** [DewGew/Domoticz-Google-Assistant#49]
There is one issue with my milight lights. I have them setup as a switch in domoticz and my milights appear in google home but with the following error:

```
Error handling message {'requestId': '1786981529328158506', 'inputs': [{'context': {'locale_country': 'NL', 'locale_language': 'nl'}, 'intent': 'action.devices.EXECUTE', 'payload': {'commands': [{'devices': [{'id': 'ColorSwitch21'}], 'execution': [{'params': {'on': False}, 'command': 'action.devices.commands.OnOff'}]}]}}]}: {'errorCode': 'unknownError'}
127.0.0.1 - - [01/Dec/2019 15:32:07] "POST /smarthome HTTP/1.1" 200 -
Response: {
  "requestId": "1786981529328158506",
  "payload": {
    "errorCode": "unknownError"
  }
}

This is the milight when i sync devices:

      {
        "willReportState": false,
        "deviceInfo": {
          "manufacturer": "milight"
        },
        "traits": [
          "action.devices.traits.OnOff",
          "action.devices.traits.Brightness",
          "action.devices.traits.ColorSetting"
        ],
        "attributes": {
          "colorTemperatureRange": {
            "temperatureMinK": 1700,
            "temperatureMaxK": 6500
          },
          "colorModel": "rgb"
        },
        "name": {
          "name": "Slaapkamer Lamp"
        },
        "type": "action.devices.types.LIGHT",
        "id": "ColorSwitch21"
      }
```
I can still use my voice commands to turn on/off the light but google home mini says there is an error each time. The google home app says it is not responding.

[Forum thread](https://www.domoticz.com/forum/viewtopic.php?f=69&t=27244&p=229867#p229814)

**Comment by Jochem22** [comment]
Device information:

{
   "ActTime" : 1575308652,
   "AstrTwilightEnd" : "18:35",
   "AstrTwilightStart" : "06:24",
   "CivTwilightEnd" : "17:11",
   "CivTwilightStart" : "07:49",
   "DayLength" : "08:02",
   "NautTwilightEnd" : "17:54",
   "NautTwilightStart" : "07:05",
   "ServerTime" : "2019-12-02 18:44:12",
   "SunAtSouth" : "12:30",
   "Sunrise" : "08:29",
   "Sunset" : "16:31",
   "app_version" : "4.10717",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "Off",
         "Description" : "",
         "DimmerType" : "none",
         "Favorite" : 1,
         "HardwareID" : 4,
         "HardwareName" : "milight",
         "HardwareType" : "Limitless/AppLamp/Mi Light with LAN/WiFi interface",
         "HardwareTypeVal" : 22,
         "HaveDimmer" : true,
         "HaveGroupCmd" : false,
         "HaveTimeout" : false,
         "ID" : "1",
         "Image" : "Light",
         "IsSubDevice" : false,
         "LastUpdate" : "2019-12-02 08:02:24",
         "Level" : 71,
         "LevelInt" : 71,
         "MaxDimLevel" : 100,
         "Name" : "Slaapkamer Lamp",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "RGBWW",
         "SwitchType" : "On/Off",
         "SwitchTypeVal" : 0,
         "Timers" : "true",
         "Type" : "Color Switch",
         "TypeImg" : "lightbulb",
         "Unit" : 2,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "21"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}

**Comment by DewGew** [comment]
Is it possible to dim?

**Comment by Jochem22** [comment]
Yes it's RGBW and dimmable.

**Comment by DewGew** [comment]
Ok, i think you have to set it as dimmer in Domoticz, it says above its an on/ off switch only

**Comment by Jochem22** [comment]
Thnx that is the fix :)

`127.0.0.1 - - [02/Dec/2019 20:06:29] "POST /smarthome HTTP/1.1" 200 -
Response: {
  "requestId": "8412433874412423770",
  "payload": {
    "commands": [
      {
        "status": "SUCCESS",
        "ids": [
          "ColorSwitch21"
        ],
        "states": {
          "brightness": 71,
          "on": false,
          "color": {
            "temperatureK": 6502
          },
          "online": true
        }
      }
    ]
  }
}
`
