### ISSUE TITLE
Reverse proxy (apache2) not working properly 

### ISSUE THREAD

**Issue by ficueu** [DewGew/Domoticz-Google-Assistant#52]
Hello, I'm tryin to redirect from _my.domain:3030_ to _my.domain/asssistant/_ in apache2:

```
  ProxyPass "/assistant/" "http://127.0.0.1:3030/"
  ProxyPassReverse "/assistant/" "http://127.0.0.1:3030/"
```
and I can see login page at _my.domain/assistant/login_ but while trying to click sign in it redirect me to _my.domain/login_ - probably code only support main "catalog" _example.domain/_, it not working if there is more levels: _example.domain/googleassistant/_ etc.

Is possible to fix it? Or only way is use ngrock/port redirecting?

**Comment by DewGew** [comment]
What happens if you go to _my.domain/assistant/settings_?

**Comment by ficueu** [comment]
_my.domain/assistant/settings_ gives _my.domain/login?redirect_uri=/settings_.

**Comment by DewGew** [comment]
It looks like it should work

**Comment by ficueu** [comment]
If I mannualy add **/assistant/** _to my.domain/login?redirect_uri=/settings_ then I see login page. Without  **/assistant/** there is not found error.

**Comment by ficueu** [comment]
I tried to fix it in code but this is too hard for me.

**Comment by DewGew** [comment]
I found some you can test:
https://stackoverflow.com/questions/26848945/exclude-an-alias-from-virtualhost-proxypass
https://serverfault.com/questions/746698/apache-virtual-hosts-redirect-proxypass-and-alias
https://serverfault.com/questions/497541/virtual-host-on-a-sub-directory/497582

**Comment by DewGew** [comment]
Same as #35

**Comment by DewGew** [comment]
Did you get this to work?

**Comment by ficueu** [comment]
No, I'm not found any worked solution. After authenticated by ngrok, the address was set to my reverse proxy. On reverse proxy, controlling devices working great but authentication or settings page didn't work.

**Comment by DewGew** [comment]
Are you running master or beta?

**Comment by DewGew** [comment]
You can try to change https://github.com/DewGew/Domoticz-Google-Assistant/blob/c614e96a6feb149d2d91ac7107765f323a39f6f4/server.py#L80
to

`self.send_header('Location', '/assistant' + path)`

**Comment by Reneke43** [comment]
Thanks tizzen33. Removing the slashes also makes my Synology reverse proxy function.
Also enabled web socket in the headers.
