### ISSUE TITLE
Update in GUI not correct

### ISSUE THREAD

**Issue by SargonofAssyria** [DewGew/Domoticz-Google-Assistant#55]
I just did a pull on the beta v. 1.3.5 and everything went fine.
I did a restart of the server and a sync.
The version is shown in 'const.py' on the header in the GUI.
At the bottom of the GUI it shows that I am on version v.1.3.5
But the 'Update' button is visible and clickable.
I think that the button should be disabled or gone.

**Comment by DewGew** [comment]
You are on beta. That why it shows. The update check against master.

**Comment by DewGew** [comment]
I change to check from correct branch . Try latetest beta (v.1.3.6)

**Comment by SargonofAssyria** [comment]
I did a 'git pull' manually and got into problems.
When I manually start the service I got this.
`Successfully installed GitPython-3.0.5 gitdb2-2.0.6 smmap2-2.0.5
Traceback (most recent call last):
  File "/home/pi/Domoticz-Google-Assistant/smarthome.py", line 30, in <module>
    import git
ImportError: No module named 'git'
`
