### ISSUE TITLE
Update button does not show.

### ISSUE THREAD

**Issue by SargonofAssyria** [DewGew/Domoticz-Google-Assistant#59]
I am on version 1.3.6 (present in const.py and the GUI) but the button in the GUI does not show.
I saw that both master and beta are currently on 1.3.7.
I use Chrome and cleared the cache.

**Comment by DewGew** [comment]
Restart server and it will show. Only checks at startup.

**Comment by SargonofAssyria** [comment]
Indeed that worked. But should the version change not be vissible after a GUI (re)start?
Normally I do not restart a service.

**Comment by DewGew** [comment]
I havent found any solution for this yet

**Comment by SargonofAssyria** [comment]
Oke, hope in time you will.

**Comment by DewGew** [comment]
Should be working now

**Comment by SargonofAssyria** [comment]
Updated from 1.3.7 with button to 1.3.8 Everything went fine.
