### ISSUE TITLE
Version 1.4.0 crash of service at start.

### ISSUE THREAD

**Issue by SargonofAssyria** [DewGew/Domoticz-Google-Assistant#63]
I update DGA on the webgui and also tried normal git pull to version 1.4.0
The system crashes immediately after start.
No hits in the log file with DEBUG On.
Went back to 1.3.9. and everything is fine.

**Comment by DewGew** [comment]
Thanks for reporting. There was a typo. I have fixed it now, please try update again.

**Comment by SargonofAssyria** [comment]
Yes that did the trick. Problem solved.
