### ISSUE TITLE
Roller shutter direction changed.

### ISSUE THREAD

**Issue by SargonofAssyria** [DewGew/Domoticz-Google-Assistant#64]
I might be mistaken, but a few versions back my roller shutters worked normally with voice command.
Commands like Up and Down worked normally but the action in version 1.4.3 is now reversed.
Can that be changed some where or is there something changed in code?
The "Open" and "Close" work correctly.

**Comment by DewGew** [comment]
maybe its this one #54 I havent tested this myself.

**Comment by SargonofAssyria** [comment]
I changed direction and then both work the opposite. So I have to learn just to use "Open" and "Close"
in my commands to Google. To me "Open" and "Up" are to same, but not Google. Strange.
