### ISSUE TITLE
Failure to sync devices

### ISSUE THREAD

**Issue by jsiegmund** [DewGew/Domoticz-Google-Assistant#66]
Running off of the latest beta version I'm getting the following when trying to sync up with Google: 

> https://homegraph.googleapis.com:443 "POST /v1/devices:requestSync HTTP/1.1" 404 None

The UI is giving me: 

> Page not found!: 404 Client Error: Not Found for url:  https://homegraph.googleapis.com/v1/devices:requestSync

I'm using `smart-home-key.json` which I downloaded from Google and as far as I can see everything seems to be set-up correctly. What might I be missing here? 

PS: I also tried the master branch using the `Homegraph_API_Key` setting, but that gives me: 

> Homegraph api key not valid!

I'm quite sure the key is correct though, I've copy/pasted it from the Google console a couple of times now.

**Comment by jsiegmund** [comment]
Maybe useful as additional background info, I updated an old version to the most recent version today, which broke things. I can't control anything any more. 

Checking the logs it seems it thinks all devices are offline: 

```
2019-12-23 21:12:08 - INFO - Response {
  "payload": {
    "devices": {
      "Light/Switch216": {
        "online": false
      }
    }
  },
  "requestId": "9978847179539540631"
}
```

Connection to domoticz seems to be fine though, since the log is neatly listing all of my switches and scenes.

**Comment by DewGew** [comment]
Regenarate new api key and json file. According to your logg it seems that dzga is not getting any info from your domoticz. Check your connection first.

**Comment by jsiegmund** [comment]
I tried regenerating, same result. Also I do not think that the connection to domoticz is an issue, following lines are logged when the service starts: 

```
2019-12-24 16:18:09 - DEBUG - Connecting to Domoticz on http://192.168.1.175:80
2019-12-24 16:18:09 - DEBUG - Starting new HTTP connection (1): 192.168.1.175:80
2019-12-24 16:18:09 - DEBUG - http://192.168.1.175:80 "GET /json.htm?type=command&param=addlogmessage&message=Connected%20to%20Google%20Assistant%20with%20DZGA%20v1.4.3 HTTP/1.1" 200 53
```

It also outputs a list of all of my switches and scenes.

In Domoticz log I see: 

```2019-12-24 16:18:09.988 Status: Connected to Google Assistant with DZGA v1.4.3```

**Comment by jsiegmund** [comment]
Additional info: I started a browser debug and when I click the sync button this ends up in a 404 being returned from the /settings url. Response is: 

> Page not found!: 404 Client Error: Not Found for url: https://homegraph.googleapis.com/v1/devices:requestSync

**Comment by DewGew** [comment]
Check your credentials also and , important restart test in Actions On Google

**Comment by DewGew** [comment]
Still have the same issue?

**Comment by jsiegmund** [comment]
Yeah nothing changed, didn't have a lot of time due to the holidays :) 

I can ping the google servers from the device itself so internet access should not be an issue. It's not using any other ports than what I default I assume, otherwise my firewall might be an issue. 

Here's some more logging when I try to execute an action via Google. Something happens at least, so that proves that Google is able to contact the DZGA running on my Pi. 

```
Starting new HTTP connection (1): 192.168.1.175:80
http://192.168.1.175:80 "GET /json.htm?type=settings HTTP/1.1" 200 1511
Host: domoticz-gh.repsaj.nl
X-Real-IP: <removed>
X-Forwarded-For: <removed>
X-Forwarded-Proto: https
Connection: close
Content-Length: 275
Content-Type: application/json;charset=UTF-8
Google-Assistant-API-Version: v1
Authorization: Bearer <removed>
User-Agent: Mozilla/5.0 (compatible; Google-Cloud-Functions/2.1; +http://www.goo                                                                                                                                                             gle.com/bot.html)
Accept-Encoding: gzip,deflate,br


Request {
  "requestId": "5030143157272526476",
  "inputs": [
    {
      "context": {
        "locale_country": "US",
        "locale_language": "en"
      },
      "intent": "action.devices.EXECUTE",
      "payload": {
        "commands": [
          {
            "execution": [
              {
                "command": "action.devices.commands.OnOff",
                "params": {
                  "on": true
                }
              }
            ],
            "devices": [
              {
                "id": "Media462"
              }
            ]
          }
        ]
      }
    }
  ]
}
'NoneType' object has no attribute 'report_state'
Error handling message {'requestId': '5030143157272526476', 'inputs': [{'context                                                                                                                                                             ': {'locale_country': 'US', 'locale_language': 'en'}, 'intent': 'action.devices.                                                                                                                                                             EXECUTE', 'payload': {'commands': [{'execution': [{'command': 'action.devices.co                                                                                                                                                             mmands.OnOff', 'params': {'on': True}}], 'devices': [{'id': 'Media462'}]}]}}]}:                                                                                                                                                              {'errorCode': 'unknownError'}
192.168.0.100 - - [30/Dec/2019 10:37:05] "POST /smarthome HTTP/1.1" 200 -
Response {
  "requestId": "5030143157272526476",
  "payload": {
    "errorCode": "unknownError"
  }
}
```

**Comment by DewGew** [comment]
Rename or remove json file and remove homegraph_API_key. The sync your devices with voice then put logs here.

**Comment by jsiegmund** [comment]
I'm not 100% clear on the instructions. I renamed the json (`smart-home-key.json`) file to .back and within my config.yaml I didn't have an entry for `homegraph_API_key` to begin with. When I now press the sync button in the UI this gives me: 

`Add Homegraph api key or a Homegraph Service Account json file to sync devices here!`

Which seems to make sense. What am I missing?

**Comment by jsiegmund** [comment]
Not sure if this might be related, but I have the feeling that the Python install on this RPi is not in a great state. For example I need to explicitly call `python3.5` to get things to run, `python` seems to point to 3.4 and I'm not entirely sure why and how I might change that. But again: i have no clue whether this is actually related or not.

**Comment by DewGew** [comment]
You have to sync with voice. Open google assistant and say ”sync my devices”

**Comment by jsiegmund** [comment]
Got it. Logs look like this: 

```
2020-01-02 11:37:16 - DEBUG - Starting new HTTPS connection (1): accounts.google.com:443
2020-01-02 11:37:17 - DEBUG - https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None
2020-01-02 11:37:17 - DEBUG - Starting new HTTPS connection (1): homegraph.googleapis.com:443
2020-01-02 11:37:17 - DEBUG - https://homegraph.googleapis.com:443 "POST /v1/devices:reportStateAndNotification HTTP/1.1" 404 None
2
```

Note the 404 at the end. Next it

**Comment by jsiegmund** [comment]
Sorry I hit enter where I didn't want to... let me update the previous comment and this one is only for reopening.

**Comment by DewGew** [comment]
There must be something with your setup. back up your config.yaml then delete Domoticz-Google-Assistant folder.
Then run new install with `bash <(curl -s https://raw.githubusercontent.com/DewGew/dzga-installer/master/install.sh)` . Choose 'Yes' to install development branch. This will update your rpi and python, install required packages and then install dzga in a virtual enviroment.
After install is finished goto ui and add your configuration. (Dont copy config.yaml in winSCP or somthing just update in ui in case there is some missing in your config)

**Comment by jsiegmund** [comment]
I'm getting more and more confused here, haha. I removed the entire folder and used the install script to install the latest beta version. Updated the configuration and restarted the service. Now when I check the logs I see the following: 

```
========
Started DZGA v1.4.6 server at port 3030

   Visit http://localhost:3030/settings to access the user interface

=========
Visit the Actions on Google console at http://console.actions.google.com
Under Develop section, replace the fulfillment URL in Actions with:
   https://[YOUR REVERSE PROXY URL]/smarthome

In Account linking, set the Authorization URL to:
   https://[YOUR REVERSE PROXY URL]/oauth

Then set the Token URL to:
   https://[YOUR REVERSE PROXY URL]/token

Finally press 'SAVE' and then 'TEST' button
=======
(Press CTRL+C to stop server)
Starting new HTTP connection (1): 127.0.0.1:80
http://127.0.0.1:80 "GET /json.htm?type=devices&plan=0&filter=all&used=true HTTP/1.1" 200 5932
(Alles verlicht, 14, Scene, Mixed, None, True)
(Eetkamer + Keuken AAN/UIT, 10, Group, Off, None, True)
(Huiskamer AAN/UIT, 11, Group, Mixed, None, True)
(Keuken AAN/UIT, 13, Group, Off, None, True)
(Eetkamer, 15, Group, Off, None, True)
(Huiskamer, 22, Scene, Off, None, True)
(Huiskamer - Film, 9, Scene, Off, None, True)
(Huiskamer - Film Pauze, 23, Scene, Off, None, True)
....
```

There's a full list of devices and scenes there (as there already was before btw). But when I log into the settings UI it says `Connection to Domoticz refused! Check configuration.` and the list of devices is emtpy. It's almost as if it can't parse / handle the valid response it gets from Domoticz. As before, Domoticz log is showing: 

```2020-01-02 17:00:57.289 Status: Connected to Google Assistant with DZGA v1.4.6```

**Comment by jsiegmund** [comment]
Hmmm now that I look at that list, it's long but these are definitely not all switches / scenes that I have. So maybe it is failing on processing the response and the UI simply interprets that error as if it can't reach Domoticz? I've got a few hidden switches having $-signs in their names for instance, maybe that messes up things?

**Comment by DewGew** [comment]
There can be an issue with special characters try sync without your hidden devices.

**Comment by jsiegmund** [comment]
I changed the name on those to remove the special characters, didn't make a difference. And as shown above the device on which it might (?) fail doesn't have any special characters. It is a virtual switch, maybe that is something?

**Comment by DewGew** [comment]
What domoticz version are you using? I use beta

**Comment by dutch2005** [comment]
Not to hijack this topic, but I have the same issue...

---

192.168.1.14 - - [02/Jan/2020 22:47:08] "POST /settings HTTP/1.1" 200 -
192.168.1.14 - - [02/Jan/2020 22:48:05] "GET /smarthome HTTP/1.1" 500 -
192.168.1.14 - - [02/Jan/2020 22:48:09] "GET / HTTP/1.1" 404 -
192.168.1.14 - - [02/Jan/2020 22:48:14] "GET /settings HTTP/1.1" 200 -
Backup saved
192.168.1.14 - - [02/Jan/2020 23:00:03] "POST /settings HTTP/1.1" 200 -
{
  "error": {
    "code": 404,
    "message": "Requested entity was not found.",
    "status": "NOT_FOUND"
  }
}

192.168.1.14 - - [02/Jan/2020 23:02:06] "POST /settings HTTP/1.1" 200 -
{
  "error": {
    "code": 404,
    "message": "Requested entity was not found.",
    "status": "NOT_FOUND"
  }
}

192.168.1.14 - - [02/Jan/2020 23:02:47] "POST /settings HTTP/1.1" 200 -
---

192.168.1.14 = nginx reverse proxy
Domoticz Version = 4.115900
Using the stable version of Domoticz-Google_assistant

**Comment by DewGew** [comment]
Try also not use a user account to connect to domoticz. Use an admin account

**Comment by DewGew** [comment]
I cant reproduce your issues. sorry. Send me your config.yaml and log file by email , you can change your personal credetials to something random.

**Comment by jsiegmund** [comment]
I'm using the admin account. And also running Domoticz beta. Do you have virtual switches in your setup?

**Comment by DewGew** [comment]
I have virtual devices

**Comment by jsiegmund** [comment]
I've redone the Device_Config and lower sections, that seems to have solved the issue connecting to Domoticz. So I now have my devices list in DZGA again but I still can't send commands via voice. I'm sending you my files via e-mail, stand-by....

**Comment by jsiegmund** [comment]
Hmm, still baffled but after redoing all the steps once again my devices now re-appeared in the Home app but not linked to a house any more. So I redid the entire linking process for all of them and now things are starting to work again. At the same time voice keeps complaining about not being able to connect to devices so it seems the old references are also still there. Maybe I'll just wait for a bit, seems like there's some background stuff going on.

**Comment by dutch2005** [comment]
> Hmm, still baffled but after redoing all the steps once again my devices now re-appeared in the Home app but not linked to a house any more. So I redid the entire linking process for all of them and now things are starting to work again. At the same time voice keeps complaining about not being able to connect to devices so it seems the old references are also still there. Maybe I'll just wait for a bit, seems like there's some background stuff going on.

So you made new keys and tried again?

**Comment by jsiegmund** [comment]
Yes, don't forget to also update the client / secret combination in Google itself. It works now, but literally every action replies that it could not access certain devices, I'm guessing the "old" ones from the previous set-up. So you might be better off creating completely new apps in Google as well and unliking your current application.

**Comment by DewGew** [comment]
For testing your own clientId and secret is not needed. You can set for example "sampleClient" and "sampleSecret" in Action on Google and same in config.yaml.

**Comment by SargonofAssyria** [comment]
I am using latest beta 1.4.8
Cannot sync devices anymore.
When I sync via UI I get: Page not found!: 400 Client Error: Bad Request for url: https://homegraph.googleapis.com/v1/devices:requestSync
I changed my API key and the corresponding smart-home-key.json and restarted the server but the problem remains. Also Google voice "Sync devices" give an error back, but does not state anything that there was an error syncing. When I try to sync by voice I do not find anything in the dzga.log.

**Comment by DewGew** [comment]
@SargonofAssyria Try Goto action on google and press Test button again,

**Comment by SargonofAssyria** [comment]
Yep! That did the trick. Why? I hope this is NOT often necessary!

**Comment by DewGew** [comment]
I don't now why. It happens sometimes. Not very often thou.

**Comment by jsiegmund** [comment]
Ok. So the main issue for me is definitely fixed, it's been working since. But with every voice action I get a "sorry, something went wrong" back from Google even though the actions seem to work OK. 

With every actions I see a block like this: 

```
2020-01-07 17:37:30 - DEBUG - Starting new HTTP connection (1): 127.0.0.1:80
2020-01-07 17:37:30 - DEBUG - http://127.0.0.1:80 "GET /json.htm?type=command&param=switchlight&idx=462&switchcmd=On HTTP/1.1" 200 47
2020-01-07 17:37:30 - DEBUG - Starting new HTTP connection (1): 127.0.0.1:80
2020-01-07 17:37:30 - DEBUG - http://127.0.0.1:80 "GET /json.htm?type=devices&rid=462 HTTP/1.1" 200 648
2020-01-07 17:37:30 - DEBUG - (Radio, 462, Light, On, None, True)
2020-01-07 17:37:31 - DEBUG - Starting new HTTPS connection (1): accounts.google.com:443
2020-01-07 17:37:32 - DEBUG - https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None
2020-01-07 17:37:32 - DEBUG - Starting new HTTPS connection (1): homegraph.googleapis.com:443
2020-01-07 17:37:32 - DEBUG - https://homegraph.googleapis.com:443 "POST /v1/devices:reportStateAndNotification HTTP/1.1" 404 None
2020-01-07 17:37:32 - ERROR - 404 Client Error: Not Found for url: https://homegraph.googleapis.com/v1/devices:reportStateAndNotification
2020-01-07 17:37:32 - INFO - Error handling message {'requestId': '12814072524766946115', 'inputs': [{'context': {'locale_language': 'en', 'locale_country': 'US'}, 'intent': 'action.devices.EXECUTE', 'payload': {'commands': [{'execution': [{'params': {'on': True}, 'command': 'action.devices.commands.OnOff'}], 'devices': [{'id': 'Light462'}]}]}}]}: {'errorCode': 'unknownError'}
2020-01-07 17:37:32 - INFO - Response {
  "requestId": "12814072524766946115",
  "payload": {
    "errorCode": "unknownError"
  }
}
```

Any ideas?

**Comment by DewGew** [comment]
Disable smart-home-key.json and try again see if you get same error

**Comment by jsiegmund** [comment]
Yep, renaming that file and restarting does indeed solve the issue. So what impact does that have?

**Comment by DewGew** [comment]
Hmm seems like you cant send request to homegraph. Not valid json or Something block your reguest.

**Comment by jsiegmund** [comment]
I tried syncing again and I see that request coming in in the logs. The last lines: 

```
2020-01-21 19:55:14 - DEBUG - Starting new HTTPS connection (1): homegraph.googleapis.com:443
2020-01-21 19:55:15 - DEBUG - https://homegraph.googleapis.com:443 "POST /v1/devices:reportStateAndNotification HTTP/1.1" 404 None
```

So reporting back fails again. Just to be absolutely sure: the client ID / secret that I configure in the actions console: those are the same as previously generated in the cloud API & services section, right? The ones which are also in the yaml config file under `ClientID` and `ClientSecret`?

**Comment by jsiegmund** [comment]
Unlinked the entire thing from Home, re-linked and re-added all devices to their rooms. Nothing changes. I'm lost.

**Comment by DewGew** [comment]
Clientid and clientsecret in config must match with actions on google console..

**Comment by jsiegmund** [comment]
Right. And those in turn come from the "Add Credentials" step where you generate them from Google Cloud Console API & Service page. I've redone it so many times now, I'm gonna give up.

**Comment by DewGew** [comment]
remove smart-home-key.json and try without that

**Comment by Jochem22** [comment]
Like @DewGew said. Make sure you use the correct project at Google Cloud Platform Console at the top left in the blue bar next to Google Cloud Platform. There is a drop down menu where you can choose your projects. I made the same mistake once.

**Comment by jsiegmund** [comment]
That's a very good addition, @Jochem22. That was exactly what my oversight was as well. Apparantly somewhere in the trying-to-get-it-to-work process I created a new project with a very similar name and I had the wrong one selected when exporting the key. I switched it over to the other one to try it and now the error is gone. Thanks a lot!
