### ISSUE TITLE
Temperature Conversion Fahrenheit / Celcius

### ISSUE THREAD

**Issue by j0nson** [DewGew/Domoticz-Google-Assistant#68]
I'm running DGA from source, pulled yesterday.

My Domoticz devices report temperature in Fahrenheit, but it seems that Google Home thinks the report is in Celsius, and converts to Fahrenheit. So, when my thermostat setpoint is 66f, Google Home reports the temperature as 150f (converting 66c to 150f). Here's a snippet from my DGA log:

> 2019-12-29 14:01:51 - INFO - Response: {
  "requestId": "12700150954660525955",
  "payload": {
    "devices": {
      "Temp119": {
        "online": true,
        "thermostatMode": "heat",
        "thermostatTemperatureAmbient": 66.0,
        "thermostatTemperatureSetpoint": 66.0
      }
    }
  }
}

And here's a screenshot from GH:
![Screenshot_20191229-091321](https://user-images.githubusercontent.com/3464138/71557947-814cd080-2a1b-11ea-9577-9bb44d52c6f5.png)

**Comment by DewGew** [comment]
Dzga fetches domoticz settings. Did set fahrenheit in domoticz?

**Comment by j0nson** [comment]
Yes, my domoticz is set to Fahrenheit, and dzga settings reports the device status correctly:
![Screenshot_20191229-201810](https://user-images.githubusercontent.com/3464138/71565097-ee428380-2a78-11ea-83ca-ddb06b1af5ad.png)

**Comment by DewGew** [comment]
I try to reproduce this..

**Comment by DewGew** [comment]
Try latest beta. Google uses celsius only for state query. I had to add a convert tool.

**Comment by j0nson** [comment]
I had some issues running the beta branch. I finally got it to run correctly, and got this error: "name 'units' is not defined", and google home reports the thermostat as offline. 
Here's the full log, with my server url redacted:

> 127.0.0.1 - - [01/Jan/2020 18:12:29] "GET /settings?code=f9299e202ce3462cbc9161a411a56c5f&state=undefined HTTP/1.1" 200 -
Request: {
  "inputs": [
    {
      "intent": "action.devices.QUERY",
      "payload": {
        "devices": [
          {
            "id": "Temp119"
          }
        ]
      }
    }
  ],
  "requestId": "8968117430731453033"
}
Starting new HTTP connection (1): [URL]
http://[URL]:[PORT] "GET /json.htm?type=devices&plan=0&filter=all&used=true HTTP/1.1" 200 4349
Starting new HTTP connection (1): [URL]
http://[URL]:[PORT] "GET /json.htm?type=settings HTTP/1.1" 200 1419
Starting new HTTP connection (1): [URL]
http://[URL]:[PORT] "GET /json.htm?type=devices&rid=119 HTTP/1.1" 200 601
Starting new HTTP connection (1): [URL]
http://[URL]:[PORT] "GET /json.htm?type=settings HTTP/1.1" 200 1419
name 'units' is not defined
Error handling message {'inputs': [{'intent': 'action.devices.QUERY', 'payload': {'devices': [{'id': 'Temp119'}]}}], 'requestId': '8968117430731453033'}: {'errorCode': 'unknownError'}
127.0.0.1 - - [01/Jan/2020 18:12:47] "POST /smarthome HTTP/1.1" 200 -
Response: {
  "requestId": "8968117430731453033",
  "payload": {
    "errorCode": "unknownError"
  }
}

Also, the error that was stopping me from running the beta fully is this, even through I have "Check for Updates = false in the config file. This error shows up, and I get an error in the gui stating that the connection to domoticz was refused, even though it works fine.  I fixed the error by putting a return 0 at the beginning of "def checkupdate():" in smarthome.py

> 127.0.0.1 - - [01/Jan/2020 18:02:54] "GET /settings?code=67f92aa2a2274e82899742814e2f5ecf&state=undefined HTTP/1.1" 307 -
127.0.0.1 - - [01/Jan/2020 18:02:54] "GET /login?redirect_uri=/settings HTTP/1.1" 200 -
127.0.0.1 - - [01/Jan/2020 18:02:55] "POST /login HTTP/1.1" 301 -
Connection to Github refused! Check configuration.
Connection to Github refused! Check configuration.
127.0.0.1 - - [01/Jan/2020 18:02:55] "GET /settings?code=aa4471294d0f4fd087bd001ae0d54034&state=undefined HTTP/1.1" 200 -

**Comment by DewGew** [comment]
I did some more changes try v1.4.6 sync your devices first before query termostat

**Comment by DewGew** [comment]
if you update manually use:
 ` git reset --hard`
then
 ` git pull`

**Comment by j0nson** [comment]
Im still having problems running the beta branch, I got the error connecting to Domoticz, and no devices show up in the gui. I suspect it's a get / post issue, unrelated to the temperature issue. I'm using the same settings as the stable branch, so there should be no issue with connections. The log doesn't show anything interesting, even with it set to debug.

I'll test more later, maybe by pulling in the temperature conversion changes into the stable branch.

**Comment by j0nson** [comment]
Since I cannot get the beta branch to run correctly, I tested with master, but with the traits.py from the beta branch, and in helpers.py, I added the tempConvert function from the beta.  I believe these were the only relevant changes.  Everything runs correctly, but Google Home still shows incorrect temps.

I got it to work by changing this function to always return "F", and added in some debugging output:
> def _google_temp_unit(units):
    """Return Google temperature unit."""
    print("Google Temp Unit")
    print(units)
    if units == True:
        return "F"
        print("Google Temp Unit F")
    #return "C"
    return "F"

The output when checking a temperature device is:
> http://[URL]:[PORT] "GET /json.htm?type=settings HTTP/1.1" 200 1419
Google Temp Unit
None
Google Temp Unit
None
127.0.0.1 - - [02/Jan/2020 21:17:09] "POST /smarthome HTTP/1.1" 200 -
Response: {
  "requestId": "17737534401830420235",
  "payload": {
    "devices": {
      "Thermostat120": {
        "online": true,
        "thermostatMode": "heat",
        "thermostatTemperatureAmbient": 15.6,
        "thermostatTemperatureSetpoint": 15.6
      }
    }
  }
}

If I check the device again, the debug output changes to:

> Google Temp Unit
1
Google Temp Unit
1

Also, the same changes you made to "domain == tempDOMAIN" should be made in "domain == climateDOMAIN" (in traits.py), to get it to work with thermostats.  Unrelated, it would be great to link two devices to give proper ambient temperatures along with a setpoint temp, but I suppose this is a limitation in domoticz.

**Comment by DewGew** [comment]
Can you print the device json from domticz here. I only have virtual dummy thermostat those dont have a Temp in json so its not needed to convert to celcius.

**Comment by j0nson** [comment]
Here's one:

> {
   "ActTime" : 1578014594,
   "AstrTwilightEnd" : "18:31",
   "AstrTwilightStart" : "05:51",
   "CivTwilightEnd" : "17:24",
   "CivTwilightStart" : "06:57",
   "DayLength" : "09:28",
   "NautTwilightEnd" : "17:58",
   "NautTwilightStart" : "06:23",
   "ServerTime" : "2020-01-02 20:23:14",
   "SunAtSouth" : "12:11",
   "Sunrise" : "07:27",
   "Sunset" : "16:54",
   "app_version" : "4.10717",
   "result" : [
      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 0,
         "Data" : "68.0 F",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 22,
         "HardwareName" : "Dummy Sensors",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveTimeout" : false,
         "ID" : "140C7",
         "LastUpdate" : "2020-01-02 20:00:16",
         "Name" : "Kitchen Floor Temperature",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "LaCrosse TX3",
         "Temp" : 68.0,
         "Timers" : "false",
         "Type" : "Temp",
         "TypeImg" : "temperature",
         "Unit" : 1,
         "Used" : 1,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "119",
         "trend" : 0
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}

**Comment by DewGew** [comment]
I cant reproduce your issues. sorry. Send me your config.yaml and log file by email , you can change your personal credetials to something random.

**Comment by DewGew** [comment]
Thermostat should work as suppost? I added some more logging in latest beta. 
Back up your config.yaml and then delete Domoticz-Google-Assistant folder the run install script
`bash <(curl -s https://raw.githubusercontent.com/DewGew/dzga-installer/master/install.sh)`
choose development branch

**Comment by j0nson** [comment]
The latest beta runs without error for me, and the temperatures are reading correctly for temperature sensors.
My domoticz thermostat setpoint device was not reading correct, until I made this change in the code in trait.py:

> if domain == climateDOMAIN:
            response['thermostatMode'] = 'heat'
            current_temp = float(self.state.state)
            if current_temp is not None:
                response['thermostatTemperatureAmbient'] = round(tempConvert(current_temp,  _google_temp_unit(units)), 1)
            setpoint = float(self.state.setpoint)
            if setpoint is not None:
                response['thermostatTemperatureSetpoint'] = round(tempConvert(setpoint ,  _google_temp_unit(units)), 1)

**Comment by DewGew** [comment]
Added in latest beta
