### ISSUE TITLE
Temperature doesnt update on first check.

### ISSUE THREAD

**Issue by ressof** [DewGew/Domoticz-Google-Assistant#7]
When I ask after a temperature I get an old value. When I ask again then I get the actual value.
Same thing happens in the Goolge Home App. When I push on a temperature I get an old value and when I go back and push the temperature again I get the actual value.

Does anybody else has this problem?

Edit:
I see now that the same thing happens on the switches and dimmers.

**Comment by EldigoR** [comment]
I didn't noticed it  before but yes I too get the the old value first.

**Comment by DewGew** [comment]
I dont have that issue. When I push a temp device, I see in terminal query request and in domoticz log I can see a connection.  I got same value as in domoticz .

**Comment by ressof** [comment]
Try this.
Press a light switch in Google Home App to see its state.
Then go back to home screen.
Change the state on the switch in Domoticz.
Press the light again in Google Home App to see if the state is correct.

**Comment by DewGew** [comment]
Yes now I get it

**Comment by DewGew** [comment]
Make a git pull and try now. I added getdevice() to query https://github.com/DewGew/Domoticz-Google-Assistant/commit/a2059e7604ae81875483d552b550cab587596f8e#diff-6fb23df4ce8ce8f42462cf9754c15992R433

**Comment by ressof** [comment]
Now its working
