### ISSUE TITLE
Problem Autorization

### ISSUE THREAD

**Issue by kasiporik** [DewGew/Domoticz-Google-Assistant#71]
Hi, i haw a proble at stable release and developer release, autorization don't working, how this Issues https://github.com/DewGew/Domoticz-Google-Assistant/issues/23
Check stable and developer release, help me please

**Comment by kasiporik** [comment]
oauth?redirect_uri=https%3A%2F%2Foauth-redirect.googleusercontent.com%2Fr%2Fkasiporik-d5817&client_id=************&user_locale=ru-RU

**Comment by DewGew** [comment]
Go over setup [Actions on Google](https://github.com/DewGew/Domoticz-Google-Assistant/wiki/3.-Setup-Actions-on-Google) again. I think that is the issue.

**Comment by kasiporik** [comment]
I reconfigure actions, don't working, screen actions on link
https://cloud.mail.ru/public/3uta/4ERVGNC4u
https://cloud.mail.ru/public/23gD/ZQNKq3j5j
https://cloud.mail.ru/public/5CkW/3fnQ4eBoJ

**Comment by kasiporik** [comment]
I thing %3A%2F%2F coding problem,

**Comment by DewGew** [comment]
Dont forget to press ”test” button

**Comment by kasiporik** [comment]
test buton click - on, don't work, i change reliase version to developer - don't work, recreate service account,api,and oauth token

**Comment by kasiporik** [comment]
homegraph api 36 errors

**Comment by kasiporik** [comment]
after autorization in my phone, i connect in my app again, i see error Not found, request url not found

**Comment by kasiporik** [comment]
i recreate service account is wirking,1.4.6, thank u, close ticket
