### ISSUE TITLE
Configurable place for log file

### ISSUE THREAD

**Issue by SargonofAssyria** [DewGew/Domoticz-Google-Assistant#73]
Feature request.
It would be nice if the place of the logfile could be configurable.
I have all my logfiles in /var/log/* and that is a ramfile.
So on my Raspberry Pi it will not wear out my SD-card.

**Comment by DewGew** [comment]
Can be a problem with permissons. Dzga usually runs as user but to write to var/log/* it need root permissions.

**Comment by SargonofAssyria** [comment]
I can handle that. Perhaps some additional comments in the Wiki and config file about permissions for users who do not know how to handle that.

**Comment by SargonofAssyria** [comment]
Tnx, It works.
