### ISSUE TITLE
First start configuration problem

### ISSUE THREAD

**Issue by bizziebis** [DewGew/Domoticz-Google-Assistant#77]
When I install the latest version, I run into a problem when trying to start the service. The configuration file is created because it does not exist yet, but it's filled with 'Problem opening this file'.

I think it's because of the readFile function which is trying to open the default_config from a relative location 

> file = open(filename, 'r+')

Instead of an absolute location

> file = open(os.path.join(FILE_DIR, filename), 'r+')

**Comment by DewGew** [comment]
Thanks for pointing this out. Issue is this line:
https://github.com/DewGew/Domoticz-Google-Assistant/blob/477a20597a84a08143b09635e32bf8dc80404137/helpers.py#L54

I have change this line to:
 `content = readFile(os.path.join(FILE_DIR,'default_config'))`

**Comment by bizziebis** [comment]
You are right! It would probably cause problems with log file location when you would change the function.

Thanks for the quick response.
