### ISSUE TITLE
Device control

### ISSUE THREAD

**Issue by afrieswijk** [DewGew/Domoticz-Google-Assistant#82]
What an awesome solution, great work!

I have a problem with devices in GA. for example i don't get my fan with modes in google home, but also not my thermostat programs with a selector.

So i have the idea to create a devicecontrol option like you did with voicecontrol. The devicecontrol could then be set in config.yaml or in the description field within domoticz.
The devicecontrol should have the devicetype and the devicetrait in it.
With this we can flexibel manage the devices from domoticz to GA.

Is this an idea to create in a future release?

**Comment by SargonofAssyria** [comment]
I agree, it would be nice to have some more control over the devices.
I have the same kind of problem with Thermostats (read and write) and Temperature devices (read-only)

**Comment by DewGew** [comment]
How doeas you fan work in domoticz is it switch or selelcor?.
dzga supports seletor switches.  Google ignore devices with device names with special characters. I need more info if you want to solve those issues. If you delays with thermostats or temperatures try set reports state to false for that device.

Options for advanced user is a good idea. Device type its not a big issue its more or less the icon in google home app. Devicetrait is more complex. A device can have several traits and there is around 25 to choose from.

**Comment by afrieswijk** [comment]
In my domoticz my Fan and Thermostat program are both selector switches and i see from the sync that dzga is determining it as a selector, but the trait becomes TOGGLES and that's not right i asume. In the attachtment i have put my domoticz devices and also the output from the sync of dzga. I hope you can help. Thanks a lot in  advance.

Also thanks for the information about that selector switches don't have a graphical selector within Google, i didn't know that.

About my suggestion to create somethin like devicecontrol with type (easy as you mention) and trait (hard, but maybe you can limit this one now and probably can grow in the future to the 25). Just as an idea.
[DZGA-selector-problem.docx](https://github.com/DewGew/Domoticz-Google-Assistant/files/4052881/DZGA-selector-problem.docx)

**Comment by DewGew** [comment]
I put in toggles trait, that is (for now) enough for selector switches. I dont see the benefit with modes trait now, but its possible to rewrite to modes traits if needed.

**Comment by afrieswijk** [comment]
Sorry for the late response.

I can confirm that everything works with the assistant fro the selector switches, but in Google Home is liked to see also the selector switches, so i can handle/use them also from that one. But you said that Home doesn't support them, so it has indeed no need. Nevertheless i think it would be better to use modes, because toggles can only switch between two values the documentaion says. For future use it would prefer the mode trait.

To add the devicetype would be prefferable, because with that we can adjust the right icon to it. My google home app becomes with that more clear. Would be nice to have.

I have indeed two devices for my thermostat, 1 for the temperature and 1 for the program modes.

**Comment by DewGew** [comment]
Feature request moved to #92

**Comment by DewGew** [comment]
Try out latest Beta #130
