### ISSUE TITLE
Devices sync dont work anymore

### ISSUE THREAD

**Issue by aurelhh** [DewGew/Domoticz-Google-Assistant#86]
1) When clinking on "sync devices" message "Page not found!: Can't convert 'NoneType' object to str implicitly" appear and devices dont sync

2) The only way to sync is to reboot the service

Domoticz 4.10717 on synology
DZGA 1.5.5

No logs
```
Paste the dzga logs here.
```

**Desktop (please complete the following information):**
 - Domoticz version 
 - Dzga version 
 - Python Version 

**Smartphone (please complete the following information):**
 - Device: 

**Additional context, screenshot:**

**Comment by DewGew** [comment]
Are you running dzga on synology also?

**Comment by aurelhh** [comment]
Tk for your response
Yes all in synology

**Comment by DewGew** [comment]
I havent test this in synology. I need test this

**Comment by DewGew** [comment]
I tested on my synology DS216 with Python 3.5.1 and dzga v1.5.5 master. Its working for me correct

**Comment by aurelhh** [comment]
ok thanks i will try to reinstall it. I don't understand, seems to work correctly before

**Comment by bizziebis** [comment]
The only thing I ever got from pressing sync is this:

> Page not found!: 404 Client Error: Not Found for url: https://homegraph.googleapis.com/v1/devices:requestSync

When asking Google Assistant to "synchronize my devices", it does sync though.

**Comment by DewGew** [comment]
Hmm seems like you cant send request to homegraph. Not valid json or Something is blocking your http reguest.
- Make sure the json file is for same project you use for dzga.
- Try Goto action on google and press Test button again.

**Comment by DewGew** [comment]
> 404 - Failure: 
> The requested resource could not be found but may be available in the future. Subsequent requests by the client are permissible. Typically, this means that we cannot find either the user (agentUserId) or the device. It may also mean that the user has not yet linked with Google, or you didn't send the agentUserId in the SYNC response.

**Comment by bizziebis** [comment]
For some reason the HomeGraph API was enabled for the wrong project. It defaulted to a different project and didn't even show the correct project. I had to do a search..

Now it's working!
