### ISSUE TITLE
1 server for multiple domoticz instance

### ISSUE THREAD

**Issue by lily148** [DewGew/Domoticz-Google-Assistant#9]
Hi,

Can I setup only 1 server but for many different domoticz instance?
Example, I have 2 houses and 1 office in different location.
I want to setup only 1 server but the domoticz will be at 3 different location.
3 different login because I don't want to join the item in to one. Of course, we have 3 different phone.

**Comment by DewGew** [comment]
Like this then?
House 1 -- user 1, House 2 -- user 2, Office -- user 3

**Comment by lily148** [comment]
Ya... but I don't want all smart devices in 3 different group in a google home.

**Comment by DewGew** [comment]
Not what you are looking for but you can try this: https://github.com/DewGew/Domoticz-Google-Assistant#share-devices
