### ISSUE TITLE
Device changes/updates in Domoticz not updated on Assistant

### ISSUE THREAD

**Issue by Failure404** [DewGew/Domoticz-Google-Assistant#94]
Hi,
using 1.5.5, when querying Assistant if a device is on I only get state from last manual sync.
Any change of state in Domoticz is not being reflected in Google Assistant.
For example, light x is off. I ask Assistant if light x is on. Assitant tells me light x is off. In Domoticz I turn on light x. I ask Assistant if light x is on. Assistant tells me light x is off.
Same with temperature devices. I only get the temperature from last manual sync.
It never updates.
Running DZGA behind a nginx reverse proxy. When I turn on/off devices using Assistant, I can see queries coming from Google in the reverse proxy logs. I would expect incoming queries from Google when I ask for the state of a specific device, but nothing appears in the reverse proxy log.
Does DZGA send device changes to Assistant as they happen, or does Assistant query DZGA if asked for the state of a device?

**Comment by DewGew** [comment]
dzga get latest state from domoticz when querying a device.
https://github.com/DewGew/Domoticz-Google-Assistant/blob/fed00c84f44c62f84c6893b61bfbd0539c193b7b/smarthome.py#L695

Try run without report state (rename smart-home-key.json to something else)

**Comment by Failure404** [comment]
Allright,
thank you for your support.
I've added "report_state = false" to all my device's descriptions and left smart-home-key.json untouched.
Everything seems to be working now, so I am closing this issue.
Again, thank you very much for your work.

**Comment by rezzalex** [comment]
since a while, I found that my temperature devices were too slow to answer...
I tried to remove the smart-home-key.json and now it is immediate... why ?
