### ISSUE TITLE
Configuration editing

### ISSUE THREAD

**Issue by SzemiSun** [DewGew/Domoticz-Google-Assistant#99]
**Describe the bug:**  
I change my configuration via UI and the paswords (auth_pass or Domoticz.password) contain special characters (like '+'),

**Expected behavior:**  
It hasn't saved to the config.yaml
Example: auth_pass is 'Pass1234+', but the config file contains auth_pass: 'Pass1234 '

dzga log:
2020-01-19 13:24:01 - INFO - Config saved
Nothing else... :(

**Desktop (please complete the following information):**
 - Domoticz version  Beta 4.11605
 - Dzga version 1.5.6 
 - Python Version 3.5.3

Btw: Many thanks for your works! This project is fantastic!!

**Comment by DewGew** [comment]
If you want + in your passwords you have to edit config.yaml manully. The UI editor removes all + signs
